### ISSUE TITLE
学習時のエラーについて

### ISSUE THREAD

**Issue by Ursprung-OtsuDurham1832** [kohya-ss/sd-scripts#1038]
本家のこちらにお聞きする内容なのか不明なのですが、
フォーク版kohya_ss(https://github.com/bmaltais/kohya_ss)を使用していて
git pullでアップデートした後からLoRA学習したものをSDで生成をかけるとエラーが出るため
ローカル上改めて環境を作り直しWeb UI起動までできているのですが、
肝心の学習時に以下エラーが出て
```
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\bmaltais\kohya_ss\library\train_util.py", line 3480, in get_optimizer
    import bitsandbytes as bnb
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bmaltais\kohya_ss\train_network.py", line 996, in <module>
    trainer.train(args)
  File "C:\bmaltais\kohya_ss\train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\bmaltais\kohya_ss\library\train_util.py", line 3482, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bmaltais\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\bmaltais\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\bmaltais\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=N:/hogehoge/SD_Models/SD_Stable-diffusion_Model/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=C:/kohya_gui/kohya_ss/image/Study_Materials', '--resolution=512,512', '--output_dir=C:/kohya_gui/kohya_ss/image/Study_completion_material/6_hogehoge_hogehoge_out', '--logging_dir=C:/kohya_gui/kohya_ss/image/Study_completion_material/6_hogehoge_hogehoge_out/logs', '--network_alpha=4', '--training_comment=hogehoge_hogehoge', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=16', '--output_name=hogehoge_hogehoge_For_hogehoge_hogehoge_0_01Ver', '--lr_scheduler_num_cycles=10', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=300', '--train_batch_size=1', '--max_train_steps=6000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
```
「bitsandbytesがインストールされていないようです」との表示が出ているのですが
bitsandbytes自体フォルダとしてもファイルとしてもあるようで
Kohyaさんの日本語ドキュメントに記載のオプションでのインストールも何度試してもちゃんとインストールが出来なくにっちもさっちもいかない状態になっています。
こちら対処方法などありましたらご教示いただけないでしょうか？

**Comment by Ursprung-OtsuDurham1832** [comment]
@kohya-ss 
ご教示いただいた内容を試してみたところ起動成功しました。
ありがとうございました。
こちらで一旦学習を試してSD側で反映できるか確認してみます。
