### ISSUE TITLE
crshed when use 2.1 SD ckpt, changed to 1.5,still crash

### ISSUE THREAD

**Issue by gdx09090909** [kohya-ss/sd-scripts#105]
when choose 2.1 ckpt,it crashed as misssize,like no yaml in webui
then i choose 1.5,it seems like this:
it is a cloud machine,i have no D:\ai folder.

steps:   0%|                                                                                    | 0/25 [00:00<?, ?it/s]epoch 1/5
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\1\lora\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\1\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Administrator\1\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Administrator\1\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\1\\lora\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.

i have only C:\

**Comment by anon-1337** [comment]
> `Error no kernel image is available for execution on the device at line 167`

I was running into the same problem. My 1060 refused to start trainining process. I replaced library located in
`.\sd-scripts\venv\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll`
with [this library instead](https://github.com/james-things/bitsandbytes-prebuilt-all_arch/blob/main/libbitsandbytes_cudaall.dll) and it worked.

**Comment by gdx09090909** [comment]
> > `Error no kernel image is available for execution on the device at line 167`
> 
> I was running into the same problem. My 1060 refused to start trainining process. I replaced library located in `.\sd-scripts\venv\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll` with [this library instead](https://github.com/james-things/bitsandbytes-prebuilt-all_arch/blob/main/libbitsandbytes_cudaall.dll) and it worked.

can u do a training with SD 2.X ? the bug log seems like when webui lack yaml ,but i dont know how to use yaml on lora

**Comment by anon-1337** [comment]
Yes, I can. You must have a corresponding yaml file in the same folder as model. If you're loading SD 2.x checkpoint, you should pass `--v2` to the arguments. If you are loading SD 2.x-768 checkpoint, you should pass `--v2 --v_parameterization` to the arguments.
