### ISSUE TITLE
SDXL Lora Training: met "AttributeError: 'NoneType' object has no attribute 'dtype', "

### ISSUE THREAD

**Issue by ericbao2000** [kohya-ss/sd-scripts#1050]
1. Using commit 842d9c7018288d5c3d6e01adc0d7f886b70252b6 (HEAD -> master, tag: v22.4.1, origin/master, origin/HEAD)
Merge: 89cfc46 bc0a7bf
Date:   Tue Jan 2 20:33:27 2024 -0500
2. MACOS   
3. Met the issue below
User/Documents/kohya_ss/library/sdxl_train_util.py", line 103, in _load_target_model
 if text_encoder2.dtype != torch.float32:
AttributeError: 'NoneType' object has no attribute 'dtype', 

I am not clear with how to set the attribution for text_encoder2

Thanks,
Eric

**Comment by DKnight54** [comment]
Can you share the full traceback stack?

**Comment by ericbao2000** [comment]
**Here is the full back trace**

21:08:02-170907 INFO     Start training LoRA Standard ...                                                                
21:08:02-173950 INFO     Checking for duplicate image filenames in training data directory...                            
21:08:02-176623 INFO     Valid image folder names found in: /Users/lilyzhang/Documents/ai/Picture                        
21:08:02-178653 INFO     Folder 100_eric_bao: 8 images found                                                             
21:08:02-180191 INFO     Folder 100_eric_bao: 800 steps                                                                  
21:08:02-181581 INFO     Total steps: 800                                                                                
21:08:02-182684 INFO     Train batch size: 2                                                                             
21:08:02-183792 INFO     Gradient accumulation steps: 1                                                                  
21:08:02-184931 INFO     Epoch: 8                                                                                        
21:08:02-185972 INFO     Regulatization factor: 1                                                                        
21:08:02-187068 INFO     max_train_steps (800 / 2 / 1 * 8 * 1) = 3200                                                    
21:08:02-188476 INFO     stop_text_encoder_training = 0                                                                  
21:08:02-189978 INFO     lr_warmup_steps = 0                                                                             
21:08:02-191217 INFO     Saving training config to                                                                       
                         /Users/lilyzhang/Documents/ai/LoRa/kohya_ss/embedding/ericbao_v1.0_20240116-210802.json...      
21:08:02-192791 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket     
                         --min_bucket_reso=64 --max_bucket_reso=2048                                                     
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"                                
                         --train_data_dir="/Users/lilyzhang/Documents/ai/Picture" --resolution="512,512"                 
                         --output_dir="/Users/lilyzhang/Documents/ai/LoRa/kohya_ss/embedding"                            
                         --logging_dir="/Users/lilyzhang/Documents/ai/LoRa/kohya_ss/log" --network_alpha="128"           
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0001             
                         --unet_lr=0.0001 --network_dim=128 --output_name="ericbao_v1.0" --lr_scheduler_num_cycles="8"   
                         --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2"         
                         --max_train_steps="3200" --save_every_n_epochs="1" --mixed_precision="fp16"                     
                         --save_precision="fp16" --seed="12345" --caption_extension=".txt" --cache_latents               
                         --cache_latents_to_disk --optimizer_type="AdamW" --max_grad_norm="1"                            
                         --max_data_loader_n_workers="0" --bucket_reso_steps=32 --save_last_n_steps_state="1"            
                         --gradient_checkpointing --xformers --noise_offset=0.0                                          
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory /Users/lilyzhang/Documents/ai/Picture/100_eric_bao contains 8 image files
800 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 64
  max_bucket_reso: 2048
  bucket_reso_steps: 32
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "/Users/lilyzhang/Documents/ai/Picture/100_eric_bao"
    image_count: 8
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator: 
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: eric_bao
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 765.56it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 576), count: 100
bucket 1: resolution (480, 544), count: 100
bucket 2: resolution (512, 512), count: 600
mean ar error (without repeats): 0.0077008016748365965
preparing accelerator
/Users/lilyzhang/Documents/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5, variant=fp16
Loading pipeline components...: 100%|██████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.03it/s]
Traceback (most recent call last):
  File "/Users/lilyzhang/Documents/kohya_ss/./sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "/Users/lilyzhang/Documents/kohya_ss/train_network.py", line 234, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/Users/lilyzhang/Documents/kohya_ss/./sdxl_train_network.py", line 47, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "/Users/lilyzhang/Documents/kohya_ss/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "/Users/lilyzhang/Documents/kohya_ss/library/sdxl_train_util.py", line 103, in _load_target_model
    if text_encoder2.dtype != torch.float32:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/Users/lilyzhang/Documents/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/lilyzhang/Documents/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Users/lilyzhang/Documents/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/Users/lilyzhang/Documents/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/lilyzhang/Documents/kohya_ss/venv/bin/python', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=64', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/Users/lilyzhang/Documents/ai/Picture', '--resolution=512,512', '--output_dir=/Users/lilyzhang/Documents/ai/LoRa/kohya_ss/embedding', '--logging_dir=/Users/lilyzhang/Documents/ai/LoRa/kohya_ss/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.0001', '--unet_lr=0.0001', '--network_dim=128', '--output_name=ericbao_v1.0', '--lr_scheduler_num_cycles=8', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=3200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=12345', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=32', '--save_last_n_steps_state=1', '--gradient_checkpointing', '--xformers', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by DKnight54** [comment]
Ah. Like I guess then. You are trying to train on the wrong model. SDXL_train_network.py only works for SDXL style models where there are two text encoders. Please try using the SDXL model instead. ("stabilityai/stable-diffusion-xl-base-1.0")

![image](https://github.com/kohya-ss/sd-scripts/assets/126916963/b2f3b466-f055-44ae-b25e-a307330edab2)

**Comment by chucknorris123453** [comment]
> if you are trying to train on SD1.5, please use train_network.py

How?
