### ISSUE TITLE
Error ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths' and i have try "activate" and "pip install bitsandbytes-windows"

### ISSUE THREAD

**Issue by nickthesail0r** [kohya-ss/sd-scripts#1062]
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\library\train_util.py", line 3497, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\train_db.py", line 503, in <module>
    train(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\train_db.py", line 182, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\library\train_util.py", line 3499, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\salto\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\salto\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Onlyfans-Silvia-Tongana\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--v2', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=512', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1-base', '--train_data_dir=C:/Onlyfans-Silvia-Tongana/Train2/Training\\img', '--reg_data_dir=C:/Onlyfans-Silvia-Tongana/Train2/Training\\reg', '--resolution=512,512', '--output_dir=C:/Onlyfans-Silvia-Tongana/Train2/Training\\model', '--logging_dir=C:/Onlyfans-Silvia-Tongana/Train2/Training\\log', '--save_model_as=safetensors', '--output_name=silvia_pose', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=0', '--learning_rate_te=1e-05', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=80', '--train_batch_size=1', '--max_train_steps=800', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--resume=C:/Onlyfans-Silvia-Tongana/Train2/Training', '--bucket_reso_steps=64', '--save_state', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--sample_sampler=dpm_2', '--sample_prompts=C:/Onlyfans-Silvia-Tongana/Train2/Training\\model\\sample\\prompt.txt', '--sample_every_n_epochs=1']' returned non-zero exit status 1.

**Comment by EugeoSynthesisThirtyTwo** [comment]
I did it, it says
```
Requirement already satisfied: bitsandbytes==0.41.1 in c:\users\armaguedin\documents\dev\python\kohya_ss\venv\lib\site-packages (0.41.1)
```

and when I restart gui.bat and click "start training" I have the same error

**Comment by EugeoSynthesisThirtyTwo** [comment]
It works thank you !

**Comment by nickthesail0r** [comment]
Trying both ways unistall and install bitsandbytes and also remove folders etc.trying the activate but i get this error again......


19:35:30-807410 INFO     Version: v22.5.0

19:35:30-816408 INFO     nVidia toolkit detected
19:35:32-766679 INFO     Torch 2.0.1+cu118
19:35:32-792760 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
19:35:32-794836 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 6144 Arch (7, 5) Cores 30
19:35:32-796871 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
19:35:32-799871 INFO     Verifying modules installation status from requirements.txt...
19:35:36-174774 INFO     headless: False
19:35:36-178810 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
19:35:51-927736 INFO     Loading config...
19:35:54-096624 INFO     Start training LoRA Standard ...
19:35:54-098626 INFO     Checking for duplicate image filenames in training data directory...
19:35:54-100627 INFO     Valid image folder names found in: C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\img
19:35:54-102625 INFO     Valid image folder names found in: C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\reg
19:35:54-104628 INFO     Folder 40_koula woman: 44 images found
19:35:54-105626 INFO     Folder 40_koula woman: 1760 steps
19:35:54-107629 WARNING  Regularisation images are used... Will double the number of steps required...
19:35:54-108623 INFO     Total steps: 1760
19:35:54-110594 INFO     Train batch size: 1
19:35:54-111590 INFO     Gradient accumulation steps: 1
19:35:54-113602 INFO     Epoch: 1
19:35:54-114592 INFO     Regulatization factor: 2
19:35:54-116628 INFO     max_train_steps (1760 / 1 / 1 * 1 * 2) = 3520
19:35:54-117631 INFO     stop_text_encoder_training = 0
19:35:54-119628 INFO     lr_warmup_steps = 352
19:35:54-120624 INFO     Saving training config to
                         C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\model\koula_20240128-193554.json...
19:35:54-125625 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\img"
                         --reg_data_dir="C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\reg" --resolution="512,512"
                         --output_dir="C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\model"
                         --logging_dir="C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\log" --network_alpha="1"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=8 --output_name="koula" --lr_scheduler_num_cycles="1"
                         --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="352" --train_batch_size="1"
                         --max_train_steps="3520" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --cache_latents --optimizer_type="AdamW" --max_grad_norm="1"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale
                         --noise_offset=0.0
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman contains 44 image files
No caption file found for 44 images. Training will continue without captions for these images. If class token exists, it will be used. / 44枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_13-58-02_1811.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_14-00-50_9646.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_14-03-39_6525.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_14-47-35_6368.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_14-50-03_4124.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman\2024-01-18_14-54-56_8027.png... and 39 more
found directory C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman contains 12 image files
No caption file found for 12 images. Training will continue without captions for these images. If class token exists, it will be used. / 12枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-12_02-57-30_8473.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-14_14-33-27_7869.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-15_00-23-39_8616.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-15_23-35-04_6800.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-15_23-58-22_1043.png
C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman\2024-01-17_03-36-32_8960.png... and 7 more
1760 train images with repeating.
12 reg images.
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\img\40_koula woman"
    image_count: 44
    num_repeats: 40
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: koula woman
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "C:\Users\salto\OneDrive\Υπολογιστής\train\trehn\reg\1_woman"
    image_count: 12
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: woman
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 2377.82it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 292
bucket 1: resolution (512, 512), count: 3228
mean ar error (without repeats): 0.0018494897959183687
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.47it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable xformers for U-Net
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 56/56 [00:07<00:00,  7.78it/s]
create LoRA network. base dim (rank): 8, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1760
  num reg images / 正則化画像の数: 12
  num batches per epoch / 1epochのバッチ数: 3520
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 3520
steps:   0%|                                                                                  | 0/3520 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\train_network.py", line 998, in <module>
    trainer.train(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\train_network.py", line 691, in train
    accelerator.init_trackers(
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 619, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2331, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 79, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 190, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 247, in __init__
    self._get_file_writer()
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\log is not a directory
steps:   0%|                                                                                  | 0/3520 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Onlyfans-Silvia-Tongana\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Onlyfans-Silvia-Tongana\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\\img', '--reg_data_dir=C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\\reg', '--resolution=512,512', '--output_dir=C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\\model', '--logging_dir=C:/Users/salto/OneDrive/Υπολογιστής/train/trehn\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=koula', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=352', '--train_batch_size=1', '--max_train_steps=3520', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
