### ISSUE TITLE
NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by Lordxan** [kohya-ss/sd-scripts#109]
While trying to start training i getting this error
Btw i using docker env for that you can see config [here](https://github.com/Lordxan/sd-scripts/commit/a904a51f43891437117a20465851be21c7c66656)
```
steps:   0%|          | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/train/lora_train_popup.py", line 591, in <module>
    main()
  File "/train/lora_train_popup.py", line 204, in main
    train_network.train(args)
  File "/train/train_network.py", line 360, in train
    optimizer.step()
  File "/opt/conda/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined

steps:   0%|          | 0/3000 [00:01<?, ?it/s]
```

**Comment by Lordxan** [comment]
Resolved by adding `RUN sed -i 's/self.use_8bit_adam: bool = True/self.use_8bit_adam: bool = False/' lora_train_popup.py` to dockerfile so basically disabling 8bit adam
