### ISSUE TITLE
Stable Cascade (Würstchen) Support

### ISSUE THREAD

**Issue by alfredplpl** [kohya-ss/sd-scripts#1119]
Stable Cascade (Würstchen) is released.
https://ja.stability.ai/blog/stable-cascade

So, I want to finetune it by this script.
You have implemented it on the Würstchen branch.

The branch is support for Stable Cascade?

**Comment by dill-shower** [comment]
+1

**Comment by ashrafbay** [comment]
+1

**Comment by rdcoder33** [comment]
+1

**Comment by alfredplpl** [comment]
Awesome. I can full-finetune the stage c.

![test](https://github.com/kohya-ss/sd-scripts/assets/3625196/ccc69bfb-9c17-4eac-b49e-13eaa56bee87)

**Comment by alfredplpl** [comment]
btw i got the error:
```bash
2024-02-18 11:32:04 INFO     use 8-bit Lion optimizer | {}                                               train_util.py:3563
enable full bf16 training.
running training / 学習開始
  num examples / サンプル数: 390503
  num batches per epoch / 1epochのバッチ数: 97639
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 4
  gradient accumulation steps / 勾配を合計するステップ数 = 16
  total optimization steps / 学習ステップ数: 1600
steps:   0%|                                                                                      | 0/1600 [00:00<?, ?it/s]
epoch 1/1
Traceback (most recent call last):
  File "/mnt/my_raid/github/sd-scripts/stable_cascade_train_stage_c.py", line 526, in <module>
    train(args)
  File "/mnt/my_raid/github/sd-scripts/stable_cascade_train_stage_c.py", line 442, in train
    current_loss = loss.detach().item()  # 平均なのでbatch sizeは関係ないはず
RuntimeError: a Tensor with 4 elements cannot be converted to Scalar
steps:   0%|                                                                                      | 0/1600 [00:03<?, ?it/s]
```

i think we can fix this error by `current_loss = loss.detach().mean().item()  ` on line 442 in stable_cascade_train_stage_c.py.
how do you think?

**Comment by alfredplpl** [comment]
and i got the error:
```bash
steps:   2%|█                                                    | 1000/48816 [2:19:08<110:53:03,  8.35s/it, avr_loss=0.21]Traceback (most recent call last):
  File "/mnt/my_raid/github/sd-scripts/stable_cascade_train_stage_c.py", line 529, in <module>
    train(args)
  File "/mnt/my_raid/github/sd-scripts/stable_cascade_train_stage_c.py", line 442, in train
    accelerator.accelerator.unwrap_model(stage_c),
AttributeError: 'Accelerator' object has no attribute 'accelerator'
steps:   2%|█                                                    | 1000/48816 [2:19:08<110:53:22,  8.35s/it, avr_loss=0.21]
```

`accelerator.accelerator.unwrap_model(stage_c)` -> `accelerator.unwrap_model(stage_c)` ?

**Comment by dill-shower** [comment]
How many VRAM is required?

**Comment by ashrafbay** [comment]
and lite ؟

**Comment by tetsuoo-online** [comment]
Oh no I'm doomed, I have 12GB

> > How many VRAM is required?
> 
> 16GB VRAM seems to be required with the batch size 1, mixed precision bf16 and AdaFactor optimizer with `relative_step=False`.

**Comment by terrificdm** [comment]
@alfredplpl How about your training result of SC comparing with SDXL? I tried with SC training branch, it turned out that the color and the brightness was not as good as SDXL, everything was dull...

**Comment by alfredplpl** [comment]
@terrificdm I trained SC on an anime dataset with 30000 steps and 5e-4 as a the learning rate. The result is as follows:

before training:

![ComfyUI_temp_fesqj_00014_](https://github.com/kohya-ss/sd-scripts/assets/3625196/650056da-93db-497a-b2f9-4ae3fc672d05)


after training:

![ComfyUI_temp_fesqj_00010_](https://github.com/kohya-ss/sd-scripts/assets/3625196/1ac62dc9-7df6-4263-8821-f678b94a91f8)

prompt:
1girl, white hair, blue eyes, white T-shirt saying "Hello", yellow background

negative prompt:
photo, bad hands, bad anatomy, bad pupil

**Comment by terrificdm** [comment]
> @terrificdm I trained SC on an anime dataset with 30000 steps and 5e-4 as a the learning rate. The result is as follows:
> 
> before training:
> 
> ![ComfyUI_temp_fesqj_00014_](https://private-user-images.githubusercontent.com/3625196/306937347-650056da-93db-497a-b2f9-4ae3fc672d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTQ3MjcsIm5iZiI6MTcwODU5NDQyNywicGF0aCI6Ii8zNjI1MTk2LzMwNjkzNzM0Ny02NTAwNTZkYS05M2RiLTQ5N2EtYjJmOS00YWUzZmM2NzJkMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDkzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY2MzkwYzgyYjI2MDE4YzMyYzUxOGYwYmViYmYzOTZmZjg1ZDE3OTJkM2E1NzcyNjBlYzA2YzM4YzM2ZjYzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SHL-wmZdckWrm_TQ55rUuJwL6V3xgDUYzFJ68pXRXww)
> 
> after training:
> 
> ![ComfyUI_temp_fesqj_00010_](https://private-user-images.githubusercontent.com/3625196/306936602-1ac62dc9-7df6-4263-8821-f678b94a91f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTQ3MjcsIm5iZiI6MTcwODU5NDQyNywicGF0aCI6Ii8zNjI1MTk2LzMwNjkzNjYwMi0xYWM2MmRjOS03ZGY2LTQyNjMtODgyMS1mNjc4Yjk0YTkxZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDkzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFhODMxZmY4NzA2ODJkZmQ5MGY2ZmVkYzllMmU0YjVjZTJkOTJiM2QyNTk0ZTNlNzdhNDg3Y2JlZmNiNmM0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V5TUwkZQlPTzjRKvrpkG9IYPFtejyCU81cdbzP_NMrk)
> 
> prompt: 1girl, white hair, blue eyes, white T-shirt saying "Hello", yellow background
> 
> negative prompt: photo, bad hands, bad anatomy, bad pupil

Thanks, seems nice, and I will try later.

**Comment by alfredplpl** [comment]
@terrificdm Sorry. the learning rate is 5e-6.

**Comment by 2kpr** [comment]
@kohya-ss , Just wanted you to be aware of a known issue (per the Stable Cascade devs themselves - see image attached) with 'loading' the models in bfloat16 vs 'loading' the models in float32 when training. I say 'loading' because even when 'loaded' in float32 there is that small section of the forward pass done in bfloat16 via torch amp as you know.

![scbf16vsfp32](https://github.com/kohya-ss/sd-scripts/assets/96332338/53ffe679-2ba2-475e-91f9-51d55754ecda)

As it mentions in the attached image the issue is that when the models are 'loaded' in float32 Stable Cascade trains much faster and better, but when 'loaded' in bfloat16 Stable Cascade doesn't seem to train at all or very slowly, which then forces you to increase the learning rate, and if you increase that too much then you can more easily overtrain the model.

**Comment by thojmr** [comment]
@kohya-ss Will there be support for training stage_c_lite as well?  It has a slightly different data shape and doesn't want to be loaded during training.  (I think I tested the latest code here)
