### ISSUE TITLE
stable cascade

### ISSUE THREAD

**Issue by ashrafbay** [kohya-ss/sd-scripts#1147]
More than half a month has passed since its release, and I hope that the training script will be released soon. Thanks

**Comment by ashrafbay** [comment]
I am testing it using the Kohya SS branch
But when training starts, it stays stuck like this. 2024-03-02 14:19:41 INFO prepare tokenizers
Also I mean to merge it into the main branch

**Comment by ashrafbay** [comment]
I use colab

**Comment by ashrafbay** [comment]
/content/kohya_ss
venv folder does not exist. Not activating...
Traceback (most recent call last):
  File "/content/kohya_ss/setup/validate_requirements.py", line 19, in <module>
    from library.custom_logging import setup_logging
  File "/content/kohya_ss/library/custom_logging.py", line 6, in <module>
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'

**Comment by ashrafbay** [comment]
OK thanks
