### ISSUE TITLE
AttributeError: module 'mpmath' has no attribute 'rational'

### ISSUE THREAD

**Issue by dfl** [kohya-ss/sd-scripts#1157]
fixed by adding mpmath==1.3.0 to requirements.txt

c.f. https://github.com/NVIDIA/TensorRT-LLM/issues/1145

**Comment by mstoebe** [comment]
This also worked for me!

**Comment by mstoebe** [comment]
```
abc@mbp ComfyUI % python3 main.py --force-fp16
Total VRAM 32768 MB, total RAM 32768 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/Users/abc/Developer/workingCopies/ComfyUI/main.py", line 76, in <module>
    import execution
  File "/Users/abc/Developer/workingCopies/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/Users/abc/Developer/workingCopies/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/Users/abc/Developer/workingCopies/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/Users/abc/Developer/workingCopies/ComfyUI/comfy/sd.py", line 8, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/Users/abc/Developer/workingCopies/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>
    import torchvision
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/ops/__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/ops/poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torchvision/ops/roi_align.py", line 4, in <module>
    import torch._dynamo
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 31, in <module>
    from torch.fx.experimental.symbolic_shapes import (
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>
    from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>
    import sympy
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sympy/__init__.py", line 30, in <module>
    from sympy.core.cache import lazy_function
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sympy/core/__init__.py", line 9, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sympy/core/expr.py", line 4159, in <module>
    from .mul import Mul
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sympy/core/mul.py", line 2193, in <module>
    from .numbers import Rational
  File "/Users/abc/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sympy/core/numbers.py", line 4567, in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
                          ^^^^^^^^^^^^^^^
AttributeError: module 'mpmath' has no attribute 'rational'
```
