### ISSUE TITLE
When using sdxl_train_network.py to train Lora, an error occurs. AttributeError: 'list' object has no attribute 'named_modules'.

### ISSUE THREAD

**Issue by xhh12381** [kohya-ss/sd-scripts#1158]
Traceback (most recent call last):
  File "D:\PycharmProjects\sd-scripts-sdxl\sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "D:\PycharmProjects\sd-scripts-sdxl\train_network.py", line 290, in train
    network = network_module.create_network(
  File "D:\PycharmProjects\sd-scripts-sdxl\networks\dylora.py", line 190, in create_network
    network = DyLoRANetwork(
  File "D:\PycharmProjects\sd-scripts-sdxl\networks\dylora.py", line 310, in __init__
    self.text_encoder_loras = create_modules(False, text_encoder, DyLoRANetwork.TEXT_ENCODER_TARGET_REPLACE_MODULE)
  File "D:\PycharmProjects\sd-scripts-sdxl\networks\dylora.py", line 280, in create_modules
    for name, module in root_module.named_modules():
AttributeError: 'list' object has no attribute 'named_modules'

When I debugged, I found that the Text encoder was a list containing two elements in  sdxl_train_network.py. I think this is the cause of the error in training. Can anyone tell me how to solve this problem?

**Comment by xhh12381** [comment]
There is no problem when I set --network_module=networks.lora. Is it because sdxl does not currently support dylora training?

**Comment by Thiocy** [comment]
@xhh12381 
Hello,

I'm not a developer, but I encountered the same issue and managed to find a workaround that allowed me to run the program successfully. It appears that the `text_encoder` variable is expected to be a single module, but it is actually a list, which leads to the `AttributeError`. To get around this, I modified the code in `train_network.py` to pass a single text encoder module to the `create_network` function instead of a list.

Here's what I changed:
```python
if args.dim_from_weights:
    network, _ = network_module.create_network_from_weights(1, args.network_weights, vae, text_encoder, unet, **net_kwargs)
else:
    if "dropout" not in net_kwargs:
        # workaround for LyCORIS (;^ω^)
        net_kwargs["dropout"] = args.network_dropout

    network = network_module.create_network(
        1.0,
        args.network_dim,
        args.network_alpha,
        vae,
        text_encoder,
        unet,
        neuron_dropout=args.network_dropout,
        **net_kwargs,
    )
```

To:
```python
if args.dim_from_weights:
    network, _ = network_module.create_network_from_weights(1, args.network_weights, vae, text_encoder, unet, **net_kwargs)
else:
    if "dropout" not in net_kwargs:
        # workaround for LyCORIS (;^ω^)
        net_kwargs["dropout"] = args.network_dropout

    network = network_module.create_network(
        1.0,
        args.network_dim,
        args.network_alpha,
        vae,
        text_encoders[0],  # Use the first element of the text_encoders list
        unet,
        neuron_dropout=args.network_dropout,
        **net_kwargs,
    )
```

This tweak should fix the error by ensuring that a single text encoder module is used when creating the network. I hope this helps others who might be facing the same problem.

Best regards.

**Comment by xhh12381** [comment]
Hi, @Thiocy  
Thanks for your reply, I was aware of this problem before, I didn't do what you did because I was afraid it would cause other problems and the author of the repository didn't answer my query, so I'm still just using the networks.lora module to train the Lora model.
