### ISSUE TITLE
cant resume kohya

### ISSUE THREAD

**Issue by kohler19** [kohya-ss/sd-scripts#1166]
i cant resume the kohya training it seem error like this when i hit start training 
i put 
("C:\Users\examples\Desktop\Train data\For_Test\Train_Data\model\clara_Hans-000009-state),when start ,kohya say ( Traceback (most recent call last):
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\train_network.py", line 460, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\library\train_util.py", line 3511, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2790, in load_state
    raise ValueError(f"Tried to find {input_dir} but folder does not exist")
ValueError: Tried to find C:/Users/cheap/Desktop/Train data/For_Test/Train_Data/model/Siti_Khatijah_Halim-state but folder does not exist
Traceback (most recent call last):
  File "C:\Users\cheap\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cheap\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\cheap\Documents\KOHYA-GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\cheap\\Documents\\KOHYA-GUI\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--cache_latents_to_disk', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--gradient_checkpointing', '--learning_rate=0.0004', '--logging_dir=C:/Users/cheap/Desktop/Train data/For_Test/Train_Data\\log', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_train_steps=8000', '--mixed_precision=bf16', '--network_alpha=1', '--network_dim=256', '--network_module=networks.lora', '--no_half_vae', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--optimizer_type=Adafactor', '--output_dir=C:/Users/cheap/Desktop/Train data/For_Test/Train_Data\\model', '--output_name=Siti_Khatijah_Halim', '--pretrained_model_name_or_path=C:/Users/cheap/Documents/Stable_Diffusion/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors', '--reg_data_dir=C:/Users/cheap/Desktop/Train data/For_Test/Train_Data\\reg', '--resume=C:/Users/cheap/Desktop/Train data/For_Test/Train_Data/model/Siti_Khatijah_Halim-state', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=bf16', '--save_state', '--text_encoder_lr=0.0004', '--train_batch_size=1', '--train_data_dir=C:/Users/cheap/Desktop/Train data/For_Test/Train_Data\\img', '--unet_lr=0.0004', '--xformers']' returned non-zero exit status 1.   and how to fix it ?

**Comment by storuky** [comment]
Please, use formatting. It's hard to read.
According to you error. You said you put `C:\Users\examples\Desktop\Train data\For_Test\Train_Data\model\clara_Hans-000009-state` but backend received `C:/Users/cheap/Desktop/Train data/For_Test/Train_Data/model/Siti_Khatijah_Halim-state` somewhy. This is weird behaviour not typical for sd-scripts.
As far as you use [GUI](https://github.com/bmaltais/kohya_ss) which has new release recently I think you should ask @bmaltais not @kohya-ss
