### ISSUE TITLE
TI errors.

### ISSUE THREAD

**Issue by DarkAlchy** [kohya-ss/sd-scripts#119]
Traceback (most recent call last):
File "D:\kohya_ss\train_textual_inversion.py", line 498, in
train(args)
File "D:\kohya_ss\train_textual_inversion.py", line 260, in train
train_util.patch_accelerator_for_fp16_training(accelerator)
File "D:\kohya_ss\library\train_util.py", line 1345, in patch_accelerator_for_fp16_training
org_unscale_grads = accelerator.scaler.unscale_grads
AttributeError: 'NoneType' object has no attribute 'unscale_grads'

I am getting a few errors when trying to do a TI training and this is just one of them. Another is about - File "D:\kohya_ss\train_textual_inversion.py", line 356, in train
unwrap_model(text_encoder).get_input_embeddings().weight[index_no_updates] = orig_embeds_params[index_no_updates]
RuntimeError: Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.

File "D:\kohya_ss\train_textual_inversion.py", line 498, in
train(args)
File "D:\kohya_ss\train_textual_inversion.py", line 260, in train
train_util.patch_accelerator_for_fp16_training(accelerator)
File "D:\kohya_ss\library\train_util.py", line 1345, in patch_accelerator_for_fp16_training
org_unscale_grads = accelerator.scaler.unscale_grads
AttributeError: 'NoneType' object has no attribute 'unscale_grads'

**Comment by DarkAlchy** [comment]
I don't have enough vram to remove that option (I chose fp16 vs bf16) and how do I find out which version of accelerator I have?
