### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by kitamo1981** [kohya-ss/sd-scripts#1197]
after last step it can't save lora

epoch 1/1
steps: 100%|█████████████████████████████████████████████████████████| 255/255 [01:38<00:00,  2.60it/s, avr_loss=0.143]Traceback (most recent call last):
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 1058, in <module>
    trainer.train(args)
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 926, in train
    self.sample_images(accelerator, args, epoch + 1, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 137, in sample_images
    train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "E:\kohyas\kohya_ss\sd-scripts\library\train_util.py", line 4705, in sample_images
    return sample_images_common(StableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "E:\kohyas\kohya_ss\sd-scripts\library\train_util.py", line 4789, in sample_images_common
    if epoch is None or epoch % args.sample_every_n_epochs != 0:
ZeroDivisionError: integer division or modulo by zero
steps: 100%|█████████████████████████████████████████████████████████| 255/255 [01:38<00:00,  2.59it/s, avr_loss=0.143]
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohyas\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohyas\\kohya_ss\\venv\\Scripts\\python.exe', 'E:\\kohyas\\kohya_ss/sd-scripts/train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=0.0001', '--logging_dir=E:/Lora/Jagoda Lora/log', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--lr_warmup_steps=26', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=512,512', '--max_train_steps=255', '--mixed_precision=fp16', '--network_alpha=1', '--network_dim=8', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--output_dir=E:/Lora/Jagoda Lora/model', '--output_name=last', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=bf16', '--text_encoder_lr=0.0001', '--train_batch_size=1', '--train_data_dir=E:/Lora/Jagoda Lora/image', '--unet_lr=0.0001', '--xformers', '--sample_sampler=euler_a', '--sample_prompts=E:/Lora/Jagoda Lora/model\\sample\\prompt.txt', '--sample_every_n_epochs=0', '--sample_every_n_steps=0']' returned non-zero exit status 1.

**Comment by kitamo1981** [comment]
ok  i got this - its a error with samples generation. Its not working when i set xxx steps, only on full epoch. So need to set "1" epoch and it works almost fine - still cant generate samples per xxx steps
