### ISSUE TITLE
Finetuning Stable Diffusion XL base 1.0 - attention_head_dim missing one head

### ISSUE THREAD

**Issue by padmalcom** [kohya-ss/sd-scripts#1199]
Hi, I tried to finetune the sdxl base 1.0 model on a custom dataset using the following command:

`accelerate launch --num_cpu_threads_per_process 8 fine_tune.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --in_json "D:\Datasets\images\sdxlclean\meta_lat.json" --train_data_dir="D:\Datasets\images\sdxlclean" --output_dir=fine_tuned --shuffle_caption --train_batch_size=1 --learning_rate=5e-6 --max_train_steps=10000 --use_8bit_adam --xformers --gradient_checkpointing --mixed_precision=fp16 --save_every_n_epochs=4 --v2`

At the beginning of the training, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\admin\python\kohya_ss\sd-scripts\fine_tune.py", line 505, in <module>
    train(args)
  File "C:\Users\admin\python\kohya_ss\sd-scripts\fine_tune.py", line 113, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\train_util.py", line 4113, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\train_util.py", line 4088, in _load_target_model
    original_unet = UNet2DConditionModel(
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\original_unet.py", line 1430, in __init__
    attn_num_head_channels=attention_head_dim[i],
IndexError: list index out of range
```

I found out that the attention head dim has a length of 3, but the DOWN_BLOCK_TYPES has a length of 4. This architectural difference between stable diffusion 2.1 and sdxl causes this crash - sd 2.1 has DOWN_BLOCK_TYPES of length 3.

Any fix for the finetuning script is apreciated.

Edit: This could be related to this issue: https://github.com/huggingface/diffusers/issues/2011

**Comment by padmalcom** [comment]
Thank you!

**Comment by min-star** [comment]
run train_db.py,the same error.

`accelerate launch --num_cpu_threads_per_process=1 "train_db.py" --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --train_data_dir="./train_girls/" --reg_data_dir="./reg_girls/"   --resolution="1024,1024"  --output_dir="./model"   --logging_dir="./log" --save_model_as=safetensors --prior_loss_weight=1.0 --max_train_steps=1600 --learning_rate=1e-6 --optimizer_type="AdamW8bit" --xformers --mixed_precision="fp16" --cache_latents --gradient_checkpointing
`

**Comment by min-star** [comment]
![Uploading 截图 2024-07-03 20-07-08.png…]()

**Comment by min-star** [comment]
![Uploading 截图 2024-07-03 20-07-08.png…]()

**Comment by min-star** [comment]
`Traceback (most recent call last):
  File "/home/min/kohya_ss/sd-scripts/train_db.py", line 529, in <module>
    train(args)
  File "/home/min/kohya_ss/sd-scripts/train_db.py", line 123, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/home/min/kohya_ss/sd-scripts/library/train_util.py", line 4387, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/home/min/kohya_ss/sd-scripts/library/train_util.py", line 4363, in _load_target_model
    original_unet = UNet2DConditionModel(
  File "/home/min/kohya_ss/sd-scripts/library/original_unet.py", line 1427, in __init__
    attn_num_head_channels=attention_head_dim[i],
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/min/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/min/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/min/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/min/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
`
