### ISSUE TITLE
PowerShellでのLoRA作成時に「Fatal error in launcher～」と表示され停止する

### ISSUE THREAD

**Issue by tenro11** [kohya-ss/sd-scripts#1225]
初心者質問で申し訳ありません。
こちらでLoRAを作成しようとしたところ、

>>     --pretrained_model_name_or_path=".\model.ckpt"  `
>>     --dataset_config=".\dataset.toml"  `
>>     --output_dir=".\outputs"    `
>>     --output_name=rolaoutput  `
>>     --save_model_as=safetensors  `
>>     --prior_loss_weight=1.0  `
>>     --max_train_steps=400  `
>>     --learning_rate=1e-4  `
>>     --optimizer_type="AdamW8bit"  `
>>     --xformers  `
>>     --mixed_precision="fp16"  `
>>     --cache_latents  `
>>     --gradient_checkpointing `
>>     --save_every_n_epochs=10  `
>>     --network_module=networks.lora

までは進むのですが、その後

Fatal error in launcher: Unable to create process using '"C:\sd-scripts\sd-scripts\venv\Scripts\python.exe"  "C:\sd-scripts\venv\Scripts\accelerate.exe" launch --config_file=.\config.yaml train_network.py --pretrained_model_name_or_path=.\model.ckpt --dataset_config=.\dataset.toml --output_dir=.\outputs --output_name=rolaoutput --save_model_as=safetensors --prior_loss_weight=1.0 --max_train_steps=400 --learning_rate=1e-4 --optimizer_type=AdamW8bit --xformers --mixed_precision=fp16 --cache_latents --gradient_checkpointing --save_every_n_epochs=10 --network_module=networks.lora': ??????????????????

のように表示され進行が止まってしまいます。
解決法をご教授いただければ幸いです。

**Comment by tenro11** [comment]
すみません。
自分なりに色々やってみたのですが駄目でした。

**Comment by tenro11** [comment]
メモ帳に最後に上書きしたのがこれです。

./venv/scripts/activate

start "C:\sd-scripts\venv\Scripts\python.exe" launch --config_file=".\\config.yaml" train_network.py `
--pretrained_model_name_or_path=".\model.ckpt"  `
    --dataset_config=".\dataset.toml"  `
    --output_dir=".\outputs"    `
    --output_name=rolaoutput  `
    --save_model_as=safetensors  `
    --prior_loss_weight=1.0  `
    --max_train_steps=400  `
    --learning_rate=1e-4  `
    --optimizer_type="AdamW8bit"  `
    --xformers  `
    --mixed_precision="fp16"  `
    --cache_latents  `
    --gradient_checkpointing `
    --save_every_n_epochs=10  `
    --network_module=networks.lora

**Comment by tenro11** [comment]
ご返信ありがとうございます。
以下のような状態になりました。

Start-Process : 引数 '--config_file=.\\config.yaml' を受け入れる位置指定パラメーターが見つかりません。
発生場所 行:1 文字:1
+ start "C:\sd-scripts\venv\Scripts\accelerate.exe" launch --config_fil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Process]、ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by tenro11** [comment]
おはようございます。
あの後、カレントディレクトリをC:\sd-scripts\sd-scriptsに移してからアクティベートするところまでは上手くいきましたが、startを外して　
"C:\sd-scripts\venv\Scripts" accelerate launch --config_file=".\\config.yaml" train_network.py `
    --pretrained_model_name_or_path=".\model.ckpt"  `
    --dataset_config=".\dataset.toml"  `
    --output_dir=".\outputs"    `
    --output_name=rolaoutput  `
    --save_model_as=safetensors  `
    --prior_loss_weight=1.0  `
    --max_train_steps=400  `
    --learning_rate=1e-4  `
    --optimizer_type="AdamW8bit"  `
    --xformers  `
    --mixed_precision="fp16"  `
    --cache_latents  `
    --gradient_checkpointing `
    --save_every_n_epochs=10  `
    --network_module=networks.lora　と入力したところ、
発生場所 行:1 文字:30
+ "C:\sd-scripts\venv\Scripts" accelerate launch --config_file=".\\conf ...
+                              ~~~~~~~~~~
式またはステートメントのトークン 'accelerate' を使用できません。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
とのメッセージが出ております。

**Comment by tenro11** [comment]
現在こんな感じです。
動くかな？と思ったら少し間をおいてメッセージが出ています。

(venv) PS C:\sd-scripts\sd-scripts> accelerate launch --config_file=".\\config.yaml" train_network.py `
>>     --pretrained_model_name_or_path=".\model.ckpt"  `
>>     --dataset_config=".\dataset.toml"  `
>>     --output_dir=".\outputs"    `
>>     --output_name=rolaoutput  `
>>     --save_model_as=safetensors  `
>>     --prior_loss_weight=1.0  `
>>     --max_train_steps=400  `
>>     --learning_rate=1e-4  `
>>     --optimizer_type="AdamW8bit"  `
>>     --xformers  `
>>     --mixed_precision="fp16"  `
>>     --cache_latents  `
>>     --gradient_checkpointing `
>>     --save_every_n_epochs=10  `
>>     --network_module=networks.lora
Traceback (most recent call last):
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 995, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 852, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 46, in load_config_from_file
    raise FileNotFoundError(
FileNotFoundError: The passed configuration file `.\\config.yaml` does not exist. Please pass an existing file to `accelerate launch`, or use the the default one created through `accelerate config` and run `accelerate launch` without the `--config_file` argument.

**Comment by tenro11** [comment]
--config_file=".\config.yaml"を外してみました。

(venv) PS C:\sd-scripts\sd-scripts> accelerate launch train_network.py `
>>     --pretrained_model_name_or_path=".\model.ckpt"  `
>>     --dataset_config=".\dataset.toml"  `
>>     --output_dir=".\outputs"    `
>>     --output_name=rolaoutput  `
>>     --save_model_as=safetensors  `
>>     --prior_loss_weight=1.0  `
>>     --max_train_steps=400  `
>>     --learning_rate=1e-4  `
>>     --optimizer_type="AdamW8bit"  `
>>     --xformers  `
>>     --mixed_precision="fp16"  `
>>     --cache_latents  `
>>     --gradient_checkpointing `
>>     --save_every_n_epochs=10  `
>>     --network_module=networks.lora
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-03-31 15:11:22 INFO     prepare tokenizer                                                        train_util.py:3959
2024-03-31 15:11:23 INFO     Loading dataset config from dataset.toml                               train_network.py:162
Traceback (most recent call last):
  File "C:\sd-scripts\sd-scripts\train_network.py", line 1058, in <module>
    trainer.train(args)
  File "C:\sd-scripts\sd-scripts\train_network.py", line 163, in train
    user_config = config_util.load_user_config(args.dataset_config)
  File "C:\sd-scripts\sd-scripts\library\config_util.py", line 628, in load_user_config
    raise ValueError(f"file not found / ファイルが見つかりません: {file}")
ValueError: file not found / ファイルが見つかりません: dataset.toml
Traceback (most recent call last):
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\sd-scripts\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=.\\model.ckpt', '--dataset_config=.\\dataset.toml', '--output_dir=.\\outputs', '--output_name=rolaoutput', '--save_model_as=safetensors', '--prior_loss_weight=1.0', '--max_train_steps=400', '--learning_rate=1e-4', '--optimizer_type=AdamW8bit', '--xformers', '--mixed_precision=fp16', '--cache_latents', '--gradient_checkpointing', '--save_every_n_epochs=10', '--network_module=networks.lora']' returned non-zero exit status 1.

**Comment by tenro11** [comment]
これで合っているでしょうか？
反応は変わったのですが。

(venv) PS C:\sd-scripts\sd-scripts> accelerate launch train_network.py `
>>     --pretrained_model_name_or_path="C:\\Users\\yutam\\model.ckpt" `
>>     --dataset_config="C:\SDXL-Traning\\dataset.toml" `
>>     --output_dir=".\outputs"    `
>>     --output_name=rolaoutput  `
>>     --save_model_as=safetensors  `
>>     --prior_loss_weight=1.0  `
>>     --max_train_steps=400  `
>>     --learning_rate=1e-4  `
>>     --optimizer_type="AdamW8bit"  `
>>     --xformers  `
>>     --mixed_precision="fp16"  `
>>     --cache_latents  `
>>     --gradient_checkpointing `
>>     --save_every_n_epochs=10  `
>>     --network_module=networks.lora
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-03-31 17:42:59 INFO     prepare tokenizer                                                        train_util.py:3959
                    INFO     Loading dataset config from C:\SDXL-Traning\dataset.toml               train_network.py:162
Traceback (most recent call last):
  File "C:\sd-scripts\sd-scripts\train_network.py", line 1058, in <module>
    trainer.train(args)
  File "C:\sd-scripts\sd-scripts\train_network.py", line 199, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "C:\sd-scripts\sd-scripts\library\config_util.py", line 463, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "C:\sd-scripts\sd-scripts\library\train_util.py", line 1378, in __init__
    assert resolution is not None, f"resolution is required / resolution（解像度）指定は必須です"
AssertionError: resolution is required / resolution（解像度）指定は必須です
Traceback (most recent call last):
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\sd-scripts\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:\\\\Users\\\\yutam\\\\model.ckpt', '--dataset_config=C:\\SDXL-Traning\\\\dataset.toml', '--output_dir=.\\outputs', '--output_name=rolaoutput', '--save_model_as=safetensors', '--prior_loss_weight=1.0', '--max_train_steps=400', '--learning_rate=1e-4', '--optimizer_type=AdamW8bit', '--xformers', '--mixed_precision=fp16', '--cache_latents', '--gradient_checkpointing', '--save_every_n_epochs=10', '--network_module=networks.lora']' returned non-zero exit status 1.

**Comment by tenro11** [comment]
これで動いたんですけれども、

accelerate launch train_network.py `
    --pretrained_model_name_or_path="C:\\Users\\yutam\\model.ckpt" `
    --dataset_config="C:\\SDXL-Traning\\dataset.toml" `
    --output_dir=".\outputs"    `
    --output_name=rolaoutput  `
    --save_model_as=safetensors  `
    --prior_loss_weight=1.0  `
    --max_train_steps=400  `
    --learning_rate=1e-4  `
    --optimizer_type="AdamW8bit"  `
    --xformers  `
    --mixed_precision="fp16"  `
    --cache_latents  `
    --gradient_checkpointing `
    --save_every_n_epochs=10  `
    --resolution=512,512 `
    --network_module=networks.lora 

このようになりまして、出力はされませんでした。

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-03-31 18:18:44 INFO     prepare tokenizer                                                        train_util.py:3959
2024-03-31 18:18:45 INFO     Loading dataset config from C:\SDXL-Traning\dataset.toml               train_network.py:162
                    INFO     prepare images.                                                          train_util.py:1469
                    INFO     found directory C:\SDXL-Traning\10_Shizuku contains 20 image files       train_util.py:1432
                    INFO     200 train images with repeating.                                         train_util.py:1508
                    INFO     0 reg images.                                                            train_util.py:1511
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1516
                    INFO     [Dataset 0]                                                              config_util.py:544
                               batch_size: 1
                               resolution: (512, 512)
                               enable_bucket: False
                               network_multiplier: 1.0

                               [Subset 0 of Dataset 0]
                                 image_dir: "C:\SDXL-Traning\10_Shizuku"
                                 image_count: 20
                                 num_repeats: 10
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: None
                                 caption_extension: .txt


                    INFO     [Dataset 0]                                                              config_util.py:550
                    INFO     loading image sizes.                                                      train_util.py:794
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 168.78it/s]
                    INFO     prepare dataset                                                           train_util.py:802
                    INFO     preparing accelerator                                                  train_network.py:226
accelerator device: cuda
                    INFO     loading model for process 0/1                                            train_util.py:4111
                    INFO     load StableDiffusion checkpoint: C:\\Users\\yutam\\model.ckpt            train_util.py:4066
2024-03-31 18:18:48 INFO     UNet2DConditionModel: 64, 8, 768, False, False                        original_unet.py:1387
2024-03-31 18:18:52 INFO     loading u-net: <All keys matched successfully>                           model_util.py:1009
2024-03-31 18:18:53 INFO     loading vae: <All keys matched successfully>                             model_util.py:1017
2024-03-31 18:18:54 INFO     loading text encoder: <All keys matched successfully>                    model_util.py:1074
2024-03-31 18:18:55 INFO     Enable xformers for U-Net                                                train_util.py:2529
import network module: networks.lora
                    INFO     [Dataset 0]                                                              train_util.py:1948
                    INFO     caching latents.                                                          train_util.py:915
                    INFO     checking cache validity...                                                train_util.py:925
100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]
                    INFO     caching latents...                                                        train_util.py:962
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.61it/s]
2024-03-31 18:19:00 INFO     create LoRA network. base dim (rank): 4, alpha: 1                               lora.py:811
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout: p=None            lora.py:812
                    INFO     create LoRA for Text Encoder:                                                   lora.py:906
                    INFO     create LoRA for Text Encoder: 72 modules.                                       lora.py:911
                    INFO     create LoRA for U-Net: 192 modules.                                             lora.py:919
                    INFO     enable LoRA for text encoder                                                    lora.py:962
                    INFO     enable LoRA for U-Net                                                           lora.py:967
                    INFO     CrossAttnDownBlock2D False -> True                                    original_unet.py:1521
                    INFO     CrossAttnDownBlock2D False -> True                                    original_unet.py:1521
                    INFO     CrossAttnDownBlock2D False -> True                                    original_unet.py:1521
                    INFO     DownBlock2D False -> True                                             original_unet.py:1521
                    INFO     UNetMidBlock2DCrossAttn False -> True                                 original_unet.py:1521
                    INFO     UpBlock2D False -> True                                               original_unet.py:1521
                    INFO     CrossAttnUpBlock2D False -> True                                      original_unet.py:1521
                    INFO     CrossAttnUpBlock2D False -> True                                      original_unet.py:1521
                    INFO     CrossAttnUpBlock2D False -> True                                      original_unet.py:1521
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\sd-scripts\sd-scripts\library\train_util.py", line 3616, in get_optimizer
    import bitsandbytes as bnb
ModuleNotFoundError: No module named 'bitsandbytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\sd-scripts\sd-scripts\train_network.py", line 1058, in <module>
    trainer.train(args)
  File "C:\sd-scripts\sd-scripts\train_network.py", line 349, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\sd-scripts\sd-scripts\library\train_util.py", line 3618, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yutam\scoop\apps\python310\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\sd-scripts\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:\\\\Users\\\\yutam\\\\model.ckpt', '--dataset_config=C:\\\\SDXL-Traning\\\\dataset.toml', '--output_dir=.\\outputs', '--output_name=rolaoutput', '--save_model_as=safetensors', '--prior_loss_weight=1.0', '--max_train_steps=400', '--learning_rate=1e-4', '--optimizer_type=AdamW8bit', '--xformers', '--mixed_precision=fp16', '--cache_latents', '--gradient_checkpointing', '--save_every_n_epochs=10', '--resolution=512,512', '--network_module=networks.lora']' returned non-zero exit status 1.

**Comment by tenro11** [comment]
過去の質問で同じような件があったので参考にしてみたところ、正常に動作しLoRAが生成されました。
問題の解決までお付き合いいただき、ありがとうございました。
二日前に突然SDXL以外のSD系列が全て起動しなくなってしまったので、本当に助かりました。

**Comment by tenro11** [comment]
本当にありがとうございました。
今度はSDXLのLoRA作りも挑戦してみます。
