### ISSUE TITLE
Log tracker config: how-to?

### ISSUE THREAD

**Issue by rafstahelin** [kohya-ss/sd-scripts#1256]
I am trying to send my parameter config to wandb.

I've added a diretory for Log tracker config, but I now get this error message which mentions a toml:
running training / 学習開始 num examples / サンプル数: 5 num batches per epoch / 1epochのバッチ数: 5 num epochs / epoch数: 2 batch size per device / バッチサイズ: 1 gradient accumulation steps / 勾配を合計するステップ数 = 1 total optimization steps / 学習ステップ数: 10 steps: 0%| | 0/10 [00:00<?, ?it/s]Traceback (most recent call last): File "E:\kohya_ss\sd-scripts\sdxl_train.py", line 818, in <module> train(args) File "E:\kohya_ss\sd-scripts\sdxl_train.py", line 489, in train init_kwargs = toml.load(args.log_tracker_config) File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 133, in load with io.open(_getpath(f), encoding='utf-8') as ffile: PermissionError: [Errno 13] Permission denied: 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\3training\\1_local_training_gr4ph1cw\\tracker' Traceback (most recent call last): File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module> File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main args.func(args) File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command simple_launcher(args) File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

What is this error?

Do i need to create a toml file in "Dataset config file"

I am Kohya 23.1.3, Windows
I am able to run training without the tracker config setting

**Comment by rafstahelin** [comment]
> The tracker config file seems to be opened by another process, or it is the folder not the file. Please see #630 for the detail of `.toml` file.

But i actually want all my training parameters in like LR, Optimiser, batch size, that goes into accelerate, to automatically be sent to wandb. I dont want to write it manually like in #630

**Comment by rafstahelin** [comment]
@kohya-ss 

I just reread Issue [#1123](https://github.com/bmaltais/kohya_ss/issues/1123)

But is there no way to make a function to pass training parameters without the issue of exposing the wandb api token? It seems such a loss of information of the trianing not to have the parameters in wandb. I know a lot of people who use kohya with wandb. It is very difficult to keep track of parameter experiments without the whole picture. 

thanks
