### ISSUE TITLE
Error running extract_lora_from_models.py

### ISSUE THREAD

**Issue by magpie514** [kohya-ss/sd-scripts#126]
Good day.
I ran into a strange issue running extract_lora_from_models.py, it seems to be unable to calculate the safetensors hashes:
```
calculating by svd
100%|█████████████████████████████████████████████████| 264/264 [00:44<00:00,  5.94it/s]
enable LoRA for text encoder
enable LoRA for U-Net
LoRA has 792 weights.
Loading extracted LoRA weights: <All keys matched successfully>
Traceback (most recent call last):
  File "/mnt/DATA/AI/sd-scripts/networks/extract_lora_from_models.py", line 164, in <module>
    svd(args)
  File "/mnt/DATA/AI/sd-scripts/networks/extract_lora_from_models.py", line 144, in svd
    lora_network_o.save_weights(args.save_to, save_dtype, metadata)
  File "/mnt/DATA/AI/sd-scripts/networks/lora.py", line 231, in save_weights
    model_hash, legacy_hash = train_util.precalculate_safetensors_hashes(state_dict, metadata)
AttributeError: module 'library.train_util' has no attribute 'precalculate_safetensors_hashes'
```

This **works when saving as ckpt**, but safetensors fails for some reason. I've verified library.train_util.precalculate_safetensors_hashes exists from a python console:
```python
>>> train_util.precalculate_safetensors_hashes
<function precalculate_safetensors_hashes at 0x7f7a14a24700>
```
so I don't know why it fails, everything looks fine.
It worked with a safetensors output on January 18th.

**Comment by magpie514** [comment]
That fixed it, thank you very much!
I am not sure what could have caused it, this local clone is the same I do training into without errors, and I did successfully output to safetensors with this script before.
Regardless, it is fixed so if it happens again I know what to do. Thanks a lot! I'll close the issue now.
