### ISSUE TITLE
When adaptive_noise_scale = 0 is given still tries to verify noise_offset

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#1275]
Is this supposed to happen? toml file as below and error is as below @kohya-ss 

**what are the default values for SDXL and SD 1.5?**

```
r factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/kaggle/working/kohya_ss/sd-scripts/sdxl_train.py", line 818, in <module>
    train(args)
  File "/kaggle/working/kohya_ss/sd-scripts/sdxl_train.py", line 100, in train
    train_util.verify_training_args(args)
  File "/kaggle/working/kohya_ss/sd-scripts/library/train_util.py", line 3473, in verify_training_args
    raise ValueError("adaptive_noise_scale requires noise_offset / adaptive_noise_scaleを使用するにはnoise_offsetが必要です")
ValueError: adaptive_noise_scale requires noise_offset / adaptive_noise_scaleを使用するにはnoise_offsetが必要です
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '/kaggle/working/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', './outputs/tmpfiledbooth.toml', '--max_grad_norm=0.0', '--no_half_vae', '--train_text_encoder', '--ddp_timeout=10000000', '--ddp_gradient_as_bucket_view']' returned non-zero exit status 1.
```

```
adaptive_noise_scale = 0
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
clip_skip = 1
dynamo_backend = "no"
epoch = 1
full_fp16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 1e-5
learning_rate_te1 = 3e-6
learning_rate_te2 = 0
logging_dir = "/kaggle/working/results/log"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 1125
mem_eff_attn = true
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0
noise_offset_type = "Original"
optimizer_type = "Adafactor"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
output_dir = "/kaggle/working/results/model"
output_name = "Kaggle_SDXL_Base_DreamBooth"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/kaggle/working/results/model/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_every_n_steps = 1300
save_model_as = "safetensors"
save_precision = "fp16"
train_batch_size = 2
train_data_dir = "/kaggle/working/results/img"
vae = "stabilityai/sdxl-vae"
vae_batch_size = 4
xformers = true
```

**Comment by FurkanGozukara** [comment]
> if `adaptive_scale` is not used, it is needed to set to `None`. The default value is `None`.

thanks it was @bmaltais new UI mistake and i think he gonna fix it
