### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by eratel** [kohya-ss/sd-scripts#1354]
Traceback (most recent call last):
  File "/Users/kleinsun/open/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/kleinsun/open/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Users/kleinsun/open/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/Users/kleinsun/open/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/kleinsun/open/kohya_ss/venv/bin/python', '/Users/kleinsun/Documents/open/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', '/Users/kleinsun/Documents/open/kohya_ss/outputs/config_dreambooth-20240531-163416.toml']' returned non-zero exit status 1.

**Comment by TTTTong777** [comment]
Hello, I've been bothering. It's been a long time since I encountered this problem. After running for more than an hour, I reported 
just:
steps:  18%|█▊        | 337/1920 [1:37:28<7:37:50, 17.35s/it, avr_loss=0.206]
Traceback (most recent call last):
  File "/home/lctools/miniconda3/envs/lora-flux/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lctools/miniconda3/envs/lora-flux/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/lctools/miniconda3/envs/lora-flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/home/lctools/miniconda3/envs/lora-flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lctools/miniconda3/envs/lora-flux/bin/python', 'flux_train_network.py', '--pretrained_model_name_or_path', 'data/models/unet/flux1-dev-fp8.safetensors', '--ae', 'data/models/vae/ae.safetensors', '--clip_l', 'data/models/clip/clip_l.safetensors', '--t5xxl', 'data/models/clip/t5xxl_fp16.safetensors', '--output_dir', 'output/flux_kuluomi/flux_kuluomi_24_1', '--dataset_config', 'config/config_kuluomi_zhengze.toml', '--max_train_epochs=20', '--learning_rate=1e-4', '--output_name=flux_kuluomi_24_1', '--save_every_n_epochs=1', '--save_precision=bf16', '--seed=42', '--max_token_length=225', '--caption_extension=.txt', '--vae_batch_size=4', '--apply_t5_attn_mask', '--discrete_flow_shift=3.185', '--timestep_sampling=flux_shift', '--sigmoid_scale=1', '--model_prediction_type=raw', '--cache_text_encoder_outputs_to_disk', '--sdpa', '--train_batch_size=2', '--resolution=1024,1024', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--bucket_no_upscale', '--save_model_as=safetensors', '--clip_skip=2', '--network_dim=32', '--network_alpha=32', '--persistent_data_loader_workers', '--cache_latents', '--cache_latents_to_disk', '--gradient_checkpointing', '--optimizer_type=PagedAdamW8bit', '--optimizer_args', 'weight_decay=0.01', 'betas=0.9,0.95', '--unet_lr=2e-4', '--text_encoder_lr=1e-5', '--keep_tokens=1', '--fp8_base_unet', '--mixed_precision=bf16', '--network_module=networks.lora_flux', '--gradient_accumulation_steps=1', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=2', '--lr_warmup_steps=192', '--sample_every_n_epochs=1', '--sample_prompts', 'data/prompts/prompts_kuluomi.txt']' returned non-zero exit status 1.
