### ISSUE TITLE
Runtime Error: CUDA out of memory

### ISSUE THREAD

**Issue by Desuka-art** [kohya-ss/sd-scripts#138]
I got really close to training a model, but then it hit me with the error above, what do I do?

**Comment by GucciFlipFlops1917** [comment]
Can you post the full error prompt as well as your GPU and available RAM?

**Comment by Desuka-art** [comment]
`Traceback (most recent call last):
  File "C:\Users\phill\sd-scripts\train_network.py", line 538, in <module>
    train(args)
  File "C:\Users\phill\sd-scripts\train_network.py", line 380, in train
    for step, batch in enumerate(train_dataloader):
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\phill\sd-scripts\library\train_util.py", line 444, in __getitem__
    image = self.image_transforms(img)      # -1.0~1.0のtorch.Tensorになる
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torchvision\transforms\transforms.py", line 94, in __call__
    img = t(img)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torchvision\transforms\transforms.py", line 134, in __call__
    return F.to_tensor(pic)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\torchvision\transforms\functional.py", line 153, in to_tensor
    return img.to(dtype=default_float_dtype).div(255)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 3145728 bytes.

steps:   8%|████▊                                                       | 203/2500 [03:46<42:44,  1.12s/it, loss=0.139]
Traceback (most recent call last):
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\phill\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\phill\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\phill\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--network_module=networks.lora', '--pretrained_model_name_or_path=D:\\SD\\stable-diffusion-webui\\models\\Stable-diffusion\\nai.ckpt', '--train_data_dir=C:\\Users\\phill\\sd-scripts\\training_images_folder\\images_dir', '--reg_data_dir=C:\\Users\\phill\\sd-scripts\\training_images_folder\\reg_dir', '--output_dir=D:\\LoRA Outputs', '--caption_extension=.txt', '--shuffle_caption', '--prior_loss_weight=1', '--resolution=512', '--train_batch_size=1', '--learning_rate=0.0001', '--max_train_steps=2500', '--mixed_precision=fp16', '--save_precision=fp16', '--use_8bit_adam', '--xformers', '--save_every_n_epochs=2', '--text_encoder_lr=5E-05', '--save_model_as=safetensors', '--clip_skip=2', '--seed=23', '--network_alpha=128', '--network_dim=128', '--color_aug', '--flip_aug', '--max_token_length=150', '--lr_scheduler=cosine_with_restarts', '--vae=D:\\SD\\stable-diffusion-webui\\models\\Stable-diffusion\\nai.vae.pt']' returned non-zero exit status 1.`

GPU: 3090

RAM: 16 GB

VRAM: 24 GB

**Comment by GucciFlipFlops1917** [comment]
Ruling out simpler options of restarting to clear system cache or making sure you're not using something memory-intensive in the background, perhaps it's a thing of the size of your paging file? Setting it to system managed is ideal for reducing strain at the cost of storage space.

In addition, be sure you've specified CPU threads to 16 and check your num_workers input. I believe you're running at the default of 8, which should theoretically work, but decreasing it may be useful to leverage your GPU (to the best of my knowledge).

That being said, the rest of your inputs looks perfectly fine and should run with ease. Given you even got through 203 steps, the issue could also unfortunately be a memory leak.

**Comment by Desuka-art** [comment]
Where is the num_workers thing? I’m using a custom power shell file to start the training.

**Comment by GucciFlipFlops1917** [comment]
My apology, the specific option is "--max_data_loader_n_workers" in train_util.py. if you add the line in the powershell script or adjust the default value in the python file, it should adjust accordingly.
