### ISSUE TITLE
SD3 Training problem

### ISSUE THREAD

**Issue by leonary** [kohya-ss/sd-scripts#1382]
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 34435.99it/s]
                    INFO     make buckets                                                                                               train_util.py:876
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                            train_util.py:922
                    INFO     bucket 0: resolution (896, 1152), count: 750                                                               train_util.py:927
                    INFO     mean ar error (without repeats): 0.04527777777777775                                                       train_util.py:932
                    INFO     prepare accelerator                                                                                         sd3_train.py:156
                    WARNING  Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to   other.py:349
                             hang. It is recommended to upgrade the kernel to the minimum version or higher.                                             
accelerator device: cuda
                    INFO     loading model for process 0/1                                                                          sd3_train_utils.py:42
                    INFO     Loading SD3 models from /root/autodl-tmp/SD3.safetensors...                                                  sd3_utils.py:47
                    INFO     clip_l is included in the checkpoint                                                                         sd3_utils.py:60
                    INFO     clip_g is included in the checkpoint                                                                         sd3_utils.py:77
                    INFO     t5xxl is included in the checkpoint                                                                          sd3_utils.py:94
                    INFO     Building MMDit                                                                                              sd3_utils.py:122
                    INFO     Loading state dict...                                                                                       sd3_utils.py:126
2024-06-24 13:05:27 INFO     Loaded MMDiT: <All keys matched successfully>                                                               sd3_utils.py:128
                    INFO     Building ClipL                                                                                              sd3_utils.py:134
2024-06-24 13:05:28 INFO     Loading state dict...                                                                                       sd3_utils.py:136
                    INFO     Loaded ClipL: <All keys matched successfully>                                                               sd3_utils.py:138
                    INFO     Building ClipG                                                                                              sd3_utils.py:144
2024-06-24 13:05:35 INFO     Loading state dict...                                                                                       sd3_utils.py:146
                    INFO     Loaded ClipG: <All keys matched successfully>                                                               sd3_utils.py:148
                    INFO     Building T5XXL                                                                                              sd3_utils.py:155
                    INFO     Loading state dict...                                                                                       sd3_utils.py:157
2024-06-24 13:05:41 INFO     Loaded T5XXL: <All keys matched successfully>                                                               sd3_utils.py:159
                    INFO     Building VAE                                                                                                sd3_utils.py:163
                    INFO     Loading state dict...                                                                                       sd3_utils.py:165
                    INFO     Loaded VAE: <All keys matched successfully>                                                                 sd3_utils.py:167
2024-06-24 13:05:42 INFO     [Dataset 0]                                                                                               train_util.py:2201
                    INFO     caching latents.                                                                                           train_util.py:991
                    INFO     checking cache validity...                                                                                train_util.py:1001
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1211.74it/s]
                    INFO     caching latents...                                                                                        train_util.py:1040
0it [00:00, ?it/s]
                    INFO     [Dataset 0]                                                                                               train_util.py:2215
                    INFO     caching text encoder outputs.                                                                             train_util.py:1083
                    INFO     checking cache existence...                                                                               train_util.py:1086
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 52692.26it/s]
2024-06-24 13:05:43 INFO     caching text encoder outputs...                                                                           train_util.py:1133
  **0%|                                                                                                                              | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/sd-scripts/sd3_train.py", line 907, in <module>
    train(args)
  File "/root/autodl-tmp/sd-scripts/sd3_train.py", line 249, in train
    train_dataset_group.cache_text_encoder_outputs_sd3(
  File "/root/autodl-tmp/sd-scripts/library/train_util.py", line 2216, in cache_text_encoder_outputs_sd3
    dataset.cache_text_encoder_outputs_sd3(
  File "/root/autodl-tmp/sd-scripts/library/train_util.py", line 1059, in cache_text_encoder_outputs_sd3
    return self.cache_text_encoder_outputs_common(
  File "/root/autodl-tmp/sd-scripts/library/train_util.py", line 1151, in cache_text_encoder_outputs_common
    cache_batch_text_encoder_outputs_sd3(
  File "/root/autodl-tmp/sd-scripts/library/train_util.py", line 2661, in cache_batch_text_encoder_outputs_sd3
    b_lg_out, b_t5_out, b_pool = sd3_utils.get_cond_from_tokens(
  File "/root/autodl-tmp/sd-scripts/library/sd3_utils.py", line 199, in get_cond_from_tokens
    l_out, l_pooled = clip_l.encode_token_weights(l_tokens)
  File "/root/autodl-tmp/sd-scripts/library/sd3_models.py", line 1453, in encode_token_weights
    out, pooled = self(list_of_tokens)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/sd-scripts/library/sd3_models.py", line 1519, in forward
    outputs = self.transformer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/sd-scripts/library/sd3_models.py", line 1424, in forward
    x = self.text_model(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/sd-scripts/library/sd3_models.py", line 1388, in forward
    x = self.embeddings(input_tokens)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/sd-scripts/library/sd3_models.py", line 1372, in forward
    return self.token_embedding(input_tokens) + self.position_embedding.weight
RuntimeError: The size of tensor a (110) must match the size of tensor b (77) at non-singleton dimension 1**
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '/root/autodl-tmp/sd-scripts/sd3_train.py', '--bucket_reso_steps=64', '--caption_extension=.txt', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--huber_c=0.1', '--huber_schedule=snr', '--learning_rate=0.00012', '--loss_type=l2', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_train_steps=300', '--min_timestep=0', '--mixed_precision=no', '--optimizer_type=AdamW8bit', '--output_name=last', '--pretrained_model_name_or_path=/root/autodl-tmp/SD3.safetensors', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=float', '--train_batch_size=1', '--train_data_dir=/root/autodl-tmp/181/188', '--sdpa', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--cache_latents', '--cache_latents_to_disk']' returned non-zero exit status 1.
```

It looks like cache_text_encoder_outputs_to_disk causes an error.

**Comment by leonary** [comment]
I can now start training, thank you very much!

**Comment by zengjie617789** [comment]
@leonary  how you run successfully when the text_encoder is not passed but it needed?
line64:
>    assert (
        not args.train_text_encoder or not args.cache_text_encoder_outputs
    ), "cache_text_encoder_outputs is not supported when training text encoder / text encoderを学習するときはcache_text_encoder_outputsはサポートされていません"
