### ISSUE TITLE
KeyError: 'time_embed.0.weight while Training on SD3.

### ISSUE THREAD

**Issue by SatyamSSJ10** [kohya-ss/sd-scripts#1414]
`Traceback (most recent call last):
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\train_network.py", line 1242, in <module>
    trainer.train(args)
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\train_network.py", line 234, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\train_network.py", line 101, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\library\train_util.py", line 4655, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\library\train_util.py", line 4610, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\library\model_util.py", line 1005, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "F:\AI\sd-scripts-sd3\sd-scripts-sd3\library\model_util.py", line 267, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'`

using sd3_medium_incl_clips.safetensors

**Comment by SatyamSSJ10** [comment]
using sd3_medium and other variations
