### ISSUE TITLE
Support FLUX series models

### ISSUE THREAD

**Issue by ddpasa** [kohya-ss/sd-scripts#1445]
These models have just been released and appear to be amazing.  Links below:

Blog from fal.ai: https://blog.fal.ai/flux-the-largest-open-sourced-text2img-model-now-available-on-fal/

Huggingface: https://huggingface.co/black-forest-labs

There is a schell version and dev version.

**Comment by 3blackbar** [comment]
When you prune it in comfy it takes up 11GB, so it should be doable to train lora at 640x640 on 3090?

**Comment by LazyCat420** [comment]
is it possible to finetune the model on a 3090 or do we have to do a lora due to the size?

**Comment by leonary** [comment]
I totally agree. Since SD3 may not be able to fit a slightly larger dataset due to model problems (scripts include SimpleTuner, SD-scripts, OneTrainer), it is recommended to stop developing SD3 training scripts. I did a simple test on Flux-dev, and its capabilities are completely superior to SD3. Here are some examples:
![zyi7Khvc7wnYcFh64fENU](https://github.com/user-attachments/assets/a4c6adce-ba8c-4c68-a661-67153dcd7f4b)
![DFVgNwtZxrLxJGkulrcN0](https://github.com/user-attachments/assets/b073d41a-030a-4a72-85a9-12f5ea6823c4)
![8ihTzsxMXqggjHJyC-N8k](https://github.com/user-attachments/assets/04030178-9bfe-482e-883a-f3e51587c9f6)
![fWPcyz5JIePCHseGBZqLj](https://github.com/user-attachments/assets/7184fa6a-c6ce-4b25-8396-ecdd3fc87b43)
It’s worth pointing out that this is the first model I’ve seen that can correctly draw the position of the umbrella handle and the umbrella cover, and the text prompt on the road sign is “iiilllllbddbwW”. Although the AI ​​didn’t draw it correctly, I haven’t seen any model that can draw it correctly either.

**Comment by dill-shower** [comment]
> I totally agree. Since SD3 may not be able to fit a slightly larger dataset due to model problems (scripts include SimpleTuner, SD-scripts, OneTrainer), it is recommended to stop developing SD3 training scripts. I did a simple test on Flux-dev, and its capabilities are completely superior to SD3. Here are some examples:


I strongly disagree. While the SD3 Medium model has certain drawbacks, it possesses a crucial advantage that FLUX lacks: its weights are publicly available. In contrast, FLUX only provides access to the base model's weights through an API, with no indication or information suggesting they plan to make it open-source. The models that are publicly accessible are derived through distillation of the base model; they are truncated, incomplete, and practically unsuitable for further training. It only makes sense to train the model we weren't given, as fine-tuning the distilled models would require roughly the same effort as training from scratch, if not more. Even the SDXL model was superior in this regard

**Comment by ResidentChief** [comment]
> > I totally agree. Since SD3 may not be able to fit a slightly larger dataset due to model problems (scripts include SimpleTuner, SD-scripts, OneTrainer), it is recommended to stop developing SD3 training scripts. I did a simple test on Flux-dev, and its capabilities are completely superior to SD3. Here are some examples:
> 
> I strongly disagree. While the SD3 Medium model has certain drawbacks, it possesses a crucial advantage that FLUX lacks: its weights are publicly available. In contrast, FLUX only provides access to the base model's weights through an API, with no indication or information suggesting they plan to make it open-source. The models that are publicly accessible are derived through distillation of the base model; they are truncated, incomplete, and practically unsuitable for further training. It only makes sense to train the model we weren't given, as fine-tuning the distilled models would require roughly the same effort as training from scratch, if not more. Even the SDXL model was superior in this regard.
> 
> Calling it open-source is akin to labeling GPT-4o as open-source simply because we were given GPT-3 weights and the ability to fine-tune it. I'm concerned that we'll be wasting time that could be better spent studying SD3, debugging and optimizing its training script. SD3 has more potential, and Stability AI has promised to eventually release all models, including their weights, as open-source. This makes SD3 a more promising avenue for our efforts

You do realise the schnell and dev model weights are freely available, and the schnell one is even under the apache licence....

**Comment by dill-shower** [comment]
> Hello, the weights for the Flux series models have been released, including the dev version and the schnell version.

Please read this https://blog.fal.ai/flux-the-largest-open-sourced-text2img-model-now-available-on-fal/
Dev and schnell are obtained by distillation of pro scales. It is possible to create LoRAs for them, they will work. But full model training is practically impossible because of this

**Comment by ddpasa** [comment]
> > Hello, the weights for the Flux series models have been released, including the dev version and the schnell version.
> 
> Please read this https://blog.fal.ai/flux-the-largest-open-sourced-text2img-model-now-available-on-fal/ Dev and schnell are obtained by distillation of pro scales. It is possible to create LoRAs for them, they will work. But full model training is practically impossible because of this

It should be possible to fine-tune distilled models.

**Comment by dill-shower** [comment]
> It should be possible to fine-tune distilled models.

Why should it? I just did a quick search for information about training SDXL Turbo, and it turns out it was also obtained through distillation from the base model. There are tons of such models on Civitai, but they're all created by merging SDXL Turbo with something else. I couldn't find a single one obtained through fine-tuning. As I expected. https://www.reddit.com/r/StableDiffusion/comments/18l2qp0/sdxl_turbo_fine_tunemerging/

**Comment by ddpasa** [comment]
> > It should be possible to fine-tune distilled models.
> 
> Why should it? I just did a quick search for information about training SDXL Turbo, and it turns out it was also obtained through distillation from the base model. There are tons of such models on Civitai, but they're all created by merging SDXL Turbo with something else. I couldn't find a single one obtained through fine-tuning.The only relevant post I came across was a complaint on Reddit about how training SDXL Turbo produces very poor results. As I expected. https://www.reddit.com/r/StableDiffusion/comments/18l2qp0/sdxl_turbo_fine_tunemerging/

That is because the training code for Turbo was never released and nobody wrote one.  It's not fundamentally impossible.

**Comment by bghira** [comment]
even training schnell with lora or full tune is fine. they're just big models and require the use of LoRA with quantised base weights, but Kohya should probably wait for the bugs to be worked out in Quanto first before going ahead and trying to integrate it. it makes a mess of the model state dict keys.

**Comment by BenDes21** [comment]
@kohya-ss Training scripts released : https://github.com/XLabs-AI/x-flux

**Comment by bghira** [comment]
those are pretty minimal and eg. it doesn't implement cosmap/logit-norm or any of the SD3 training details, just about the same as cloneofsimo/minRF implementation. in fact it's basically identical - the interesting thing there is probably their ControlNet training implementation details

**Comment by ddpasa** [comment]
> diffusers scripts arrived
> 
> https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_flux.md

@FurkanGozukara , you are amazing as usual!

**Comment by FurkanGozukara** [comment]
@ddpasa thanks

pull request arrived already :d 

https://github.com/kohya-ss/sd-scripts/pull/1374/files/da4d0fe0165b3e0143c237de8cf307d53a9de45a..36b2e6fc288c57f496a061e4d638f5641c32c9ea

**Comment by cyan2k** [comment]
> > It should be possible to fine-tune distilled models.
> 
> Why should it? I just did a quick search for information about training SDXL Turbo, and it turns out it was also obtained through distillation from the base model. There are tons of such models on Civitai, but they're all created by merging SDXL Turbo with something else. I couldn't find a single one obtained through fine-tuning.The only relevant post I came across was a complaint on Reddit about how training SDXL Turbo produces very poor results. As I expected. https://www.reddit.com/r/StableDiffusion/comments/18l2qp0/sdxl_turbo_fine_tunemerging/

Do you guys also love it when someone is so confidently incorrect?

My flux finetune is coming in very nicely. Huge upgrade compared to SDXL and Pony, also way more trainable than SD3 Medium. It's literally impossible to add NSFW to SD3 medium because of the complete lack of training data.

Flux seem to seen plenty of NSFW images, and it's just filtered via captioning. So the context and knowledge already exists in the latent space, and it only needs to.. well get finetuned.

So, yeah fuck SD3. Pyro's NSFW model <3 FLUX

**Comment by protector131090** [comment]
> > > It should be possible to fine-tune distilled models.
> > 
> > 
> > Why should it? I just did a quick search for information about training SDXL Turbo, and it turns out it was also obtained through distillation from the base model. There are tons of such models on Civitai, but they're all created by merging SDXL Turbo with something else. I couldn't find a single one obtained through fine-tuning.The only relevant post I came across was a complaint on Reddit about how training SDXL Turbo produces very poor results. As I expected. https://www.reddit.com/r/StableDiffusion/comments/18l2qp0/sdxl_turbo_fine_tunemerging/
> 
> Do you guys also love it when someone is so confidently incorrect?
> 
> My flux finetune is coming in very nicely. Huge upgrade compared to SDXL and Pony, also way more trainable than SD3 Medium. It's literally impossible to add NSFW to SD3 medium because of the complete lack of NSFW content in its training data. No finetuner is going to finish SAI's pathetic job. Nobody is ever going to create any kind of content for SD3 when you can create better results for the same money with flux. so yeah, rip.
> 
> Flux seems to have seen plenty of NSFW images, and it's just filtered and dropped out via captioning. So the context and knowledge already exists in the latent space, and it only needs to... well get finetuned.
> 
> So, yeah f*ck SD3. Pyro's NSFW model goes FLUX.

what are you talking about? i trained 3.0 for 30 minutes and it can generate nsfw just fine. **NSFW** link https://imgur.com/a/sd-30-test-G7G7G6u

**Comment by dill-shower** [comment]
> > > > It should be possible to fine-tune distilled models.
> > > 
> > > 
> > > Why should it? I just did a quick search for information about training SDXL Turbo, and it turns out it was also obtained through distillation from the base model. There are tons of such models on Civitai, but they're all created by merging SDXL Turbo with something else. I couldn't find a single one obtained through fine-tuning.The only relevant post I came across was a complaint on Reddit about how training SDXL Turbo produces very poor results. As I expected. https://www.reddit.com/r/StableDiffusion/comments/18l2qp0/sdxl_turbo_fine_tunemerging/
> > 
> > 
> > Do you guys also love it when someone is so confidently incorrect?
> > My flux finetune is coming in very nicely. Huge upgrade compared to SDXL and Pony, also way more trainable than SD3 Medium. It's literally impossible to add NSFW to SD3 medium because of the complete lack of NSFW content in its training data. No finetuner is going to finish SAI's pathetic job. Nobody is ever going to create any kind of content for SD3 when you can create better results for the same money with flux. so yeah, rip.
> > Flux seems to have seen plenty of NSFW images, and it's just filtered and dropped out via captioning. So the context and knowledge already exists in the latent space, and it only needs to... well get finetuned.
> > So, yeah f*ck SD3. Pyro's NSFW model goes FLUX.
> 
> what are you talking about? i trained 3.0 for 30 minutes and it can generate nsfw just fine. **NSFW** link https://imgur.com/a/sd-30-test-G7G7G6u

Someone just reads too much reddit and similar places where everyone is convinced that if a model wasn't trained on nsfw then they will never be able to create such things. How they used to create models for anime, furry and the rest for sdxl no one knows. Lost technology

In all seriousness, there's nothing stopping sd3 from learning to create any nsfw content and even worse. Due to the more efficient architecture, training does not require as much GPU overhead as sdxl.

I don't understand why everyone is so crazy with this FLUX and minus my comment that it has no scales and access only by api

**Comment by cyan2k** [comment]
>Someone just reads too much reddit and similar places where everyone is convinced that if a model wasn't trained on nsfw then they will never be able to create such things.

We (group of SDXL finetuners) spend like 5k bucks making NSFW in SD3 work, but a model that can't even render women lying in grass is so lobotomized that re-introducing NSFW takes immense ressources, as in the ballpark of SAI's training infrastructure. No hobby finetuner is going to pay for that. Nobody is going to pay for that, if they can get way better results for a fraction of the cost with FLUX.

It's not hard to understand. It took 20 bucks to teach FLUX NSFW concepts.... 5k$ vs 20$ pretty clear cut.

>How they used to create models for anime, furry and the rest for sdxl no one knows. Lost technology

Well it seems that you don't know the basic of how training such models work and how self-organisation of embeddings in the latent space works. LAION, the data corpus of SDXL, is full of furry and anime shit. SD3 data corpus has exactly 0 NSFW images in it. And you honestly have difficulties to understand why one is trainable and the later isn't? You're on the wrong board then.

Please stop talking about things you don't have a clue about.

Also FLUX is runnable locally and the weights are public, so I don't even know what " it has no scales and access only by api" even means.

**Comment by dill-shower** [comment]
> We (group of SDXL finetuners) spend like 5k bucks making NSFW in SD3 work, but a model that can't even render women lying in grass is so lobotomized

Stabilityai promised to release the 3.1 model soon. They promised to fix this problem in it. You've been too quick to educate yourself



> Well it seems that you don't know the basic of how training such models work and how self-organisation of embeddings in the latent space works. LAION, the data corpus of SDXL, is full of furry and anime shit

When sdxl came out it was written about on reddit the same thing they are now writing about sd3. That it didn't use NSFW content in training so nsfw training is impossible, "it's a terrible model, stabilityai killed their reputation by refusing to train on nsfw content, we can't use it, we stay on sd1.5".... Just like they wrote about sd2.... Let's wait a year and find out that there was nsfw in the sd3 dataset but it was removed from the sd4 dataset so we stay on sd3 and boycott the new model....

**Comment by D3voz** [comment]
People are using simple tuner for flux lora creation. Unfortunately it has no windows support. Waiting for kohya ss :) . Flux dev is so much better than sd3 💯

**Comment by leonary** [comment]
> Stabilityai promised to release the 3.1 model soon. They promised to fix this problem in it. You've been too quick to educate yourself

If sd3.1 can have the performance of flux dev and allow training and sharing, and the machine cost of fine-tuning is smaller than flux dev, then I will be very happy to use sd3.1. But as far as sd3 8b and the license of sd3 are concerned, I am pessimistic about this possibility.

**Comment by leonary** [comment]
> Now sd3 branch supports FLUX.1 dev LoRA training experimentally :) https://github.com/kohya-ss/sd-scripts/tree/sd3

Thank you for your excellent work. The fine-tuning effect of sd-scripts with Flux has completely met my expectations, and its performance is on par with Simple Tuner.

Additionally, is there any plan to support Flux in some of the LoRA processing scripts? These scripts could help the community more quickly develop models like "detail enhancer."

**Comment by Tophness** [comment]
> > People are using simple tuner for flux lora creation. Unfortunately it has no windows support. Waiting for kohya ss :) . Flux dev is so much better than sd3 💯
> 
> Now sd3 branch supports FLUX.1 dev LoRA training experimentally :) https://github.com/kohya-ss/sd-scripts/tree/sd3

Will this work for the much more efficient NF4 model that was released yesterday?
Up to 4x speedups, reduced vram, increased quality. Hopefully more accessible to people without a spare A100 lying around.

https://civitai.com/models/638572/nf4-flux1
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

**Comment by bghira** [comment]
you don't need an A100 for flux. imo kohya should release sooner than keep trying to add the million features. you can train on 16G VRAM without any quantisation at all.

**Comment by Tophness** [comment]
> you don't need an A100 for flux. imo kohya should release sooner than keep trying to add the million features. you can train on 16G VRAM without any quantisation at all.

It did in the other training setups I'd seen but yeah apparently not anymore. The NF4 model is far superior though and more accessible for inference.
FP8 used to be virtually unusable on my 4080 because it'd take about 5-10 mins for 1 overquantized generation, and now it's about 20 sec for outputs that look on par with Pro.
Don't really wanna waste a week training an FP8 model that's already obsolete and can't be used be most people.

**Comment by bghira** [comment]
it's not like that at all though. fp8 is fine, especially in pytorch 2.4. you can read back through the comments in this issue to see.

**Comment by bghira** [comment]
also, NF4 is definitely not "on par with Pro" 🤪

**Comment by Tophness** [comment]
In addition to the links above citing the same thing I did, prominent youtubers testing it are saying the same thing.
"the regular flux Dev takes about 50 seconds to run on my machine on a RTX 4090, this takes 14 seconds to run"
https://www.youtube.com/watch?v=L5BjuPgF1Ds

**Comment by cyan2k** [comment]
just as a quickie and teaser for all people on the fence shelling out for 4090 or an online GPU and doubters of FLUX's capabilities.

my pre-release ATJ lora - will get published on civitai in a couple of hours


![ComfyUI_00408_](https://github.com/user-attachments/assets/fbd1afeb-9842-4fa7-bbbb-17f07a74c96b)

It's like on a completely different level than SD3

**Comment by cyan2k** [comment]
@bghira finally got your shit running, and the results are amazing! thanks for entertaining me on reddit, hope I didn't piss you off all that much :)

**Comment by bghira** [comment]
just... try not to call people the 'n word' when they don't meet your expectations of expedience. that genuinely hurt. i am glad it is working for you now.

**Comment by cyan2k** [comment]
Perhaps you misread me, or mixed me up with someone else, but I never used the n-word in my life. I may be an asshole, but at least I'm not a racist asshole.

**Comment by bghira** [comment]
must have just been a case of mistaken identity - that is my mistake now, apologies to @cyan2k

**Comment by AmericanPresidentJimmyCarter** [comment]
@cyan2k Yeah sorry, that was some guy on civitai. The haters have been out in full force lately

**Comment by mliand** [comment]
The dev and snhnel versions of flux are based on the distillation model of the pro version. It is meaningless to support fine-tuning. It is completely impossible to learn complex tasks. It seems that there are still a large number of amateur users in this discussion.

**Comment by AmericanPresidentJimmyCarter** [comment]
> The dev and snhnel versions of flux are based on the distillation model of the pro version. It is meaningless to support fine-tuning. It is completely impossible to learn complex tasks. It seems that there are still a large number of amateur users in this discussion.

I trained cfg back into flux.dev with a 6 hour LoRA accidentally. If you just set the "fake" CFG value (the one they baked into with distillation) to anything greater than 1, the distillation breaks and CFG is restored. You just have to skip the first couple of steps because for some reason I don't yet understand if you use CFG on them it makes blurry images.

![concatenated_image](https://github.com/user-attachments/assets/d50678b3-af8b-45e2-ba89-cdfbaae367e5)

@ostris is [training CFG back into the schnell model on huggingface](https://huggingface.co/ostris/OpenFLUX.1), dunno how that's going.

**Comment by dill-shower** [comment]
> I trained cfg back into flux.dev with a 6 hour LoRA accidentally.

LoRA ≠ full finetune

**Comment by bghira** [comment]
^ this is incorrect. see LoRA paper about rank 128.

**Comment by pyros-sd-models** [comment]
> > I trained cfg back into flux.dev with a 6 hour LoRA accidentally.
> 
> LoRA ≠ full finetune

are you speedrunning "how often can I be wrong in one thread"?

**Comment by b-7777777** [comment]
Latest update to SD3 script made this smooth sailing for 12GB vram flux lora training, I've got a 4 hour timer on 1600 steps at the recommended settings and its at most using 7GB of my 12GB GPU. BLESS YOU KOHYA!!! <3

**Comment by D3voz** [comment]
For some reason my flux lora trained on kohya ss when using in comfyui runs extremely slow. I get 200s/it with the kohya flux lora which I get 1.8s/it using other flux lora from civitai

**Comment by leonary** [comment]
> For some reason my flux lora trained on kohya ss when using in comfyui runs extremely slow. I get 200s/it with the kohya flux lora while I get 1.8s/it using other flux lora from civitai

Is the slow inference possibly due to insufficient VRAM or RAM? You could try training LoRA with a lower dim value, or consider using a machine with more VRAM and RAM for inference. The fine-tuning results of Kohya's script are quite good; this is my result of fine-tuning Flux using Kohya's script, and there hasn't been any slowdown in inference speed.

![image](https://github.com/user-attachments/assets/b37c307f-bc6e-494a-a57a-04a3b4ad23a9)

**Comment by D3voz** [comment]
Yes, using my kohya trained lora eats all my vram in f8 , tried with 16gb vram and 20 gb vram machines . Using other lora eats like around 12 gb vram . I might have done something wrong . I did use 512 resolution which gave me around 3sec/it during training on 4060ti 16 gb . I used this - accelerate launch  --mixed_precision bf16 --num_cpu_threads_per_process 1 flux_train_network.py --pretrained_model_name_or_path "E:/ComfyUI/models/checkpoints/flux1-dev.safetensors" --clip_l "E:/ComfyUI/models/clip/clip_l.safetensors" --t5xxl "E:/ComfyUI/models/clip/t5xxl_fp16.safetensors" --ae "E:/ComfyUI/models/vae/ae.safetensors" --cache_latents_to_disk --save_model_as safetensors --sdpa --persistent_data_loader_workers --max_data_loader_n_workers 2 --seed 42 --gradient_checkpointing --mixed_precision bf16 --save_precision bf16 --network_module networks.lora_flux --network_dim 4 --optimizer_type adafactor --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False" --learning_rate 1e-4 --network_train_unet_only --cache_text_encoder_outputs --cache_text_encoder_outputs_to_disk --fp8_base --highvram --max_train_epochs 100 --save_every_n_epochs 10 --sample_every_n_steps 200 --sample_prompts "D:/github/ee/pt.txt" --sample_sampler "euler" --dataset_config "D:/github/ee/fx.toml" --output_dir "D:/github/kohya_ss/outputs" --output_name flux-lora-name --timestep_sampling sigmoid --model_prediction_type raw --guidance_scale 1.0 --loss_type l2      (might have changed a little if it gave error but this is what i saved on my text file to copy paste again)

**Comment by leonary** [comment]
> Yes, using my kohya trained lora eats all my vram in f8 , tried with 16gb vram and 20 gb vram machines . Using other lora eats like around 12 gb vram . 

That's strange because a LoRA with a dim value of 4 shouldn't consume more VRAM. Assuming that most of the LoRAs on Civitai are currently fine-tuned with Simple Tuner, and considering that both Simple Tuner and SD scripts are now only training the Unet, the VRAM requirements should be similar if the file sizes are comparable. Therefore, the slowdown in inference speed is likely due to insufficient RAM. 20GB of RAM might indeed be a bit tight for this kind of task. You could try restarting your computer to fully clear the VRAM and RAM, then test the inference speed of SD scripts' LoRA again.

**Comment by D3voz** [comment]
![om1](https://github.com/user-attachments/assets/9a467d8b-e8d9-4248-a127-e9361524fcff)
![ome](https://github.com/user-attachments/assets/2a3deced-cdfb-413b-9303-6abe5a74f05b)
For me it just goes out of memory when i use my lora trained on kohya . Lora rank 4 alpha 1 .

**Comment by leonary** [comment]
> For me it just goes out of memory when i use my lora trained on kohya . Lora rank 4 alpha 1 .

Would you mind sharing this lora? I would like to see how much video memory this lora would occupy on my machine.

**Comment by D3voz** [comment]
Unfortunately the lora is a person lora(ai person but still not mine)  so i cannot send it. I will train a celeb lora again tomorrow and will send the link. Only thing i can think of is that i did cropped the images to 512x512 as i am using 512 res for training . It is sad because the sampling images during training were very good and close to the actual look. Here 1st one is training sampling image and second one is training image. 
![cv](https://github.com/user-attachments/assets/0f919158-05f8-4070-8e38-608f000d0bb6)

**Comment by ssube** [comment]
@D3voz the high memory usage with some LoRAs has been reported in the ComfyUI repo: https://github.com/comfyanonymous/ComfyUI/issues/4343 . The slow inference is specific to Windows and the way it uses shared GPU memory, on Linux it simply runs out of memory (or since the recent updates, partially loads the LoRA with undefined results).

**Comment by DarkAlchy** [comment]
Long thread, and I am late to the party.  I want no part of SD3, or SAI, but we now have other options we can train on as good as Flux is that is truly open?  I, along with a lot of lawyers, don't like their licence, but we all wait for clarification from them (if it comes).  I have a 4090 and training at BS1 will be the one thing to cause me to toss in the towel on all this.  A lora taking 90 minutes to train without even the clip (that I drastically need for what I do) is far too long.  If this is the future, then I rather rot in antiquity.

**Comment by ddpasa** [comment]
> Long thread, and I am late to the party. I want no part of SD3, or SAI, but we now have other options we can train on as good as Flux is that is truly open? I, along with a lot of lawyers, don't like their licence, but we all wait for clarification from them (if it comes). I have a 4090 and training at BS1 will be the one thing to cause me to toss in the towel on all this. A lora taking 90 minutes to train without even the clip (that I drastically need for what I do) is far too long. If this is the future, then I rather rot in antiquity.

SD3 is a terrible model with very complicated legal mess of a license.  Given how much better Flux.1 is, I see no reason to waste any of my time on SD3.  Stability AI is a huge mess right now, and it's really good that new models are coming to the scene.

**Comment by bghira** [comment]
flux and sd3 have the same license, but both are unenforceable anyway. just have fun and do less drama.

**Comment by bghira** [comment]
what does it have to do with this thread? act like an adult if you are one. some of us are researchers who dont care about how open a model is and can make a living regardless.

**Comment by DarkAlchy** [comment]
It is enforceable and even as a researcher if you break it I'd even come after you lawyers if I were they.  What is with "researchers" willing to be pirates?

**Comment by DarkAlchy** [comment]
I didn't demand anything I only stated that people who obey licenses, and the law, look at the license and don't want to risk it then you come barging in to basically say "screw the licence and just have fun".  No, you don't break laws.  Beyond that whatever.

**Comment by bghira** [comment]
we are here obeying the law which doesnt support the license. what an odd situation. why dont you just use AuaFlow?

**Comment by cosmicoxytocin** [comment]
> You know, there are adults who make a living and don't wish to spend it all on lawyers and court costs defending ourselves. It isn't about just popping out some waifu/husbando.

I can assure you, researchers in the field of image-synthesis (outside Medical) are not moral busybodies opposed to waifus and husbandos. 
Regardless, your opinion is irrelevant to the discussion. Go right a tumblr blog about it, if you must.

**Comment by bash-j** [comment]
``` Traceback (most recent call last):
  File "/home/mikey/kohya_ss/sd-scripts/finetune/prepare_buckets_latents.py", line 286, in <module>
    main(args)
  File "/home/mikey/kohya_ss/sd-scripts/finetune/prepare_buckets_latents.py", line 89, in main
    vae = model_util.load_vae(args.model_name_or_path, weight_dtype)
  File "/home/mikey/kohya_ss/sd-scripts/library/model_util.py", line 1304, in load_vae
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(vae_sd, vae_config)
  File "/home/mikey/kohya_ss/sd-scripts/library/model_util.py", line 429, in convert_ldm_vae_checkpoint
    new_checkpoint["quant_conv.weight"] = vae_state_dict["quant_conv.weight"]```

What is this quant_conv.weight it is trying to find in the vae? I can't see it in the file. It looks like it's ignoring that I provided a path to the vae file also and trying to load it from the flux model file.

**Comment by popovidis** [comment]
Flux would be awesome

**Comment by iamrohitanshu** [comment]
> Latest update to SD3 branch script made this smooth sailing for 12GB vram flux lora training, I've got a 4 hour timer on 1600 steps at the recommended settings and its at most using 7GB of my 12GB GPU. BLESS YOU KOHYA!!! <3

@b-7777777 my 12GB 3060 is running out of memory. Can you tell me the base model, clip and vae you're using, please?

**Comment by bghira** [comment]
4 hours for 1600 steps is really really slow. you can rent a $0.200/hr 4090 and train 1600 steps in one hour. for less than $1. it probably costs you more per-kWh than it would to rent a cloud GPU

**Comment by hablaba** [comment]
I tried to see if I can run with Prodigy and it appears to work… weirdly only using ~17GB of VRAM, so not much more than when I was using AdamW8bit. That seems… wrong. Is there anything I’m missing on why Prodigy would “work” but potentially not be doing what I expect?

**Comment by hablaba** [comment]
Well, I can confirm training with prodigy works great. Just using my same settings as what I’d use in SDXL, setting d_coef to 2, betas 0.9,0.999, weight_decay 0.01. No warmup steps. Was able to get a great Lora of my dog at 1000 steps in about 35 mins on a 4090 (~2.2s/it) All other settings the same as the default recommendation on sd3 readme (except LR is 1 of course). Only used 17GB VRAM. 

Got better results than my attempted training using AdamW8bit constant for 3000 steps at 1e-4 and 1e-3. In those it seemed both undertrained (sometimes prompted other unrelated things) and also overfit (realistic style when prompting line art or comic book style)

**Comment by markrmiller** [comment]
Just to note for anyone else that’s been trying this or is just starting - at least for me, if you go with full bf16 and the fused backward pass option, I get I get messed up hands and then distorted body parts or bodies very quickly regardless of learning rate. No full bf16 and the fused optimizer option and I don’t get that. Surprisingly the latter also appears to use less VRAM, certainly not any more, and is faster. Of course, keep in mind things are changing, but that’s been my experience the last few days.

**Comment by oovm** [comment]
Can you add an script to quantify checkpoint (BF16) to NF4?
Many users do not have powerful hardware. I hope my model can be used for more people.

**Comment by wogam** [comment]
> I tried to see if I can train Lora with Prodigy and it appears to work… weirdly only using ~17GB of VRAM, so not much more than when I was using AdamW8bit. That seems… wrong. Is there anything I’m missing on why Prodigy would “work” but potentially not be doing what I expect?

What settings are you using to use such low VRAM? AdamW8bit training with 512px images is using almost 24gb ram for me.

**Comment by FurkanGozukara** [comment]
> > I tried to see if I can train Lora with Prodigy and it appears to work… weirdly only using ~17GB of VRAM, so not much more than when I was using AdamW8bit. That seems… wrong. Is there anything I’m missing on why Prodigy would “work” but potentially not be doing what I expect?
> 
> What settings are you using to use such low VRAM? AdamW8bit training with 512px images is using almost 24gb ram for me.
> 
> Edit: if you have any caption drop out and it doesn't cache the captions, the text encoders are loaded into the GPU memory during training time which leads to the high GPU usage.

with adafactor and 512px i go as low as 7.5 GB : https://youtu.be/nySGu12Y05k

**Comment by iamrohitanshu** [comment]
@wogam "The training can be done with 12GB VRAM GPUs with Adafactor optimizer, `--split_mode` and `train_blocks=single` options." from the readme.

**Comment by CaledoniaProject** [comment]
I'm wondering why the sd3 branch isn't merged yet?
