### ISSUE TITLE
AssertionError: resolution is required / resolution（解像度）指定は必須です

### ISSUE THREAD

**Issue by Shenrui-Ma** [kohya-ss/sd-scripts#1449]
I already wrote the path in the command,and my config.toml looks like this: 
`[general]
enable_bucket = true                        # 是否使用宽高比分桶（Aspect Ratio Bucketing）

[[datasets]]
resolution = 768                        # 学习分辨率
batch_size = 2                              # 批次大小

  [[datasets.subsets]]
  image_dir = '/root/work/sd-scripts/dataset_LoRA/6_dataset1'                     # 指定存放学习用图像的文件夹
  class_tokens = 'hoge girl'                # 指定标识符类别
  num_repeats = 5                          # 学习用图像的重复次数
`

Why the train_network.py cannot find the resolution?

```
 (venv) root@9c5a454d94fb:~/work/sd-scripts# /root/work/sd-scripts/venv/bin/python3.10 /root/work/sd-scripts/train_network.py --config_file=/root/work/sd-scripts/config.toml
2024-08-11 11:34:19 INFO     Loading settings from /root/work/sd-scripts/config.toml...                                                                                       train_util.py:3744
                    INFO     /root/work/sd-scripts/config                                                                                                                     train_util.py:3763
 2024-08-11 11:34:19 INFO     prepare tokenizer                                                                                                                                train_util.py:4227
 2024-08-11 11:34:20 INFO     Using DreamBooth method.                                                                                                                       train_network.py:171
 Traceback (most recent call last):
   File "/root/work/sd-scripts/train_network.py", line 1112, in <module>
     trainer.train(args)
   File "/root/work/sd-scripts/train_network.py", line 197, in train
     train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
   File "/root/work/sd-scripts/library/config_util.py", line 482, in generate_dataset_group_by_blueprint
     dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
   File "/root/work/sd-scripts/library/train_util.py", line 1916, in __init__
     self.dreambooth_dataset_delegate = DreamBoothDataset(
   File "/root/work/sd-scripts/library/train_util.py", line 1438, in __init__
     assert resolution is not None, f"resolution is required / resolution（解像度）指定は必須です"
 AssertionError: resolution is required / resolution（解像度）指定は必須です
```

**Comment by Shenrui-Ma** [comment]
There,thanks.
`[general]
enable_bucket = true                        # （Aspect Ratio Bucketing）

[[datasets]]
resolution = 768                        
batch_size = 2                              

  [[datasets.subsets]]
  image_dir = '/root/work/sd-scripts/dataset_LoRA/6_dataset1/'                     # detaset_images
  class_tokens = 'hoge girl'                
  num_repeats = 5                          
`

**Comment by Shenrui-Ma** [comment]
> ControlNet dataset is seemed to be used. Could you please share `config.toml`?

There,thanks.

`[general]
enable_bucket = true                        # （Aspect Ratio Bucketing）

[[datasets]]
resolution = 768                        
batch_size = 2                              

  [[datasets.subsets]]
  image_dir = '/root/work/sd-scripts/dataset_LoRA/6_dataset1/'                     # detaset_images
  class_tokens = 'hoge girl'                
  num_repeats = 5                          
`

**Comment by Shenrui-Ma** [comment]
> Oh, I'd like to know the settings in `config.toml` (training settings). The dataset config seems to be fine, so I wonder some parameter in `config.toml` may be wrong.

My bad...I have named the file names of train_comfig and dataset_comfig in reverse.Sorry to bother.
