### ISSUE TITLE
(SD3-FLUX)error: cache_text_encoder_outputs

### ISSUE THREAD

**Issue by JoshonSmith** [kohya-ss/sd-scripts#1460]
when added 'cache_text_encoder_outputs' and 'cache_text_encoder_outputs_to_disk' params, this error happened

log:

```
Traceback (most recent call last):
  File "/sd-scripts-sd3/flux_train_network.py", line 540, in <module>
    trainer.train(args)
  File "/sd-scripts-sd3/train_network.py", line 329, in train
    self.assert_extra_args(args, train_dataset_group)
  File "/sd-scripts-sd3/flux_train_network.py", line 38, in assert_extra_args
    assert (
AssertionError: when caching Text Encoder output, either caption_dropout_rate, shuffle_caption, token_warmup_step or caption_tag_dropout_rate cannot be used 
```

**Comment by JoshonSmith** [comment]
if I do not use these two cache* params, 
the error is below:

steps```
:   0%|                                                                                                                                                                                                                         | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/sd-scripts-sd3/flux_train_network.py", line 540, in <module>
    trainer.train(args)
  File "/sd-scripts-sd3/train_network.py", line 1012, in train
    self.sample_images(accelerator, args, 0, global_step, accelerator.device, vae, tokenizers, text_encoder, unet)   
  File "/data/mengxiangyu/diffusion/sd-scripts-sd3/flux_train_network.py", line 207, in sample_images
    accelerator, args, epoch, global_step, flux, ae, text_encoder, self.sample_prompts_te_outputs
AttributeError: 'FluxNetworkTrainer' object has no attribute 'sample_prompts_te_outputs'
```

**Comment by JoshonSmith** [comment]
when I use --fp8_base
the error is 

RuntimeError: "index_select_cuda" not implemented for 'Float8_e4m3fn'


I have updated torch followed README

**Comment by fireicewolf** [comment]
> when added 'cache_text_encoder_outputs' and 'cache_text_encoder_outputs_to_disk' params, this error happened
> 
> log:
> 
> ```
> Traceback (most recent call last):
>   File "/sd-scripts-sd3/flux_train_network.py", line 540, in <module>
>     trainer.train(args)
>   File "/sd-scripts-sd3/train_network.py", line 329, in train
>     self.assert_extra_args(args, train_dataset_group)
>   File "/sd-scripts-sd3/flux_train_network.py", line 38, in assert_extra_args
>     assert (
> AssertionError: when caching Text Encoder output, either caption_dropout_rate, shuffle_caption, token_warmup_step or caption_tag_dropout_rate cannot be used 
> ```

Set 
`shuffle_caption=False`
`caption_dropout_rate=0`
`token_warmup_step=0`
`caption_tag_dropout_rate=0`
When you set `cache_text_encoder_outputs=True`

**Comment by JoshonSmith** [comment]
> > when added 'cache_text_encoder_outputs' and 'cache_text_encoder_outputs_to_disk' params, this error happened
> > log:
> > ```
> > Traceback (most recent call last):
> >   File "/sd-scripts-sd3/flux_train_network.py", line 540, in <module>
> >     trainer.train(args)
> >   File "/sd-scripts-sd3/train_network.py", line 329, in train
> >     self.assert_extra_args(args, train_dataset_group)
> >   File "/sd-scripts-sd3/flux_train_network.py", line 38, in assert_extra_args
> >     assert (
> > AssertionError: when caching Text Encoder output, either caption_dropout_rate, shuffle_caption, token_warmup_step or caption_tag_dropout_rate cannot be used 
> > ```
> 
> Set `shuffle_caption=False` `caption_dropout_rate=0` `token_warmup_step=0` `caption_tag_dropout_rate=0` When you set `cache_text_encoder_outputs=True`

thanks!!!
I add these  params in the dataset_XXX.toml,
It works!

**Comment by fireicewolf** [comment]
> if I do not use these two cache* params, the error is below:
> 
> ```
> steps:   0%|                                                                                                                                                                                                                 | 0/8 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/sd-scripts-sd3/flux_train_network.py", line 540, in <module>
>     trainer.train(args)
>   File "/sd-scripts-sd3/train_network.py", line 1012, in train
>     self.sample_images(accelerator, args, 0, global_step, accelerator.device, vae, tokenizers, text_encoder, unet)   
>   File "/sd-scripts-sd3/flux_train_network.py", line 207, in sample_images
>     accelerator, args, epoch, global_step, flux, ae, text_encoder, self.sample_prompts_te_outputs
> AttributeError: 'FluxNetworkTrainer' object has no attribute 'sample_prompts_te_outputs'
> ```

I've made a temporary fix for this error(PR#1461)
Need @kohya-ss  to double check to make sure my modify will not effect other function's works.
