### ISSUE TITLE
[HELP] train flux lora on Multi GPU

### ISSUE THREAD

**Issue by kyrie111** [kohya-ss/sd-scripts#1481]
**[Environment]**

A800*8  
cuda11.8  
torch 2.4.0+cu118  
torchaudio 2.4.0+cu118  
torchvision 0.19.0+cu118  
accelerate 0.33.0

**[TrainingScript]**

```bash
accelerate launch \
    --config_file ./accelerate_config/default_config.yaml \
    --num_cpu_threads_per_process=8 \
    flux_train_network.py \
    --pretrained_model_name_or_path=$model_path \
    --train_data_dir=$train_data_dir \
    --clip_l=$clip_l_path \
    --t5xxl=$t5xxl_path \
    --ae=$ae_path \
    --t5xxl_max_token_length=$t5xxl_max_token_length \
    --cache_latents_to_disk \
    --save_model_as safetensors \
    --sdpa \
    --persistent_data_loader_workers \
    --max_data_loader_n_workers 8 \
    --seed 42 \
    --mixed_precision bf16 \
    --save_precision bf16 \
    --resolution 1024,1024 \
    --network_module networks.lora_flux \
    --network_dim 128 \
    --network_alpha 64 \
    --optimizer_type adamw8bit \
    --learning_rate 1e-4 \
    --network_train_unet_only \
    --cache_text_encoder_outputs \
    --cache_text_encoder_outputs_to_disk \
    --bucket_reso_steps 64 \
    --bucket_no_upscale \
    --min_bucket_reso 256 \
    --max_bucket_reso 1024 \
    --enable_bucket \
    --fp8_base \
    --highvram \
    --max_train_epochs 10 \
    --train_batch_size 4 \
    --save_every_n_epochs 2 \
    --output_dir="$output_dir" \
    --output_name=$output_name \
    --timestep_sampling sigmoid \
    --model_prediction_type raw \
    --guidance_scale 1.0 \
    --loss_type l2 \
    --gradient_checkpointing
```

**[TrainingLog]**

```bash
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/FLUX-training-scripts/sd-scripts/flux_train_network.py", line 408, in <module>  
[rank1]:     trainer.train(args)  
[rank1]:   File "/home/FLUX-training-scripts/sd-scripts/train_network.py", line 1092, in train  
[rank1]:     text_encoder_conds = text_encoding_strategy.encode_tokens(  
[rank1]:   File "/home/FLUX-training-scripts/sd-scripts/library/strategy_flux.py", line 63, in encode_tokens  
[rank1]:     clip_l, t5xxl = models  
[rank1]: ValueError: not enough values to unpack (expected 2, got 0)  
```

**I commented out the following lines of code in `train_network.py`**

```python
if self.is_text_encoder_not_needed_for_training(args):
    logger.info("text_encoder is not needed for training. deleting to save memory.")
    for t_enc in text_encoders:
        del t_enc
    text_encoders = []
```

**Then I got the following error like [issue1455]:**

```bash
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/sd-scripts/flux_train_network.py", line 408, in <module>
[rank1]:     trainer.train(args)
[rank1]:   File "/home/sd-scripts/train_network.py", line 1101, in train
[rank1]:     noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
[rank1]:   File "/home/sd-scripts/flux_train_network.py", line 312, in get_noise_pred_and_target
[rank1]:     model_pred = unet(
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank1]:     return model_forward(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank1]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/sd-scripts/library/flux_models.py", line 1006, in forward
[rank1]:     vec = vec + self.vector_in(y)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/sd-scripts/library/flux_models.py", line 560, in forward
[rank1]:     return checkpoint(self._forward, *args, use_reentrant=False, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
[rank1]:     return disable_fn(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 488, in checkpoint
[rank1]:     ret = function(*args, **kwargs)
[rank1]:   File "/home/sd-scripts/library/flux_models.py", line 556, in _forward
[rank1]:     return self.out_layer(self.silu(self.in_layer(x)))
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 119, in forward
[rank1]:     return F.linear(input, self.weight, self.bias)
[rank1]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
···
[rank2]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
···
[rank3]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

**Does anyone have any suggestions to help me?**

[issue1455]: https://github.com/kohya-ss/sd-scripts/issues/1455

**Comment by BootsofLagrangian** [comment]
Fix [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/train_network.py#L375C68-L377C1) Line 375

from 
`train_dataset_group.new_cache_latents(vae, accelerator.is_main_process)`

to
`train_dataset_group.new_cache_latents(vae, True)`

**Comment by kyrie111** [comment]
> Fix [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/train_network.py#L375C68-L377C1) Line 375
> 
> from `train_dataset_group.new_cache_latents(vae, accelerator.is_main_process)`
> 
> to `train_dataset_group.new_cache_latents(vae, True)`

I tried what you said, but it didn't solve my problem

**Comment by BootsofLagrangian** [comment]
> > Fix [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/train_network.py#L375C68-L377C1) Line 375
> > from `train_dataset_group.new_cache_latents(vae, accelerator.is_main_process)`
> > to `train_dataset_group.new_cache_latents(vae, True)`
> 
> I tried what you said, but it didn't solve my problem

And sorry for my mistake, I did wrong citation.

In [flux_train_network.py Line 169](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L166)

from 
`dataset.new_cache_text_encoder_outputs(text_encoders, accelerator.is_main_process)
`
to
`dataset.new_cache_text_encoder_outputs(text_encoders, True)
`

**Comment by kyrie111** [comment]
> > > Fix [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/train_network.py#L375C68-L377C1) Line 375
> > > from `train_dataset_group.new_cache_latents(vae, accelerator.is_main_process)`
> > > to `train_dataset_group.new_cache_latents(vae, True)`
> > 
> > 
> > I tried what you said, but it didn't solve my problem
> 
> Sorry for my mistake, I did wrong citation.
> 
> In [flux_train_network.py Line 169](https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L166)
> 
> from `dataset.new_cache_text_encoder_outputs(text_encoders, accelerator.is_main_process) ` to `dataset.new_cache_text_encoder_outputs(text_encoders, True) `

Thank you! It really works
