### ISSUE TITLE
where do i get dataset.toml file for FLux Finetuning?

### ISSUE THREAD

**Issue by protector131090** [kohya-ss/sd-scripts#1486]
where do i get dataset.toml file for FLux Finetuning?  im trying fr hours to launch with chatgpt and ai studio. No luck!

[general]
# define common settings here
flip_aug = true
color_aug = false
keep_tokens_separator= "|||"
shuffle_caption = false
caption_tag_dropout_rate = 0
caption_extension = ".txt"

[[datasets]]
# define the first resolution here
batch_size = 1
enable_bucket = true
resolution = [1024, 1024]

  [[datasets.subsets]]
  image_dir = "P:\\DREAMBOOTH\\FLUX\\Dreambooth\\imgDOlly"  
  num_repeats = 20

WHere do i get normal file example? its driving me crasy now...

(venv) S:\sd-scripts>accelerate launch  --mixed_precision bf16 --num_cpu_threads_per_process 1 flux_train.py --pretrained_model_name_or_path "S:\ai-toolkit\black-forest-labs\FLUX.1-dev\flux1-dev.sft" --clip_l "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip\clip_l.safetensors" --t5xxl "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip\t5xxl_fp16.safetensors" --ae "S:\ai-toolkit\black-forest-labs\FLUX.1-dev\ae.sft" --save_model_as safetensors --sdpa --persistent_data_loader_workers --max_data_loader_n_workers 2 --seed 42 --gradient_checkpointing --save_precision bf16 --dataset_config "P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq\dataset.toml" --output_dir "P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq" --output_name "DoolyQ_DB" --learning_rate 5e-5 --max_train_epochs 4 --sdpa --highvram --cache_text_encoder_outputs_to_disk --cache_latents_to_disk --save_every_n_epochs 1 --optimizer_type adafactor --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False" --timestep_sampling sigmoid --model_prediction_type raw --guidance_scale 1.0 --blockwise_fused_optimizers --double_blocks_to_swap 6 --cpu_offload_checkpointing
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
2024-08-21 15:38:39 WARNING  A matching Triton is not available, some optimizations will not be enabled                                                                                                                                                                                __init__.py:61
                             Traceback (most recent call last):
                               File "S:\sd-scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
highvram is enabled / highvramが有効です
                    WARNING  cache_latents_to_disk is enabled, so cache_latents is also enabled / cache_latents_to_diskが有効なため、cache_latentsを有効にします                                                                                                                   train_util.py:3899
2024-08-21 15:38:39 WARNING  cache_text_encoder_outputs_to_disk is enabled, so cache_text_encoder_outputs is also enabled / cache_text_encoder_outputs_to_diskが有効になっているため、cache_text_encoder_outputsも有効になります                                                     flux_train.py:62
                    INFO     Load dataset config from P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq\dataset.toml                                                                                                                                                                              flux_train.py:90
                    ERROR    Invalid user config / ユーザ設定の形式が正しくないようです                                                                                                                                                                                            config_util.py:371
Traceback (most recent call last):
  File "S:\sd-scripts\flux_train.py", line 823, in <module>
    train(args)
  File "S:\sd-scripts\flux_train.py", line 126, in train
    blueprint = blueprint_generator.generate(user_config, args)
  File "S:\sd-scripts\library\config_util.py", line 405, in generate
    sanitized_user_config = self.sanitizer.sanitize_user_config(user_config)
  File "S:\sd-scripts\library\config_util.py", line 368, in sanitize_user_config
    return self.user_config_validator(user_config)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['datasets'][0]['subsets'][0]['caption_dir']
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['S:\\sd-scripts\\venv\\Scripts\\python.exe', 'flux_train.py', '--pretrained_model_name_or_path', 'S:\\ai-toolkit\\black-forest-labs\\FLUX.1-dev\\flux1-dev.sft', '--clip_l', 'S:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\clip_l.safetensors', '--t5xxl', 'S:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'S:\\ai-toolkit\\black-forest-labs\\FLUX.1-dev\\ae.sft', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--save_precision', 'bf16', '--dataset_config', 'P:\\DREAMBOOTH\\FLUX\\Dreambooth\\Dollyq\\dataset.toml', '--output_dir', 'P:\\DREAMBOOTH\\FLUX\\Dreambooth\\Dollyq', '--output_name', 'DoolyQ_DB', '--learning_rate', '5e-5', '--max_train_epochs', '4', '--sdpa', '--highvram', '--cache_text_encoder_outputs_to_disk', '--cache_latents_to_disk', '--save_every_n_epochs', '1', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--timestep_sampling', 'sigmoid', '--model_prediction_type', 'raw', '--guidance_scale', '1.0', '--blockwise_fused_optimizers', '--double_blocks_to_swap', '6', '--cpu_offload_checkpointing']' returned non-zero exit status 1.

(venv) S:\sd-scripts>

**Comment by protector131090** [comment]
[general]
# define common settings here
flip_aug = true
color_aug = false
keep_tokens_separator= "|||"
shuffle_caption = false
caption_tag_dropout_rate = 0
caption_extension = ".txt"

[[datasets]]
# define the first resolution here
batch_size = 1
enable_bucket = true
resolution = [1024, 1024]

  [[datasets.subsets]]
  image_dir = "P:/DREAMBOOTH/FLUX/Dreambooth/imgDOlly"  
  num_repeats = 20



(venv) S:\sd-scripts>accelerate launch  --mixed_precision bf16 --num_cpu_threads_per_process 1 flux_train.py --pretrained_model_name_or_path "S:\ai-toolkit\black-forest-labs\FLUX.1-dev\flux1-dev.sft" --clip_l "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip\clip_l.safetensors" --t5xxl "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip\t5xxl_fp16.safetensors" --ae "S:\ai-toolkit\black-forest-labs\FLUX.1-dev\ae.sft" --save_model_as safetensors --sdpa --persistent_data_loader_workers --max_data_loader_n_workers 2 --seed 42 --gradient_checkpointing --save_precision bf16 --dataset_config "P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq\dataset.toml" --output_dir "P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq" --output_name "DoolyQ_DB" --learning_rate 5e-5 --max_train_epochs 4 --sdpa --highvram --cache_text_encoder_outputs_to_disk --cache_latents_to_disk --save_every_n_epochs 1 --optimizer_type adafactor --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False" --timestep_sampling sigmoid --model_prediction_type raw --guidance_scale 1.0 --blockwise_fused_optimizers --double_blocks_to_swap 6 --cpu_offload_checkpointing
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
2024-08-21 17:42:52 WARNING  A matching Triton is not available, some optimizations will not be enabled                                                                                                                                                                                __init__.py:61
                             Traceback (most recent call last):
                               File "S:\sd-scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
highvram is enabled / highvramが有効です
                    WARNING  cache_latents_to_disk is enabled, so cache_latents is also enabled / cache_latents_to_diskが有効なため、cache_latentsを有効にします                                                                                                                   train_util.py:3899
2024-08-21 17:42:52 WARNING  cache_text_encoder_outputs_to_disk is enabled, so cache_text_encoder_outputs is also enabled / cache_text_encoder_outputs_to_diskが有効になっているため、cache_text_encoder_outputsも有効になります                                                     flux_train.py:62
                    INFO     Load dataset config from P:\DREAMBOOTH\FLUX\Dreambooth\Dollyq\dataset.toml                                                                                                                                                                              flux_train.py:90
                    ERROR    Invalid user config / ユーザ設定の形式が正しくないようです                                                                                                                                                                                            config_util.py:371
Traceback (most recent call last):
  File "S:\sd-scripts\flux_train.py", line 823, in <module>
    train(args)
  File "S:\sd-scripts\flux_train.py", line 126, in train
    blueprint = blueprint_generator.generate(user_config, args)
  File "S:\sd-scripts\library\config_util.py", line 405, in generate
    sanitized_user_config = self.sanitizer.sanitize_user_config(user_config)
  File "S:\sd-scripts\library\config_util.py", line 368, in sanitize_user_config
    return self.user_config_validator(user_config)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "S:\sd-scripts\venv\lib\site-packages\voluptuous\schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['datasets'][0]['subsets'][0]['caption_dir']
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['S:\\sd-scripts\\venv\\Scripts\\python.exe', 'flux_train.py', '--pretrained_model_name_or_path', 'S:\\ai-toolkit\\black-forest-labs\\FLUX.1-dev\\flux1-dev.sft', '--clip_l', 'S:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\clip_l.safetensors', '--t5xxl', 'S:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'S:\\ai-toolkit\\black-forest-labs\\FLUX.1-dev\\ae.sft', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--save_precision', 'bf16', '--dataset_config', 'P:\\DREAMBOOTH\\FLUX\\Dreambooth\\Dollyq\\dataset.toml', '--output_dir', 'P:\\DREAMBOOTH\\FLUX\\Dreambooth\\Dollyq', '--output_name', 'DoolyQ_DB', '--learning_rate', '5e-5', '--max_train_epochs', '4', '--sdpa', '--highvram', '--cache_text_encoder_outputs_to_disk', '--cache_latents_to_disk', '--save_every_n_epochs', '1', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--timestep_sampling', 'sigmoid', '--model_prediction_type', 'raw', '--guidance_scale', '1.0', '--blockwise_fused_optimizers', '--double_blocks_to_swap', '6', '--cpu_offload_checkpointing']' returned non-zero exit status 1.

(venv) S:\sd-scripts>

**Comment by protector131090** [comment]
[general]
# define common settings here
flip_aug = true
color_aug = false
keep_tokens_separator= "|||"
shuffle_caption = false
caption_tag_dropout_rate = 0
caption_extension = ".txt"

[[datasets]]
# define the first resolution here
batch_size = 1
enable_bucket = true
resolution = [1024, 1024]

  [[datasets.subsets]]
  image_dir = "P:\\DREAMBOOTH\\FLUX\\Dreambooth\\imgDOlly" 
  num_repeats = 20
  caption_dir = "P:\\DREAMBOOTH\\FLUX\\Dreambooth\\captions" 
![Снимок экрана (3168)](https://github.com/user-attachments/assets/d653ece5-96e8-4abe-b66f-8d932efeb937)

**Comment by protector131090** [comment]
![Uploading Снимок экрана (3169).png…]()

**Comment by protector131090** [comment]
no idea what did it but it started training. after 40 times correcting it again and again,

**Comment by protector131090** [comment]
but now i get epoch 1/4
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
2024-08-21 18:44:03 WARNING  A matching Triton is not available, some optimizations will not be enabled                                                                                                                                                                                __init__.py:61
                             Traceback (most recent call last):
                               File "S:\sd-scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
S:\sd-scripts\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
2024-08-21 18:44:06 WARNING  A matching Triton is not available, some optimizations will not be enabled                                                                                                                                                                                __init__.py:61
                             Traceback (most recent call last):
                               File "S:\sd-scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
2024-08-21 18:44:06 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                                                                                                       train_util.py:668
                    INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                                                                                                       train_util.py:668
Traceback (most recent call last):
  File "S:\sd-scripts\flux_train.py", line 823, in <module>
    train(args)
  File "S:\sd-scripts\flux_train.py", line 619, in train
    model_pred = flux(
  File "S:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\sd-scripts\library\flux_models.py", line 1007, in forward
    img = self.img_in(img)
  File "S:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\sd-scripts\venv\lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and BFloat16
steps:   0%|                                                                                                                                                                                                                                                               | 0/4720 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "S:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['S:\\sd-scripts\\venv\\Scripts\\python.exe', 'flux_train.py', '--pretrained_model_name_or_path', 'S:/ai-toolkit/black-forest-labs/FLUX.1-dev/flux1-dev.sft', '--clip_l', 'S:/ComfyUI/ComfyUI_windows_portable/ComfyUI/models/clip/clip_l.safetensors', '--t5xxl', 'S:/ComfyUI/ComfyUI_windows_portable/ComfyUI/models/clip/t5xxl_fp16.safetensors', '--ae', 'S:/ai-toolkit/black-forest-labs/FLUX.1-dev/ae.sft', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--save_precision', 'bf16', '--dataset_config', 'P:/DREAMBOOTH/FLUX/Dreambooth/Dollyq/dataset.toml', '--output_dir', 'P:/DREAMBOOTH/FLUX/Dreambooth/Dollyq', '--output_name', 'DoolyQ_DB', '--learning_rate', '5e-5', '--max_train_epochs', '4', '--sdpa', '--highvram', '--cache_text_encoder_outputs_to_disk', '--cache_latents_to_disk', '--save_every_n_epochs', '1', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--timestep_sampling', 'sigmoid', '--model_prediction_type', 'raw', '--guidance_scale', '1.0', '--blockwise_fused_optimizers', '--double_blocks_to_swap', '6', '--cpu_offload_checkpointing']' returned non-zero exit status 1.

(venv) S:\sd-scripts>

**Comment by protector131090** [comment]
mat1 and mat2 must have the same dtype, but got Float and BFloat16
