### ISSUE TITLE
sd3 branch flux_train and flux_train_network fail while unloading VAE and text encoders 

### ISSUE THREAD

**Issue by SQCU** [kohya-ss/sd-scripts#1498]
Problem (is in the title):
Using the template training script provided in the readme for flux training, the training process consistently loads the t5 encoder, clip encoder, and vae as expected, then throws an error and terminates training.
the specific logged error is `NotImplementedError: Cannot copy out of meta tensor; no data! `, and appears both for lora training and full model fine tuning training. Following the instructions in the error ( adding `.to_empty(device)` to line 973 of `library/flux_models.py` ) does not, of course, resolve the error.
all tests run in a fresh install of sd-scripts with the exact python version (3.10.6) mentioned in the readme, the exact pytorch mentioned in the readme ( `pip3 install torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu124` ), and so on.

Interesting notes:
flux_train successfully writes cached image latent files and text embeddings to the directory where the training data is held! a substantial portion of the training script's normal routine is definitely being carried out, and there is a definite error at the precise point where u-net training would have begun.

Error log, attached:
```override steps. steps for 10 epochs is / 指定エポックまでのステップ数: 60
enable full bf16 training.
Traceback (most recent call last):
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\flux_train.py", line 905, in <module>
    train(args)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\flux_train.py", line 429, in train
    accelerator.unwrap_model(flux).move_to_device_except_swap_blocks(accelerator.device)  # reduce peak memory usage
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\library\flux_models.py", line 973, in move_to_device_except_swap_blocks
    self.to(device)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1167, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
Traceback (most recent call last):
  File "C:\Users\neet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\neet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "F:\dox\ai\sd-scripts\kohya_ss-sd3\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\dox\\ai\\sd-scripts\\kohya_ss-sd3\\sd-scripts\\venv\\Scripts\\python.exe', 'F:/dox/ai/sd-scripts/kohya_ss-sd3/sd-scripts/flux_train.py', '--pretrained_model_name_or_path', 'F:/dox/ai/stable-diffusion-webui-forge/models/Stable-diffusion/flux1DFp16_v10.safetensors', '--clip_l', 'F:/dox/ai/models/flux_text_encoders/clip_l.safetensors', '--t5xxl', 'F:/dox/ai/models/flux_text_encoders/t5xxl_fp16.safetensors', '--ae', 'F:/dox/ai/stable-diffusion-webui-forge/models/VAE/flux_ae.sft', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--dataset_config', 'F:/dox/ai/training-data/inbound/train_class/tiny_bundled_class/flux_hypah_tiny_i.toml', '--output_dir', 'F:/dox/ai/stable-diffusion-webui-forge/models/', '--output_name', 'flux1dFP16_hypah1', '--learning_rate', '5e-5', '--max_train_epochs', '10', '--sdpa', '--highvram', '--cache_text_encoder_outputs_to_disk', '--cache_latents_to_disk', '--save_every_n_epochs', '1', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--timestep_sampling', 'sigmoid', '--model_prediction_type', 'raw', '--guidance_scale', '1.0', '--fused_backward_pass', '--double_blocks_to_swap', '6', '--full_bf16']' returned non-zero exit status 1.```

**Comment by SQCU** [comment]
thank you for the reply! aforementioned error reproduces in the same manner when loading previous checkpoint, or illyasaviel's nf4 or fp8 checkpoints.
u-net training begins as expected if I load the original fp32 model release.

**Comment by Peli86** [comment]
Same problem, tried original and some other flux1-dev.

**Comment by setothegreat** [comment]
> fp8 checkpoint seems to cause this error. Please use fp16 version.

This will also happen if trying to load a FP16 checkpoint that has had a LoRA applied to it. It won't happen if you use the Flux_Merge_LoRA script, but that script seems to produce substantially worse image generation results than just applying the LoRA and then saving the model using Comfy.
