### ISSUE TITLE
Error when trying to extract difference between two SD2.1 checkpoints as safetensors LoRA network

### ISSUE THREAD

**Issue by anon-1337** [kohya-ss/sd-scripts#150]
Basically the title. Extracting in *.ckpt format gives me no error.
```console
(venv) PS D:\git\sd-scripts\networks> python .\extract_lora_from_models.py --v2 --model_org "D:\git\stable-diffusion-webui\models\Stable-diffusion\v2-1_768-ema-pruned.safetensors" --model_tuned "F:\Files\Stable Diffusion\models\classicNegativeSD21_classicNegative768px.ckpt" --dim 256 --device cuda --save_to ClassicNegative768_for_SD2.1768.safetensors
loading SD model : D:\git\stable-diffusion-webui\models\Stable-diffusion\v2-1_768-ema-pruned.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : F:\Files\Stable Diffusion\models\classicNegativeSD21_classicNegative768px.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 192 modules.
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 192 modules.
Text encoder is same. Extract U-Net only.
calculating by svd
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 192/192 [00:32<00:00,  5.86it/s]
enable LoRA for U-Net
LoRA has 576 weights.
Loading extracted LoRA weights: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\git\sd-scripts\networks\extract_lora_from_models.py", line 164, in <module>
    svd(args)
  File "D:\git\sd-scripts\networks\extract_lora_from_models.py", line 144, in svd
    lora_network_o.save_weights(args.save_to, save_dtype, metadata)
  File "D:\git\sd-scripts\networks\lora.py", line 230, in save_weights
    model_hash, legacy_hash = train_util.precalculate_safetensors_hashes(state_dict, metadata)
AttributeError: module 'library.train_util' has no attribute 'precalculate_safetensors_hashes'
```

**Comment by anon-1337** [comment]
Thanks. My fault.
