### ISSUE TITLE
Precision Issue

### ISSUE THREAD

**Issue by tristanwqy** [kohya-ss/sd-scripts#1515]
I got this during the flux training，I was using multi gpu with deepspeed stage2 
```
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/ubuntu/sd-scripts/flux_train_network.py", line 411, in <module>
[rank2]:     trainer.train(args)
[rank2]:   File "/home/ubuntu/sd-scripts/train_network.py", line 1102, in train
[rank2]:     noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
[rank2]:                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/sd-scripts/flux_train_network.py", line 313, in get_noise_pred_and_target
[rank2]:     model_pred = unet(
[rank2]:                  ^^^^^
[rank2]:   File "/home/ubuntu/miniconda3/envs/sd-scripts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/miniconda3/envs/sd-scripts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/sd-scripts/library/flux_models.py", line 1009, in forward
[rank2]:     img = self.img_in(img)
[rank2]:           ^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/miniconda3/envs/sd-scripts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/miniconda3/envs/sd-scripts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/miniconda3/envs/sd-scripts/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 117, in forward
[rank2]:     return F.linear(input, self.weight, self.bias)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: RuntimeError: mat1 and mat2 must have the same dtype, but got Float and BFloat16
```
and here is my config toml, what's the problem?
```
# path
pretrained_model_name_or_path = "/home/ubuntu/MyFiles/xiaodi/training/workspace/models/models--black-forest-labs--FLUX.1-dev/flux1-dev.sft"
clip_l = "/home/ubuntu/MyFiles/xiaodi/training/workspace/models/models--stabilityai--stable-diffusion-3-medium/text_encoders/clip_l.safetensors"
t5xxl = "/home/ubuntu/MyFiles/xiaodi/training/workspace/models/models--stabilityai--stable-diffusion-3-medium/text_encoders/t5xxl_fp16.safetensors"
tokenizer_cache_dir = "/home/ubuntu/MyFiles/xiaodi/training/workspace/models"
ae = "/home/ubuntu/MyFiles/xiaodi/training/workspace/models/models--black-forest-labs--FLUX.1-dev/ae.sft"
output_dir = "/home/ubuntu/MyFiles/xiaodi/training/output/flux/sd-scripts/flux_lora_200k"
output_name = "flux_lora_200k"
# log
logging_dir = "/home/ubuntu/MyFiles/xiaodi/training/output/flux/sd-scripts/flux_lora_200k/logs"
console_log_level = "INFO"
log_tracker_name = "sd_scripts_flux_lora_200k"
log_with = "wandb"
# sampler
seed = 42
sample_every_n_steps = 2000
sample_prompts = "/home/ubuntu/sd-scripts/test_prompts.txt"
dataset_config = "/home/ubuntu/sd-scripts/train/flux_1024/flux_lora_train_dataset.toml"
# train config
max_train_epochs = 20
mixed_precision = "bf16"
no_half_vae = true
gradient_checkpointing = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
save_model_as_safetensors = true
highvram = true
sdpa = true
persistent_data_loader_workers = true
max_data_loader_n_workers = 4
# save config
save_every_n_steps = 2000
save_every_n_epoch = 1
save_state = true
save_model_as = "safetensors"
# lora setting
network_module = "networks.lora_flux"
network_dim = 64
# train lr
gradient_accumulation_steps = 4
#train_text_encoder = true
optimizer_type = "AdamW"
learning_rate = 5e-6
network_train_unet_only = true
guidance_scale = 1.0
loss_type = "l2"
model_prediction_type = "raw"
timestep_sampling = "sigmoid"
#learning_rate_te1 = 5e-7
#learning_rate_te2 = 5e-7
#noise_offset = 0.1
#lr_warmup_steps = 0
# deepspeed
deepspeed = true
zero_stage = 2
# lowram
#lowram = true
#torch_compile = true
```

**Comment by tristanwqy** [comment]
It works after closing deepspeed , maybe that's the problem? Lora training does not support deepspeed yet?
