### ISSUE TITLE
flux text encoder training not working 

### ISSUE THREAD

**Issue by DarkViewAI** [kohya-ss/sd-scripts#1518]
Traceback (most recent call last):
  File "/home/ai/Downloads/kohya_ss/sd-scripts/flux_train_network.py", line 411, in <module>
    trainer.train(args)
  File "/home/ai/Downloads/kohya_ss/sd-scripts/train_network.py", line 330, in train
    self.assert_extra_args(args, train_dataset_group)
  File "/home/ai/Downloads/kohya_ss/sd-scripts/flux_train_network.py", line 43, in assert_extra_args
    assert (
AssertionError: network for Text Encoder cannot be trained with caching Text Encoder outputs / Text Encoderの出力をキャ ッシュしながらText Encoderのネットワークを学習することはできません
Traceback (most recent call last):

**Comment by DarkViewAI** [comment]
<img width="1028" alt="sss" src="https://github.com/user-attachments/assets/6de58c8b-a534-4ff6-a949-4969e84da628">
managed to get passed that error, now getting this @kohya-ss
