### ISSUE TITLE
TokenizeStrategy strategy is already set

### ISSUE THREAD

**Issue by hablaba** [kohya-ss/sd-scripts#1531]
Hello!

I run sd-scripts via a small Python file. I basically have some small utilities that make it easier for me to get things setup and I run it in Docker to manage my dependencies. As a part of this I like to be able to do a loop on hyperparameters to fire off multiple trainings in a row. For example I may want to run a training for dim 16, 32, etc. in one execution. At a high level I do something like this:

```
for dim in dims:
    execute(dim)
```

I believe this used to work a while ago when I did it in this repo. Recently when I tried it for a Flux training I get the following error:

```
Traceback (most recent call last):
  File "/sd-scripts/external/train_flux_prodigy.py", line 33, in <module>
    execute(
  File "/sd-scripts/external/flux_utils_prodigy.py", line 135, in execute
    trainer.train(args)
  File "/sd-scripts/train_network.py", line 257, in train
    strategy_base.TokenizeStrategy.set_strategy(tokenize_strategy)
  File "/sd-scripts/library/strategy_base.py", line 28, in set_strategy
    raise RuntimeError(f"Internal error. {cls.__name__} strategy is already set")
RuntimeError: Internal error. TokenizeStrategy strategy is already set

```

The error itself is pretty clear and it is clearly related to this piece of code:
```
class TokenizeStrategy:
    _strategy = None  # strategy instance: actual strategy class

    @classmethod
    def set_strategy(cls, strategy):
        if cls._strategy is not None:
            raise RuntimeError(f"Internal error. {cls.__name__} strategy is already set")
        cls._strategy = strategy
```

I'm considering just deleting

```
if cls._strategy is not None:
            raise RuntimeError(f"Internal error. {cls.__name__} strategy is already set")
```

Could you clarify why this check is necessary? I am hesitant to delete it since I presume you added it for a reason? Would it be an issue to delete it and change parameters or run a training on a different dataset all within the same program execution?

**Comment by hablaba** [comment]
I figured out a better way to set this up for my scripts
