### ISSUE TITLE
flux lora training does not start

### ISSUE THREAD

**Issue by nim00e** [kohya-ss/sd-scripts#1589]
=============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
                    INFO     use 8-bit AdamW optimizer | {}                       train_util.py:4343
running training / 学習開始
  num examples / サンプル数: 3
  num batches per epoch / 1epochのバッチ数: 3
  num epochs / epoch数: 250
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 750
steps:   0%|                                                                | 0/750 [00:00<?, ?it/s]
epoch 1/250
Traceback (most recent call last):
  File "/workspace/nima_workspace/kohya_ss/sd-scripts/flux_train.py", line 905, in <module>
    train(args)
  File "/workspace/nima_workspace/kohya_ss/sd-scripts/flux_train.py", line 642, in train
    for step, batch in enumerate(train_dataloader):
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 350, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/workspace/nima_workspace/kohya_ss/sd-scripts/library/train_util.py", line 1418, in __getitem__
    im_h == self.height and im_w == self.width
AssertionError: image size is small / 画像サイズが小さいようです: /workspace/nima_workspace/kohya_ss/experiments/test_lora/img_2/img/1_ohwx sofa/17.png
steps:   0%|                                                                | 0/750 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/miniconda3/envs/kohya/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/workspace/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/miniconda3/envs/kohya/bin/python', '/workspace/nima_workspace/kohya_ss/sd-scripts/flux_train.py', '--config_file', '/workspace/nima_workspace/kohya_ss/experiments/test_lora/img_2/model/config_dreambooth-20240910-112002.toml']' returned non-zero exit status 1.
11:20:12-804962 INFO     Training has ended.

here is my settings: 

                    INFO     3 train images with repeating.                       train_util.py:1844
                    INFO     0 reg images.                                        train_util.py:1847
                    WARNING  no regularization images /                           train_util.py:1852
                             正則化画像が見つかりませんでした                                       
                    INFO     [Dataset 0]                                          config_util.py:570
                               batch_size: 1                                                        
                               resolution: (1024, 1024)                                             
                               enable_bucket: False                                                 
                               network_multiplier: 1.0                                              
                                                                                                    
                               [Subset 0 of Dataset 0]                                              
                                 image_dir:                                                         
                             "/workspace/nima_workspace/kohya_ss/experiments/test                   
                             _lora/img_2/img/1_ohwx sofa"                                           
                                 image_count: 3                                                     
                                 num_repeats: 1                                                     
                                 shuffle_caption: False                                             
                                 keep_tokens: 0                                                     
                                 keep_tokens_separator:                                             
                                 caption_separator: ,                                               
                                 secondary_separator: None                                          
                                 enable_wildcard: False                                             
                                 caption_dropout_rate: 0                                            
                                 caption_dropout_every_n_epoches: 0                                 
                                 caption_tag_dropout_rate: 0.0                                      
                                 caption_prefix: None                                               
                                 caption_suffix: None                                               
                                 color_aug: False                                                   
                                 flip_aug: False                                                    
                                 face_crop_aug_range: None                                          
                                 random_crop: False                                                 
                                 token_warmup_min: 1,                                               
                                 token_warmup_step: 0,                                              
                                 alpha_mask: False,                                                 
                                 is_reg: False                                                      
                                 class_tokens: ohwx sofa                                            
                                 caption_extension: .txt 
                                 
       
also why the accelerator device is printed as cpu?
accelerator device: cpu

**Comment by nim00e** [comment]
I set accelerate config to gpu and gave [all] for gpu ids. but still facing this issue
