### ISSUE TITLE
AttributeError: 'LycorisNetworkKohya' object has no attribute 'train_t5xxl'

### ISSUE THREAD

**Issue by sd2530615** [kohya-ss/sd-scripts#1617]
im using Lycoris.kohya module and training lokr, then this error pops out, this error happened when i updating to the latest sd3-branch.(i t works fine half month ago)

Traceback (most recent call last):
  File "F:\AI_LORA_TRAIN\sd-scripts_new\flux_train_network.py", line 519, in <module>
    trainer.train(args)
  File "F:\AI_LORA_TRAIN\sd-scripts_new\train_network.py", line 441, in train
    self.post_process_network(args, accelerator, network, text_encoders, unet)
  File "F:\AI_LORA_TRAIN\sd-scripts_new\flux_train_network.py", line 170, in post_process_network
    self.train_t5xxl = network.train_t5xxl
  File "F:\AI_LORA_TRAIN\sd-scripts_new\venv\lib\site-packages\torch\nn\modules\module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LycorisNetworkKohya' object has no attribute 'train_t5xxl'
Traceback (most recent call last):
  File "D:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\AI_LORA_TRAIN\sd-scripts_new\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\AI_LORA_TRAIN\sd-scripts_new\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "F:\AI_LORA_TRAIN\sd-scripts_new\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "F:\AI_LORA_TRAIN\sd-scripts_new\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\AI_LORA_TRAIN\\sd-scripts_new\\venv\\Scripts\\python.exe', 'F:\\AI_LORA_TRAIN\\sd-scripts_new\\flux_train_network.py', '--config_file', 'F:\\AI_LORA_TRAIN\\sd-scripts_new\\toml_output\\yyshana_flux_v1.toml']' returned non-zero exit status 1.
Press any key to continue . . .

**Comment by sd2530615** [comment]
same issue when i switch module to 'networks.lora'

**Comment by sd2530615** [comment]
my toml being like:
[basics]
pretrained_model_name_or_path = "F:/AI_SD/models/Stable-diffusion/flux/flux1-dev.safetensors"
train_data_dir = "I:/TRAIN____AIoutput/OnmyojiHana/imgsdxl"
#network_weights = "F:/AI_SD/models/Lora/t/WIP/flux/Kate_flux_v5.safetensors"
clip_l = "F:/ComfyUI/models/clip/clip_l.safetensors"
t5xxl = "F:/ComfyUI/models/clip/t5xxl_fp16.safetensors"
ae = "F:/AI_SD/models/VAE/flux/fux_dev_vae_fp16.safetensors"
resolution = "512,512"
seed = 23
mixed_precision = "bf16"
fp8_base = true
clip_skip = 2

[output]
output_dir = "F:/AI_SD/models/Lora/t/WIP/flux/"
output_name = "yyshana_flux_v1"
save_precision = "bf16"
save_every_n_epochs = 2
max_token_length = 225
sdpa = true
max_train_epochs = 10


[learning_rate]
unet_lr = 1e-3
#text_encoder_lr = 2e-7
text_encoder_lr = 0

[Lr_scheduler]
lr_scheduler = "cosine_with_restarts"
# "linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup" 
lr_warmup_steps = 24
lr_decay_steps = 48
lr_scheduler_num_cycles = 2
#lr_scheduler_power = 1.0	# Polynomial power for polynomial scheduler
#lr_scheduler_min_lr_ratio = 0.1

#[optimizer]
#train_batch_size = 2
#gradient_checkpointing = true
#gradient_accumulation_steps = 4
#optimizer_type = "Prodigy"
#learning_rate = 1.0
#optimizer_args = [ "weight_decay=0.01", "betas=.9,.99", "decouple=True", "use_bias_correction=True", "d_coef=0.5", "d0=1e-4",]
#lr_decay_steps = 48
#lr_scheduler_num_cycles = 2
#lr_scheduler_min_lr_ratio = 0.1

######optimizer == adamwschedulefree,sgdschedulefree,prodigy,adamw8bit,lion8bit

[optimizer]
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
#use_8bit_adam = true
optimizer_type = "adamw8bit"
#optimizer_type = "adamwschedulefree"
optimizer_args = [ "weight_decay=0.01", "betas=.9,.99",]
lr_decay_steps = 48
lr_scheduler_num_cycles = 2
lr_scheduler_min_lr_ratio = 0.1

[network]
network_module = "lycoris.kohya"
#network_module = "networks.lora"
network_dim = 4
network_alpha = 1
network_args = [ "algo=lokr", "preset=attn-mlp", "factor=8", "decompose_both=True", "full_matrix=True",]
#network_args = [ "algo=lokr", "preset=attn-mlp", "factor=8", "decompose_both=True","full_matrix=True","loraplus_unet_lr_ratio=4",]
#network_args = [ "algo=lora", "preset=attn-mlp", "decompose_both=True","loraplus_unet_lr_ratio=4",]
network_train_unet_only = true

[Logging]
#logging_dir = "logs_training"
log_with = "wandb"
#log_prefix = ""
wandb_api_key = "b817d4118df3571091566d60581560acfe8de94b"

[extras]
caption_extension = ".txt"
keep_tokens = 0
shuffle_caption = false
keep_tokens_separator = "|||"
secondary_separator = ";;;"
cache_latents = true
vae_batch_size = 4
cache_latents_to_disk = true
enable_bucket = true
max_bucket_reso = 1216
bucket_no_upscale = true
apply_t5_attn_mask = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
guidance_scale = 1.0
guidance_rescale = true
timestep_sampling = "sigmoid"
model_prediction_type = "raw"
logging_dir = "./logs"
persistent_data_loader_workers = true
max_data_loader_n_workers = 8

**Comment by envy-ai** [comment]
What did you do to actually fix this?

**Comment by envy-ai** [comment]
Figured it out, in case somebody else googles this and they're having trouble training lycoris but not standard loras:

```
pip uninstall lycoris-lora
pip uninstall lycoris-lora
# I had to run the above twice because I somehow had two different versions of the package installed.

git clone https://github.com/KohakuBlueleaf/LyCORIS
cd LyCORIS
pip install .
```
