### ISSUE TITLE
cant sample with fux (fine-tuning)

### ISSUE THREAD

**Issue by betterftr** [kohya-ss/sd-scripts#1647]
I get an error when it sample time

ae = "C:/train/flux/ae.safetensors"
apply_t5_attn_mask = false
blockwise_fused_optimizers = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_l = "C:/train/flux/clip_l.safetensors"
cpu_offload_checkpointing = true
dataset_config = "C:/train/test.toml"
dataset_repeats = 1
discrete_flow_shift = 3.1582
dynamo_backend = "no"
enable_bucket = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1
huber_c = 0.1
huber_schedule = "snr"
in_json = "C:/train/C:/train/meta_lat.json"
learning_rate = 2e-5
logging_dir = "C:/train"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_warmup_steps = 50
max_bucket_reso = 1024
max_data_loader_n_workers = 2
max_timestep = 1000
max_token_length = 75
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
model_prediction_type = "raw"
multires_noise_discount = 0.3
noise_offset_type = "Original"
optimizer_args = [ "relative_step=False", "scale_parameter=False", "warmup_init=False",]
optimizer_type = "Adafactor"
output_dir = "C:/train"
output_name = "last"
persistent_data_loader_workers = 1
pretrained_model_name_or_path = "C:/train/flux/flux1-dev.safetensors"
resolution = "1024,1024"
sample_every_n_steps = 1
sample_prompts = "C:/train\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 10
save_model_as = "safetensors"
save_precision = "bf16"
save_state = true
sdpa = true
seed = 1234
blocks_to_swap = 8
t5xxl = "C:/train/flux/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
timestep_sampling = "shift"
train_batch_size = 1
train_blocks = "all"
wandb_run_name = "last"

```
Traceback (most recent call last):                                                      | 1/30 [00:01<00:39,  1.36s/it]
  File "C:\kohya_ss\sd-scripts\flux_train.py", line 993, in <module>
    train(args)
  File "C:\kohya_ss\sd-scripts\flux_train.py", line 842, in train
    flux_train_utils.sample_images(
  File "C:\kohya_ss\sd-scripts\library\flux_train_utils.py", line 90, in sample_images
    sample_image_inference(
  File "C:\kohya_ss\sd-scripts\library\flux_train_utils.py", line 229, in sample_image_inference
    x = denoise(flux, noise, img_ids, t5_out, txt_ids, l_pooled, timesteps=timesteps, guidance=scale, t5_attn_mask=t5_attn_mask)
  File "C:\kohya_ss\sd-scripts\library\flux_train_utils.py", line 316, in denoise
    pred = model(
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 820, in forward
    return model_forward(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 808, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\kohya_ss\sd-scripts\library\flux_models.py", line 1083, in forward
    img, txt = block(img=img, txt=txt, vec=vec, pe=pe, txt_attention_mask=txt_attention_mask)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\kohya_ss\sd-scripts\library\flux_models.py", line 740, in forward
    return checkpoint(self._forward, img, txt, vec, pe, txt_attention_mask, use_reentrant=False)
  File "C:\kohya_ss\venv\lib\site-packages\torch\_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py", line 496, in checkpoint
    ret = function(*args, **kwargs)
  File "C:\kohya_ss\sd-scripts\library\flux_models.py", line 689, in _forward
    img_mod1, img_mod2 = self.img_mod(vec)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\kohya_ss\sd-scripts\library\flux_models.py", line 638, in forward
    out = self.lin(nn.functional.silu(vec))[:, None, :].chunk(self.multiplier, dim=-1)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\kohya_ss\venv\lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
steps:   0%|                                                                       | 1/1600 [00:34<15:25:36, 34.73s/it]
Traceback (most recent call last):
  File "C:\Users\elysi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\elysi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1174, in launch_command
    simple_launcher(args)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 769, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/kohya_ss/sd-scripts/flux_train.py', '--config_file', 'C:/train/test.toml']' returned non-zero exit status 1.
```

**Comment by edrevo** [comment]
I think I'm getting an error that is related to the fix in [a9aa526](https://github.com/kohya-ss/sd-scripts/commit/a9aa52658a0d9ba7910a1d1983b650bc9de7153e):

```
Traceback (most recent call last):
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 519, in <module>
[2024-09-28 14:31:27] [INFO] trainer.train(args)
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/train_network.py", line 1208, in train
[2024-09-28 14:31:27] [INFO] self.sample_images(
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 315, in sample_images
[2024-09-28 14:31:27] [INFO] flux_train_utils.sample_images(
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/library/flux_train_utils.py", line 90, in sample_images
[2024-09-28 14:31:27] [INFO] sample_image_inference(
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/library/flux_train_utils.py", line 229, in sample_image_inference
[2024-09-28 14:31:27] [INFO] x = denoise(flux, noise, img_ids, t5_out, txt_ids, l_pooled, timesteps=timesteps, guidance=scale, t5_attn_mask=t5_attn_mask)
[2024-09-28 14:31:27] [INFO] File "/app/fluxgym/sd-scripts/library/flux_train_utils.py", line 316, in denoise
[2024-09-28 14:31:27] [INFO] model.prepare_block_swap_before_forward()
[2024-09-28 14:31:27] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[2024-09-28 14:31:27] [INFO] raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[2024-09-28 14:31:27] [INFO] AttributeError: 'FluxUpperLowerWrapper' object has no attribute 'prepare_block_swap_before_forward'
```

**Comment by edrevo** [comment]
Thanks for the super-quick turnaround!
