### ISSUE TITLE
  --blocks_to_swap is supported on linux?

### ISSUE THREAD

**Issue by al-swaiti** [kohya-ss/sd-scripts#1656]
flux_train_network.py: error: unrecognized arguments:  
Traceback (most recent call last):
  File "/home/abdallah/Desktop/webui/sd-scripts/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/abdallah/Desktop/webui/sd-scripts/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/abdallah/Desktop/webui/sd-scripts/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/home/abdallah/Desktop/webui/sd-scripts/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/abdallah/Desktop/webui/sd-scripts/.venv/bin/python', 'flux_train_network.py', '--pretrained_model_name_or_path', '/home/abdallah/Desktop/webui/ComfyUI/models/diffusion_models/fp8-kaji.safetensors', '--clip_l', '/home/abdallah/Desktop/webui/stable-diffusion-webui/models/text_encoder/clip_l.safetensors', '--ae', '/home/abdallah/Desktop/webui/stable-diffusion-webui/models/VAE/ae.safetensors', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--dataset_config', 'dataset_1024_bs1.toml', '--output_dir', 'path/to/output/dir', '--output_name', 'output-name', '--learning_rate', '5e-5', ' ']' returned non-zero exit status 2.
fish: Unknown command: --max_train_epochs
fish: 
  --max_train_epochs 4 \
  ^~~~~~~~~~~~~~~~~^
fish: Unknown command: --model_prediction_type
fish: 
  --model_prediction_type raw \
  ^~~~~~~~~~~~~~~~~~~~~~^
fish: Unknown command: --blocks_to_swap
fish: 
  --blocks_to_swap 8 \

**Comment by marsatgithub** [comment]
get last version

**Comment by al-swaiti** [comment]
That sad ,,, thank u ,,,, I think this option  good to add for lora training ,,,,
