### ISSUE TITLE
Cannot resume finetuning flux checkpoint - resume option cannot find input path, but input path is correct ###kohya_ss GUI release v24.2.0###

### ISSUE THREAD

**Issue by bolli20000** [kohya-ss/sd-scripts#1692]
Please fix - cannot solve the issue: dir

(venv) D:\flux_train\kohya_ss\venv\Scripts>accelerate launch --dynamo_backend no --gpu_ids 0 --mixed_precision bf16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 D:/flux_train/kohya_ss/sd-scripts/flux_train.py --config_file D:/Bilder/Project_AI/Train/model/config_dreambooth-20241011-001320.toml --resume D:/Bilder/Project_AI/Train/model/LostPlace-Inside-Flux-000120.safetensors
D:\flux_train\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-10-12 23:57:52.785206: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-12 23:57:53.546950: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
D:\flux_train\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
D:\flux_train\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-10-12 23:57:55 INFO     Loading settings from D:/Bilder/Project_AI/Train/model/config_dreambooth-20241011-001320.toml...                                                                  train_util.py:4328
                    INFO     D:/Bilder/Project_AI/Train/model/config_dreambooth-20241011-001320                                                                                                train_util.py:4347
2024-10-12 23:57:55 INFO     Using DreamBooth method.                                                                                                                                           flux_train.py:103
                    INFO     prepare images.                                                                                                                                                   train_util.py:1872
                    INFO     get image size from name of cache files                                                                                                                           train_util.py:1810
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [00:00<00:00, 899.24it/s]
                    INFO     set image size from cache files: 179/179                                                                                                                          train_util.py:1817
                    INFO     found directory D:\Bilder\Project_AI\Train\datasets\LostPlace-Inside_2024\1_Lostplace contains 179 image files                                                    train_util.py:1819
                    INFO     179 train images with repeating.                                                                                                                                  train_util.py:1913
                    INFO     0 reg images.                                                                                                                                                     train_util.py:1916
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                                                                                       train_util.py:1921
                    INFO     [Dataset 0]                                                                                                                                                       config_util.py:570
                               batch_size: 1
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\Bilder\Project_AI\Train\datasets\LostPlace-Inside_2024\1_Lostplace"
                                 image_count: 179
                                 num_repeats: 1
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False,
                                 is_reg: False
                                 class_tokens: Lostplace
                                 caption_extension: .txt

                    INFO     [Dataset 0]                                                                                                                                                       config_util.py:576
                    INFO     loading image sizes.                                                                                                                                               train_util.py:909
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [00:00<?, ?it/s]
                    INFO     make buckets                                                                                                                                                       train_util.py:915
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically /                          train_util.py:932
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                                                                                    train_util.py:961
                    INFO     bucket 0: resolution (832, 1152), count: 1                                                                                                                         train_util.py:966
                    INFO     bucket 1: resolution (832, 1216), count: 9                                                                                                                         train_util.py:966
                    INFO     bucket 2: resolution (1024, 896), count: 2                                                                                                                         train_util.py:966
                    INFO     bucket 3: resolution (1088, 832), count: 1                                                                                                                         train_util.py:966
                    INFO     bucket 4: resolution (1088, 896), count: 1                                                                                                                         train_util.py:966
                    INFO     bucket 5: resolution (1152, 832), count: 3                                                                                                                         train_util.py:966
                    INFO     bucket 6: resolution (1152, 896), count: 1                                                                                                                         train_util.py:966
                    INFO     bucket 7: resolution (1216, 704), count: 1                                                                                                                         train_util.py:966
                    INFO     bucket 8: resolution (1216, 768), count: 5                                                                                                                         train_util.py:966
                    INFO     bucket 9: resolution (1216, 832), count: 146                                                                                                                       train_util.py:966
                    INFO     bucket 10: resolution (1280, 704), count: 1                                                                                                                        train_util.py:966
                    INFO     bucket 11: resolution (1280, 768), count: 3                                                                                                                        train_util.py:966
                    INFO     bucket 12: resolution (1344, 704), count: 2                                                                                                                        train_util.py:966
                    INFO     bucket 13: resolution (1408, 704), count: 1                                                                                                                        train_util.py:966
                    INFO     bucket 14: resolution (1472, 704), count: 2                                                                                                                        train_util.py:966
                    INFO     mean ar error (without repeats): 0.035069617602451975                                                                                                              train_util.py:971
                    INFO     Checking the state dict: Diffusers or BFL, dev or schnell                                                                                                           flux_utils.py:48
                    INFO     prepare accelerator                                                                                                                                                flux_train.py:173
accelerator device: cuda
                    INFO     Building AutoEncoder                                                                                                                                               flux_utils.py:100
                    INFO     Loading state dict from D:/Forge/webui/models/VAE/ae.safetensors                                                                                                   flux_utils.py:105
                    INFO     Loaded AE: <All keys matched successfully>                                                                                                                         flux_utils.py:108
                    INFO     [Dataset 0]                                                                                                                                                       train_util.py:2396
                    INFO     caching latents with caching strategy.                                                                                                                            train_util.py:1017
                    INFO     checking cache validity...                                                                                                                                        train_util.py:1044
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [00:00<00:00, 8137.13it/s]
                    INFO     no latents to cache                                                                                                                                               train_util.py:1087
D:\flux_train\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
2024-10-12 23:57:56 INFO     Building CLIP                                                                                                                                                      flux_utils.py:113
                    INFO     Loading state dict from D:/Forge/webui/models/text_encoder/clip_l.safetensors                                                                                      flux_utils.py:206
                    INFO     Loaded CLIP: <All keys matched successfully>                                                                                                                       flux_utils.py:209
                    INFO     Loading state dict from D:/Forge/webui/models/text_encoder/t5xxl_fp16.safetensors                                                                                  flux_utils.py:254
                    INFO     Loaded T5xxl: <All keys matched successfully>                                                                                                                      flux_utils.py:257
2024-10-12 23:58:01 INFO     [Dataset 0]                                                                                                                                                       train_util.py:2417
                    INFO     caching Text Encoder outputs with caching strategy.                                                                                                               train_util.py:1179
                    INFO     checking cache validity...                                                                                                                                        train_util.py:1185
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [00:00<00:00, 4324.55it/s]
                    INFO     no Text Encoder outputs to cache                                                                                                                                  train_util.py:1207
                    INFO     cache Text Encoder outputs for sample prompt: D:/Bilder/Project_AI/Train/model\sample/prompt.txt                                                                   flux_train.py:236
                    INFO     cache Text Encoder outputs for prompt: lostplace-inside of an abandoned and destroyed cinema, italian style, fire spots, overgrown from the outside, morning Sun   flux_train.py:246
                             shines in through the broken roof, amazing and complex rokokko architecture, broken chairs a piled, very messy old cinema, dark colours and atmosphere
2024-10-12 23:58:02 INFO     cache Text Encoder outputs for prompt:                                                                                                                             flux_train.py:246
                    INFO     Checking the state dict: Diffusers or BFL, dev or schnell                                                                                                           flux_utils.py:48
                    INFO     Building Flux model dev from BFL checkpoint                                                                                                                         flux_utils.py:74
                    INFO     Loading state dict from D:/Forge/webui/models/Stable-diffusion/flux1-dev.safetensors                                                                                flux_utils.py:81
                    INFO     Loaded Flux: <All keys matched successfully>                                                                                                                        flux_utils.py:93
FLUX: Gradient checkpointing enabled. CPU offload: False
                    INFO     enable block swap: blocks_to_swap=10                                                                                                                               flux_train.py:291
number of trainable parameters: 11901408320
prepare optimizer, data loader etc.
                    INFO     use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init': False, 'weight_decay': 0.01}                                          train_util.py:4641
                    WARNING  because max_grad_norm is set, clip_grad_norm is enabled. consider set to 0 /                                                                                      train_util.py:4669
                             max_grad_normが設定されているためclip_grad_normが有効になります。0に設定して無効にしたほうがいいかもしれません
                    WARNING  constant_with_warmup will be good / スケジューラはconstant_with_warmupが良いかもしれません                                                                        train_util.py:4673
enable full bf16 training.
                    INFO     resume training from local state: D:/Bilder/Project_AI/Train/model/LostPlace-Inside-Flux-000120.safetensors                                                       train_util.py:4362
Traceback (most recent call last):
  File "D:\flux_train\kohya_ss\sd-scripts\flux_train.py", line 994, in <module>
    train(args)
  File "D:\flux_train\kohya_ss\sd-scripts\flux_train.py", line 461, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "D:\flux_train\kohya_ss\sd-scripts\library\train_util.py", line 4363, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 3072, in load_state
    raise ValueError(f"Tried to find {input_dir} but folder does not exist")
ValueError: Tried to find D:/Bilder/Project_AI/Train/model/LostPlace-Inside-Flux-000120.safetensors but folder does not exist
Traceback (most recent call last):
  File "C:\Users\sabot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sabot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\flux_train\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\flux_train\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/flux_train/kohya_ss/sd-scripts/flux_train.py', '--config_file', 'D:/Bilder/Project_AI/Train/model/config_dreambooth-20241011-001320.toml', '--resume', 'D:/Bilder/Project_AI/Train/model/LostPlace-Inside-Flux-000120.safetensors']' returned non-zero exit status 1.

(venv) D:\flux_train\kohya_ss\venv\Scripts>

**Comment by bolli20000** [comment]
Thanks @kohya-ss - but this leads to fthe following result: 

D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py:212: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(input_model_file, map_location=map_location)
Traceback (most recent call last):
  File "D:\flux_train\kohya_ss\sd-scripts\flux_train.py", line 994, in <module>
    train(args)
  File "D:\flux_train\kohya_ss\sd-scripts\flux_train.py", line 461, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "D:\flux_train\kohya_ss\sd-scripts\library\train_util.py", line 4363, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 3145, in load_state
    override_attributes = load_accelerator_state(
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py", line 212, in load_accelerator_state
    state_dict = torch.load(input_model_file, map_location=map_location)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Bilder\\Project_AI\\Train\\model\\pytorch_model.bin'
Traceback (most recent call last):
  File "C:\Users\sabot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sabot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\flux_train\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\flux_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\flux_train\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/flux_train/kohya_ss/sd-scripts/flux_train.py', '--config_file', 'D:/Bilder/Project_AI/Train/model/config_dreambooth-20241011-001320.toml', '--resume', 'D:/Bilder/Project_AI/Train/model']' returned non-zero exit status 1.

**Comment by AbstractEyes** [comment]
I'm having a nearly identical problem.

**Comment by AbstractEyes** [comment]
[rank2]:[W1014 03:47:39.789025589 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).                                  | 1061/13485 [09:20<1:49:30,  1.89it/s]
[rank2]: Traceback (most recent call last):                                                                                                            | 1060/13485 [09:20<1:44:20,  1.98it/s]
[rank2]:   File "/workspace/kohya_ss/sd-scripts/flux_train_network.py", line 519, in <module>                                                          | 1059/13485 [09:19<1:42:57,  2.01it/s]
[rank2]:     trainer.train(args)                                                                                                                       | 1058/13485 [09:19<1:17:41,  2.67it/s]
[rank2]:   File "/workspace/kohya_ss/sd-scripts/train_network.py", line 392, in train                                                                  | 1057/13485 [09:18<1:27:35,  2.36it/s]
[rank2]:     accelerator.wait_for_everyone()                                                                                                           | 1056/13485 [09:18<1:36:31,  2.15it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2564, in wait_for_everyone                     | 1055/13485 [09:17<3:27:04,  1.00it/s]
[rank2]:     wait_for_everyone()                                                                                                                       | 1054/13485 [09:16<3:01:39,  1.14it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/utils/other.py", line 138, in wait_for_everyone                      | 1053/13485 [09:15<1:31:20,  2.27it/s]
[rank2]:     PartialState().wait_for_everyone()                                                                                                        | 1052/13485 [09:15<1:37:55,  2.12it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/state.py", line 374, in wait_for_everyone                            | 1051/13485 [09:14<1:26:02,  2.41it/s]
[rank2]:     torch.distributed.barrier()                                                                                                               | 1050/13485 [09:14<1:36:50,  2.14it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper                           | 959/13485 [08:21<1:38:13,  2.13it/s]
[rank2]:     return func(*args, **kwargs)                                                                                                               | 958/13485 [08:21<1:32:54,  2.25it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier                    | 957/13485 [08:20<1:23:12,  2.51it/s]
[rank2]:     work = default_pg.barrier(opts=opts)                                                                                                       | 956/13485 [08:20<2:10:22,  1.60it/s]
[rank2]: torch.distributed.DistBackendError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Sock
et Timeout������                                                                                                                                        | 954/13485 [08:19<1:50:13,  1.89it/s]
[rank2]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):                                      | 953/13485 [08:18<2:33:24,  1.36it/s]
[rank2]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7d0e53c9af86 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libc10.so)1:35:58,  2.18it/s]
[rank2]: frame #1: <unknown function> + 0x164b9c5 (0x7d0e3b24b9c5 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)   | 951/13485 [08:17<1:34:37,  2.21it/s]
[rank2]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7d0e3f8fbd92 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so):34<2:08:14,  1.64it/s]
[rank2]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7d0e3f8fcf81 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)07:34<1:34:12,  2.23it/s]
[rank2]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)33<1:57:10,  1.79it/s]
[rank2]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)33<1:19:30,  2.65it/s]
[rank2]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)32<1:27:32,  2.40it/s]
[rank2]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)32<1:38:03,  2.14it/s]
[rank2]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7d0e0618ef8f in /workspace/kohya_ss/venv/lib/python3.10/site-packages
/torch/lib/libtorch_cuda.so)                                                                                                                            | 863/13485 [07:31<1:26:35,  2.43it/s]
[rank2]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7d0e0619ad6c in /workspace/kohya_ss/venv/lib/python3.10/site-pac
kages/torch/lib/libtorch_cuda.so)                                                                                                                       | 861/13485 [07:30<2:23:23,  1.47it/s]
[rank2]: frame #10: <unknown function> + 0x11a31cf (0x7d0e061a31cf in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so) | 860/13485 [07:29<1:18:32,  2.68it/s]
[rank2]: frame #11: c10d::ProcessGroupNCCL::allreduce_impl(at::Tensor&, c10d::AllreduceOptions const&) + 0x10 (0x7d0e061a4600 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/l
ib/libtorch_cuda.so)                                                                                                                                    | 777/13485 [06:47<1:39:20,  2.13it/s]
[rank2]: frame #12: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x69c (0x7d0e061b170c in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)]
[rank2]: frame #13: <unknown function> + 0x5ca4202 (0x7d0e3f8a4202 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 775/13485 [06:46<1:37:21,  2.18it/s]
[rank2]: frame #14: <unknown function> + 0x5caea05 (0x7d0e3f8aea05 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 774/13485 [06:46<1:38:40,  2.15it/s]
[rank2]: frame #15: <unknown function> + 0x52d0c1b (0x7d0e3eed0c1b in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 773/13485 [06:45<2:02:21,  1.73it/s]
[rank2]: frame #16: <unknown function> + 0x52ce494 (0x7d0e3eece494 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 772/13485 [06:45<1:38:03,  2.16it/s]
[rank2]: frame #17: <unknown function> + 0x1ace5a8 (0x7d0e3b6ce5a8 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 771/13485 [06:44<1:29:22,  2.37it/s]
[rank2]: frame #18: <unknown function> + 0x5cb8974 (0x7d0e3f8b8974 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 770/13485 [06:44<1:22:42,  2.56it/s]
[rank2]: frame #19: <unknown function> + 0x5cb9705 (0x7d0e3f8b9705 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 769/13485 [06:43<1:55:56,  1.83it/s]
[rank2]: frame #20: <unknown function> + 0xdb0b68 (0x7d0e52bb0b68 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)| 768/13485 [06:43<1:37:43,  2.17it/s]
[rank2]: frame #21: <unknown function> + 0x4b00e4 (0x7d0e522b00e4 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)| 687/13485 [06:01<2:34:00,  1.38it/s]
[rank2]: frame #22: <unknown function> + 0x15cb2e (0x6518fc73cb2e in /workspace/kohya_ss/venv/bin/python)                                               | 686/13485 [06:00<1:42:44,  2.08it/s]
[rank2]: frame #23: _PyObject_MakeTpCall + 0x25b (0x6518fc7332db in /workspace/kohya_ss/venv/bin/python)                                                | 685/13485 [06:00<1:48:26,  1.97it/s]
[rank2]: frame #24: <unknown function> + 0x16b55b (0x6518fc74b55b in /workspace/kohya_ss/venv/bin/python)                                               | 684/13485 [05:59<2:51:43,  1.24it/s]
[rank2]: frame #25: _PyEval_EvalFrameDefault + 0x1983 (0x6518fc726b93 in /workspace/kohya_ss/venv/bin/python)                                           | 683/13485 [05:59<1:20:28,  2.65it/s]
[rank2]: frame #26: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)                                               | 682/13485 [05:58<1:53:33,  1.88it/s]
[rank2]: frame #27: _PyEval_EvalFrameDefault + 0x285e (0x6518fc727a6e in /workspace/kohya_ss/venv/bin/python)                                           | 681/13485 [05:58<1:49:31,  1.95it/s]
[rank2]: frame #28: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)                                               | 680/13485 [05:57<1:37:17,  2.19it/s]
[rank2]: frame #29: _PyEval_EvalFrameDefault + 0x613a (0x6518fc72b34a in /workspace/kohya_ss/venv/bin/python)                                           | 679/13485 [05:57<1:35:03,  2.25it/s]
[rank2]: frame #30: <unknown function> + 0x16b281 (0x6518fc74b281 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #31: _PyEval_EvalFrameDefault + 0x613a (0x6518fc72b34a in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #32: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #33: _PyEval_EvalFrameDefault + 0x6bc (0x6518fc7258cc in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #34: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #35: _PyEval_EvalFrameDefault + 0x8ab (0x6518fc725abb in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #36: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #37: _PyEval_EvalFrameDefault + 0x8ab (0x6518fc725abb in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #38: <unknown function> + 0x142016 (0x6518fc722016 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #39: PyEval_EvalCode + 0x86 (0x6518fc8178b6 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #40: <unknown function> + 0x262918 (0x6518fc842918 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #41: <unknown function> + 0x25c1db (0x6518fc83c1db in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #42: <unknown function> + 0x262665 (0x6518fc842665 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #43: _PyRun_SimpleFileObject + 0x1a8 (0x6518fc841b48 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #44: _PyRun_AnyFileObject + 0x43 (0x6518fc841793 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #45: Py_RunMain + 0x2be (0x6518fc8342ce in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #46: Py_BytesMain + 0x2d (0x6518fc80a70d in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #47: <unknown function> + 0x29d90 (0x7d0e548b6d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #48: __libc_start_main + 0x80 (0x7d0e548b6e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #49: _start + 0x25 (0x6518fc80a605 in /workspace/kohya_ss/venv/bin/python)
[rank2]: . This may indicate a possible application crash on rank 0 or a network set up issue.
  8%|�������������                                                                                                                                     | 1132/13485 [09:59<1:34:01,  2.19it/s]W1014 03:47:41.144000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7562 closing signal SIGTERM
W1014 03:47:41.147000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7563 closing signal SIGTERM
W1014 03:47:41.147000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7565 closing signal SIGTERM
E1014 03:47:41.614000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 2 (pid: 7564) of binary: /workspace/kohya_ss/venv/bin/python
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    multi_gpu_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by bolli20000** [comment]
I retrained on the scratch with checked "Save training state", but seems not to save any training state in any *-state directory, hmm...

![image](https://github.com/user-attachments/assets/bc057c7a-b785-4a6c-acca-5a894980a145)

**Comment by bolli20000** [comment]
Hmm after every trained epoch ? Or after every "Save every N epochs" ?

**Comment by bolli20000** [comment]
Let me wait still 6 Epochs to train, after I will see the wished result...

**Comment by bolli20000** [comment]
Great, works - -state directory was created. Thank you. I think issue is no issue and can be closed. Thank you kohya_ss for the perfect support.

Best Bolli

**Comment by bolli20000** [comment]
No luck, today I resumed a training from last saved state. But think training startet again from 0 ? 

![image](https://github.com/user-attachments/assets/2a5d0bd4-7dee-4097-8100-96844e0586e0)

**Comment by bolli20000** [comment]
Thank you, i.e. the training will restart on the saved state correctly ? Just the epoch counter starting at 0 is to ignore and train just #epochs - #epochs(until saved state) ?
