### ISSUE TITLE
ValueError：Cannot load xxxx from flux/vae because the following keys are missing

### ISSUE THREAD

**Issue by JingZz7** [kohya-ss/sd-scripts#1701]
This is my error report：
`
Loading pipeline components...:   0%|                                                                                                                                                            | 0/3 [00:00<?, ?it/s]accelerator device: cuda:6
The config attributes {'latents_mean': None, 'latents_std': None, 'mid_block_add_attention': True, 'shift_factor': 0.1159, 'use_post_quant_conv': False, 'use_quant_conv': False} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:   0%|                                                                                                                                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1117, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 236, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 103, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4387, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4349, in _load_target_model
accelerator device: cuda:2
    pipe = StableDiffusionPipeline.from_pretrained(name_or_path, tokenizer=None, safety_checker=None)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 805, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.autoencoders.autoencoder_kl.AutoencoderKL'> from /home_host/zj/flux/ai-modelscope/flux___1-dev/vae because the following keys are missing:
 quant_conv.bias, post_quant_conv.weight, quant_conv.weight, post_quant_conv.bias.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
[ERROR] 2024-10-16-10:14:27 (PID:3362, Device:0, RankID:0) ERR99999 UNKNOWN application exception
`

Below is the model I used to train：
[https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main](url)

This is my executed command：
`
accelerate launch --num_cpu_threads_per_process 1 train_network.py \
--pretrained_model_name_or_path="/home_host/zj/flux/ai-modelscope/flux___1-dev" \
--dataset_config="/home/ma-user/sd-scripts/sd-scripts/train_first.toml" \
--output_dir="/home/ma-user/sd-scripts/sd-scripts/output" \
--output_name="output" \
--save_model_as=safetenpip isors \
--prior_loss_weight=1.0 \
--max_train_steps=3000 \
--learning_rate=1e-4 \
--optimizer_type="AdamW" \
--xformers \
--mixed_precision="fp16" \
--cache_latents \
--save_every_n_epochs=3000 \
--network_module=networks.lora
`

**How should I solve this problem? Thank you in advance for your answers**

**Comment by JingZz7** [comment]
The error message is not very clear. This is the message I copied again：
`
The config attributes {'latents_mean': None, 'latents_std': None, 'mid_block_add_attention': True, 'shift_factor': 0.1159, 'use_post_quant_conv': False, 'use_quant_conv': False} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:   0%|                                                                                                                                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1117, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 236, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 103, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4387, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4349, in _load_target_model
accelerator device: cuda:2
    pipe = StableDiffusionPipeline.from_pretrained(name_or_path, tokenizer=None, safety_checker=None)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 805, in from_pretrained
    raise ValueError(

ValueError: Cannot load <class 'diffusers.models.autoencoders.autoencoder_kl.AutoencoderKL'> from /home_host/zj/flux/ai-modelscope/flux___1-dev/vae because the following keys are missing:
 quant_conv.bias, post_quant_conv.weight, quant_conv.weight, post_quant_conv.bias.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
[ERROR] 2024-10-16-10:14:27 (PID:3362, Device:0, RankID:0) ERR99999 UNKNOWN application exception
`

**Comment by JingZz7** [comment]
The error message is not very clear. This is the message I copied again：
```
The config attributes {'latents_mean': None, 'latents_std': None, 'mid_block_add_attention': True, 'shift_factor': 0.1159, 'use_post_quant_conv': False, 'use_quant_conv': False} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:   0%|                                                                                                                                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1117, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 236, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 103, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4387, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/home/ma-user/sd-scripts/sd-scripts/library/train_util.py", line 4349, in _load_target_model
accelerator device: cuda:2
    pipe = StableDiffusionPipeline.from_pretrained(name_or_path, tokenizer=None, safety_checker=None)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 805, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.autoencoders.autoencoder_kl.AutoencoderKL'> from /home_host/zj/flux/ai-modelscope/flux___1-dev/vae because the following keys are missing:
 quant_conv.bias, post_quant_conv.weight, quant_conv.weight, post_quant_conv.bias.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
[ERROR] 2024-10-16-10:14:27 (PID:3362, Device:0, RankID:0) ERR99999 UNKNOWN application exception
```

**Comment by JingZz7** [comment]
```
                    INFO     text_encoder [1] dtype: torch.float16, device: cpu                                                                                                                  train_network.py:1066
                    INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
                    INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:29 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:29 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:29 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:29 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
2024-10-17 14:59:30 INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                        train_util.py:706
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
        encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]

  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'

Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_train_network.py", line 520, in <module>
    trainer.train(args)
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in train
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
  File "/home/ma-user/sd-scripts/sd-scripts/train_network.py", line 1150, in <listcomp>
    encoded_text_encoder_conds = [c.to(weight_dtype) for c in encoded_text_encoder_conds]
AttributeError: 'NoneType' object has no attribute 'to'
[ERROR] 2024-10-17-14:59:34 (PID:48331, Device:2, RankID:2) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:34 (PID:48334, Device:5, RankID:5) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:34 (PID:48330, Device:1, RankID:1) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:34 (PID:48332, Device:3, RankID:3) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:34 (PID:48329, Device:0, RankID:0) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:34 (PID:48335, Device:6, RankID:6) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:35 (PID:48333, Device:4, RankID:4) ERR99999 UNKNOWN application exception
[ERROR] 2024-10-17-14:59:35 (PID:48336, Device:7, RankID:7) ERR99999 UNKNOWN application exception
steps:   0%|                                                                                                                                                                                  | 0/100 [00:12<?, ?it/s]
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48329 closing signal SIGTERM
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48330 closing signal SIGTERM
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48331 closing signal SIGTERM
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48333 closing signal SIGTERM
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48334 closing signal SIGTERM
[2024-10-17 14:59:39,192] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48335 closing signal SIGTERM
[2024-10-17 14:59:39,193] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48336 closing signal SIGTERM
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[2024-10-17 14:59:42,926] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 3 (pid: 48332) of binary: /home/ma-user/anaconda3/envs/PyTorch-2.2.0/bin/python3.1
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    multi_gpu_launcher(args)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
flux_train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-17_14:59:39
  host      : c052f30eeb6d
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 48332)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[ERROR] 2024-10-17-14:59:42 (PID:48134, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
```

**Hello,I user `flux_train_network.py`, but more errors are reported during training, below is the training script I use**

```
  1 accelerate launch  --mixed_precision bf16 --num_cpu_threads_per_process 1 flux_train_network.py \
  2 --pretrained_model_name_or_path /home_host/zj/flux/ai-modelscope/flux___1-dev/flux1-dev.safetensors \
  3 --ae /home_host/zj/flux/ai-modelscope/flux___1-dev/ae.safetensors \
  4 --clip_l /home_host/zj/docker/ComfyUI/models/clip/text_encoders/clip_l.safetensors \
  5 --t5xxl /home_host/zj/docker/ComfyUI/models/clip/text_encoders/t5xxl_fp16.safetensors \
  6 --cache_latents_to_disk \
  7 --save_model_as safetensors \
  8 --sdpa \
  9 --persistent_data_loader_workers \
 10 --max_data_loader_n_workers 2 \
 11 --seed 42 \
 12 --gradient_checkpointing \
 13 --mixed_precision fp16 \
 14 --save_precision fp16 \
 15 --network_module networks.lora_flux \
 16 --network_dim 4 \
 17 --optimizer_type adamw \
 18 --learning_rate 1e-4 \
 19 --cache_text_encoder_outputs \
 20 --cache_text_encoder_outputs_to_disk \
 21 --full_fp16 \
 22 --highvram \
 23 --max_train_epochs 4 \
 24 --save_every_n_epochs 1 \
 25 --dataset_config "/home/ma-user/sd-scripts/sd-scripts/flux_train.toml" \
 26 --output_dir /home/ma-user/sd-scripts/sd-scripts/output \
 27 --output_name "flux_lora_output" \
 28 --timestep_sampling shift \
 29 --discrete_flow_shift 3.1582 \
 30 --model_prediction_type raw \
 31 --guidance_scale 1.0
```
How should I solve this problem? Thank you in advance for your answers

**Comment by JingZz7** [comment]
> > 请使用`flux_train_network.py`而不是`train_network.py`FLUX.1 LoRA 训练。
> 
> 在哪里`flux_train_network.py`？我找不到！

You should switch to the branch of `sd3`

**Comment by JingZz7** [comment]
> Please use `flux_train_network.py` instead of `train_network.py` for FLUX.1 LoRA training.

```
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
get_preferred_device() -> cpu
2024-10-18 09:46:42 INFO     Dtypes for clip_l, t5xxl, ae, flux: torch.float16, torch.float16, torch.float16, torch.float16                                                              flux_minimal_inference.py:431
                    INFO     Loading clip_l from /home_host/zj/docker/ComfyUI/models/clip/text_encoders/clip_l.safetensors...                                                            flux_minimal_inference.py:442
                    INFO     Building CLIP                                                                                                                                                           flux_utils.py:166
                    INFO     Loading state dict from /home_host/zj/docker/ComfyUI/models/clip/text_encoders/clip_l.safetensors                                                                       flux_utils.py:259
                    INFO     Loaded CLIP: <All keys matched successfully>                                                                                                                            flux_utils.py:262
                    INFO     Loading t5xxl from /home_host/zj/docker/ComfyUI/models/clip/text_encoders/t5xxl_fp16.safetensors...                                                         flux_minimal_inference.py:446
                    INFO     Loading state dict from /home_host/zj/docker/ComfyUI/models/clip/text_encoders/t5xxl_fp16.safetensors                                                                   flux_utils.py:307
                    INFO     Loaded T5xxl: <All keys matched successfully>                                                                                                                           flux_utils.py:310
                    INFO     Checking the state dict: Diffusers or BFL, dev or schnell                                                                                                                flux_utils.py:63
Traceback (most recent call last):
  File "/home/ma-user/sd-scripts/sd-scripts/flux_minimal_inference.py", line 456, in <module>
    is_schnell, model = flux_utils.load_flow_model(args.ckpt_path, None, loading_device)
  File "/home/ma-user/sd-scripts/sd-scripts/library/flux_utils.py", line 113, in load_flow_model
    is_diffusers, is_schnell, (num_double_blocks, num_single_blocks), ckpt_paths = analyze_checkpoint_state(ckpt_path)
  File "/home/ma-user/sd-scripts/sd-scripts/library/flux_utils.py", line 82, in analyze_checkpoint_state
    max_double_block_index = max(
ValueError: max() arg is an empty sequence
[ERROR] 2024-10-18-09:46:42 (PID:63330, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.2.0/lib/python3.10/tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpy5x450kd'>
  _warnings.warn(warn_message, ResourceWarning)
```
**When I use `flux_minimal_inference.py` to infer the model I have trained, the above error occurs, but I don't know how to troubleshoot. Can you help me? Thank you very much. The following is the startup script**

```
  1 python flux_minimal_inference.py \
  2 --ckpt /home/ma-user/sd-scripts/sd-scripts/output/flux_lora_output.safetensors \
  3 --clip_l /home_host/zj/docker/ComfyUI/models/clip/text_encoders/clip_l.safetensors \
  4 --t5xxl /home_host/zj/docker/ComfyUI/models/clip/text_encoders/t5xxl_fp16.safetensors \
  5 --ae /home_host/zj/flux/ai-modelscope/flux___1-dev/ae.safetensors \
  6 --dtype fp16 \
  7 --prompt "I want an image of a beautiful natural woman on a mountaintop with an oversized white hoodie and biker shorts on for a hoodie mockup" \
  8 --out /home/ma-user/sd-scripts/sd-scripts/infer_output \
  9 --seed 1 \
 10 --flux_dtype fp16 \
 11 --offload
```
