### ISSUE TITLE
--gpu_ids 0 lose efficacy after pull

### ISSUE THREAD

**Issue by jinwei1660** [kohya-ss/sd-scripts#1778]
accelerate launch     --mixed_precision bf16     --num_cpu_threads_per_process 1     --num_processes 1     --gpu_ids 0     sd-scripts/flux_train_network.py     --pretrained_model_name_or_path "D:\pinokio\api\ajfluxlora\models\unet\bdsqlsz\flux1-dev2pro-single\flux1-dev2pro.safetensors"     --clip_l "D:\pinokio\api\ajfluxlora\models\clip\clip_l.safetensors"     --t5xxl "D:\pinokio\api\ajfluxlora\models\clip\t5xxl_fp16.safetensors"     --ae "D:\pinokio\api\ajfluxlora\models\vae\ae.sft"     --cache_latents_to_disk     --save_model_as safetensors     --sdpa --persistent_data_loader_workers     --max_data_loader_n_workers 32     --seed 42     --gradient_checkpointing     --mixed_precision bf16     --save_precision bf16     --network_module networks.lora_flux     --network_dim 128     --optimizer_type adamw8bit --sample_prompts="D:\pinokio\api\ajfluxlora\outputs\dim-test\sample_prompts.txt" --sample_every_n_steps="49"     --learning_rate 1e-4     --cache_text_encoder_outputs     --cache_text_encoder_outputs_to_disk     --fp8_base     --highvram     --max_train_epochs 2     --save_every_n_epochs 1     --dataset_config "D:\pinokio\api\ajfluxlora\outputs\dim-test\dataset.toml"     --output_dir "D:\pinokio\api\ajfluxlora\outputs\dim-test"     --output_name dim-test     --timestep_sampling shift     --discrete_flow_shift 3.1582     --model_prediction_type raw     --guidance_scale 1     --loss_type l2
Traceback (most recent call last):
  File "d:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\pinokio\api\ajfluxlora\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "d:\pinokio\api\ajfluxlora\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "d:\pinokio\api\ajfluxlora\env\lib\site-packages\accelerate\commands\launch.py", line 1084, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "d:\pinokio\api\ajfluxlora\env\lib\site-packages\accelerate\commands\launch.py", line 957, in _validate_launch_command
    raise ValueError(
ValueError: Less than two GPU ids were configured and tried to run on on multiple GPUs. Please ensure at least two are specified for `--gpu_ids`, or use `--gpu_ids='all'`.

This command was usable before, but after the update, it is not possible to specify a specific card for training

**Comment by WXT-NO1** [comment]
Hi, have you solved this problem? I also met the problem.

**Comment by WXT-NO1** [comment]
I found the reason. If we have two GPUs, even if we set multi_gpu to false, the code will automatically detect multiple GPUs and change multi_gpu to true. Therefore, we need to modify the part of the code that automatically detects hardware and sets multi_gpu. The code is located in venv\Lib\site-packages\accelerate\commands\launch.py

**Comment by kohya-ss** [comment]
Although I haven't tested it, setting the environment variable CUDA_VISIBLE_DEVICES may help.
