### ISSUE TITLE
Can't load tokenizer for 'openai/clip-vit-large-patch14'

### ISSUE THREAD

**Issue by hotdogarea** [kohya-ss/sd-scripts#1792]
我在用kohya_ss进行flux全量微调时，开启训练总会提示如下
Traceback (most recent call last):
  File "/root/kohya_ss/sd-scripts/flux_train.py", line 998, in <module>
    train(args)
  File "/root/kohya_ss/sd-scripts/flux_train.py", line 209, in train
    flux_tokenize_strategy = strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length)
  File "/root/kohya_ss/sd-scripts/library/strategy_flux.py", line 26, in __init__
    self.clip_l = self._load_tokenizer(CLIPTokenizer, CLIP_L_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
  File "/root/kohya_ss/sd-scripts/library/strategy_base.py", line 65, in _load_tokenizer
    tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/root/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/root/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/kohya_ss/venv/bin/python3.10', '/root/kohya_ss/sd-scripts/flux_train.py', '--config_file', '/root/kohya_ss/outputs/model/config_dreambooth-20241118-062914.toml']' returned non-zero exit status 1.

在strategy.py代码中我看到如下配置：
CLIP_L_TOKENIZER_ID = "openai/clip-vit-large-patch14"
T5_XXL_TOKENIZER_ID = "google/t5-v1_1-xxl"
class FluxTokenizeStrategy(TokenizeStrategy):
    def __init__(self, t5xxl_max_length: int = 512, tokenizer_cache_dir: Optional[str] = None) -> None:
        self.t5xxl_max_length = t5xxl_max_length
        self.clip_l = self._load_tokenizer(CLIPTokenizer, CLIP_L_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
        self.t5xxl = self._load_tokenizer(T5TokenizerFast, T5_XXL_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
![image](https://github.com/user-attachments/assets/7dc33e97-6923-47b6-b727-61c4a771db1f)

但是在前端页面中我已经指定了flux要用的clip_l和t5的模型文件路径，我明白这里需要的是整个仓库，但是这两个仓库太大了，goole/t5更是有近50G，部署在云服务器上下载速度慢不说 经常容易断。这里还有其他配置方式吗？必须得去load tokenizer for 'openai/clip-vit-large-patch14' 和 goole/t5 吗？

**Comment by hotdogarea** [comment]
我在克隆了https://huggingface.co/google/t5-v1_1-xxl/tree/main
以及https://huggingface.co/openai/clip-vit-large-patch14两个仓库到本地后，但我并没有下载里面大的模型文件，模型文件一个都没下载。
然后在strategy_flux.py中 将加载的地址改为了本地，之后就能成功训练了。
CLIP_L_TOKENIZER_ID = "/root/kohya_ss/clip-vit-large-patch14"
T5_XXL_TOKENIZER_ID = "/root/kohya_ss/t5-v1_1-xxl"
