### ISSUE TITLE
Loha on flux, error: LycorisNetwork object has no attribute train_t5xxl

### ISSUE THREAD

**Issue by heinrichI** [kohya-ss/sd-scripts#1810]
I try train Lycoris loha on flux.
Command:
_accelerate launch ^
  --num_cpu_threads_per_process 1 ^
  sd-scripts/flux_train_network.py ^
  --pretrained_model_name_or_path "flux1-dev-fp8.safetensors" ^
  --clip_l "clip_l.safetensors" ^
  --t5xxl "t5xxl_fp16.safetensors" ^
  --ae "ae.sft" ^
  --cache_latents_to_disk ^
  --cache_text_encoder_outputs ^
  --cache_text_encoder_outputs_to_disk ^
  --save_model_as safetensors ^
  --sdpa --persistent_data_loader_workers ^
  --max_data_loader_n_workers 2 ^
  --seed 42 ^
  --gradient_checkpointing ^
  --mixed_precision bf16 ^
  --save_precision bf16 ^
  --network_module lycoris.kohya ^
  --network_dim 32 ^
  --network_alpha 1 ^
  --network_args "conv_dim=32" "conv_alpha=1" "algo=loha" ^
  --optimizer_type adafactor  ^
  --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"  ^
  --lr_scheduler constant_with_warmup ^
  --learning_rate 5e-4 ^
  --network_train_unet_only ^
  --fp8_base_unet ^
  --highvram ^
  --max_train_epochs 100 ^
  --save_every_n_epochs 1 ^
  --dataset_config "datasetMe.toml" ^
  --output_dir "outputs" ^
  --output_name me5e4AdaFactorLycoris ^
  --timestep_sampling shift ^
  --discrete_flow_shift 3.1582 ^
  --model_prediction_type raw ^
  --guidance_scale 1 ^
  --loss_type l2 ^
  --sample_every_n_epochs 1 ^
  --sample_prompts "MePromtSmall.txt" ^
  --sample_sampler "euler_a" ^
  --save_state ^
  --save_state_on_train_end ^
  --logging_dir ./logs --log_with tensorboard --log_tracker_name me5e4AdaFactorLycoris_

but i have error:
Traceback (most recent call last):
  File "\sd-scripts\flux_train_network.py", line 574, in <module>
    trainer.train(args)
  File "\sd-scripts\train_network.py", line 475, in train
    self.post_process_network(args, accelerator, network, text_encoders, unet)
  File "\sd-scripts\flux_train_network.py", line 156, in post_process_network
    self.train_t5xxl = network.train_t5xxl
  File "\venv\lib\site-packages\torch\nn\modules\module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'LycorisNetwork' object has no attribute 'train_t5xxl'
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File \venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by heinrichI** [comment]
I install old LyCORIS.
