### ISSUE TITLE
failing to train LORA and getting these errors ( libcudart.so not found , 'WindowsPath' is not iterable) 

### ISSUE THREAD

**Issue by TaimaniNTR** [kohya-ss/sd-scripts#195]
hi, this is my 3rd clean install to kohya_ss with all the requirements but still having the same problem...
i have automatic 1111 stable diffusion with dreambooth and using it to train a LORA without any problems because i have everything installed on my pc but i want to use kohya_ss because its simpler and faster but im getting this error

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
File "D:\Kohya\kohya_ss\train_db.py", line 346, in
train(args)
File "D:\Kohya\kohya_ss\train_db.py", line 122, in train
import bitsandbytes as bnb
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes_init_.py", line 6, in
from .autograd._functions import (
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd_functions.py", line 5, in
import bitsandbytes.functional as F
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in
from .cextension import COMPILED_WITH_CUDA, lib
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 41, in
lib = CUDALibrary_Singleton.get_instance().lib
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
cls.instance.initialize()
File "D:\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
self.lib = ct.cdll.LoadLibrary(binary_path)
File "C:\Users\Lord\AppData\Local\Programs\Python\Python310\lib\ctypes_init.py", line 452, in LoadLibrary
return self.dlltype(name)
File "C:\Users\Lord\AppData\Local\Programs\Python\Python310\lib\ctypes_init.py", line 364, in init
if '/' in name or '\' in name:

TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
File "C:\Users\Lord\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Lord\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "D:\Kohya\kohya_ss\venv\Scripts\accelerate.exe_main.py", line 7, in
File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
args.func(args)
File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
simple_launcher(args)
File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

was hoping if someone can help me with this.

**Comment by TaimaniNTR** [comment]
and what is the bitsandbytes_windows ? xD

i run the command in cmd but says "cp" is not recognized so i changed it to "copy" and it did nothing 
so i really do not know how to execute this command even tho it should be done automatically during the installation cuz its a part of it yet from what i understand "cp" is not meant for windows

**Comment by TaimaniNTR** [comment]
PowerShell gives the same error as cmd
but the manual copy helped, thank you.
