### ISSUE TITLE
Folder preparation utility duplicates folders and their contents infinitely

### ISSUE THREAD

**Issue by User-Input** [kohya-ss/sd-scripts#225]
Ran the folder preparation utility twice to the same directory "M:\AiGen\Kohya\kohya_ss\SAMPLE IMAGES\Gura"
This is what the folder looked like the first time I ran the tool.
![github](https://user-images.githubusercontent.com/114333816/221076848-47374677-e282-497a-b066-80717133b4c7.png)

I added the training data to the image folder (about 22 images) and then ran the tool again because I forgot to add the regularization folder.
And the result was infinite dupes of the img folder and all of its data
![github2](https://user-images.githubusercontent.com/114333816/221079087-135011e8-f5de-4bab-a1e3-6be950271ef0.png)

Log Data
```
Copy M:/AiGen/Kohya/kohya_ss/SAMPLE IMAGES/Gura to M:/AiGen/Kohya/kohya_ss/SAMPLE IMAGES/Gura\img/40_gura 1girl...
Traceback (most recent call last):
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "M:\AiGen\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "M:\AiGen\Kohya\kohya_ss\library\dreambooth_folder_creation_gui.py", line 69, in dreambooth_folder_preparation
    shutil.copytree(util_training_images_dir_input, training_dir)
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 494, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 494, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
```
The last bit of the message repeats for quite a while until...
```
File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 498, in _copytree
    copy_function(srcobj, dstname)
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "M:\AiGen\Kohya\Python3.10.6\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I assume this is due to a symlink loop

**Comment by bmaltais** [comment]
Yeah... I need to track this one down. It happened to me a few times and I have yet to spend the time understanding why... must be a logic issue with the code. Will see if I can figure out what it is and fix it for good.

**Comment by User-Input** [comment]
Late reply, but you are correct, thank you

**Comment by hurleytom** [comment]
I had this same problem. It was caused by the output folder being inside the input folder. This caused a loop. Changing the output folder to be on the same directory level as the input folder resolved the issue.

**Comment by Dekadinious** [comment]
I had this same problem, but it was caused by the output folder existing before running the preparation. After some fighting I was able to remove it and try again, and it worked.

**Comment by bmaltais** [comment]
Let me update the code so it does not happen again.
