### ISSUE TITLE
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) and returned non-zero exit status 1

### ISSUE THREAD

**Issue by HomePie03** [kohya-ss/sd-scripts#249]
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Traceback (most recent call last):
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\dreambooth_gui.py", line 213, in open_configuration
    my_data = update_optimizer(my_data)
UnboundLocalError: local variable 'my_data' referenced before assignment
Loading config...
Folder 20_cst girl: 320 steps
max_train_steps = 160
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="C:/Users/stabl/Downloads/ACertainty.ckpt" --train_data_dir="C:/Users/stabl/Downloads/lora1/sozai" --resolution=512,512 --output_dir="C:/Users/stabl/Downloads/lora1/output" --logging_dir="C:/Users/stabl/Desktop/kohya" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="cst1" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="160" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers
prepare tokenizer
Use DreamBooth method.
Traceback (most recent call last):
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\train_network.py", line 61, in train
    train_dataset = DreamBoothDataset(args.train_batch_size, args.train_data_dir, args.reg_data_dir,
TypeError: DreamBoothDataset.__init__() takes 13 positional arguments but 21 were given
Traceback (most recent call last):
  File "C:\Users\stabl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\stabl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\stabl\Desktop\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\stabl\\Desktop\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/Users/stabl/Downloads/ACertainty.ckpt', '--train_data_dir=C:/Users/stabl/Downloads/lora1/sozai', '--resolution=512,512', '--output_dir=C:/Users/stabl/Downloads/lora1/output', '--logging_dir=C:/Users/stabl/Desktop/kohya', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=cst1', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=160', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers']' returned non-zero exit status 1.

I have tried the various methods posted for this error, but to no avail.
Does anyone have any good wisdom to share?

**Comment by PeterMoras** [comment]
Have you been able to load a config file successfully?
I ran into a similar issue when trying to load a config file, with the same
`UnboundLocalError: local variable 'my_data' referenced before assignment`.

This appears to be a straight up error in the code, as `my_data` is never referenced else.

You can fix this issue by opening dreambooth_gui.py, going to line 217, and changing both instances of `my_data` to `my_data_db`

**Comment by PeterMoras** [comment]
Also you are commenting in the wrong Github Repository.
You are probably using https://github.com/bmaltais/kohya_ss
but this is https://github.com/kohya-ss/sd-scripts

**Comment by HomePie03** [comment]
Mr.PeterMoras
Thank you for telling us how to solve this problem and  about the location. About location, I'll keep that in mind henceforth.

**Comment by aytekinttas** [comment]
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory C:\Users\Monster\Desktop\ai\ai-kohya\lora traning serenay\training_test_2\img\30_serenays_l1rv_2 person contains 40 image files
1200 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Monster\Desktop\ai\ai-kohya\lora traning serenay\training_test_2\img\30_serenays_l1rv_2 person"    image_count: 40
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: serenays_l1rv_2 person
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 3995.91it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 90
bucket 1: resolution (384, 576), count: 180
bucket 2: resolution (512, 512), count: 930
mean ar error (without repeats): 0.00016288773902651822
prepare accelerator
C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\Monster\AppData\Local\Programs\Python\Python310\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2077: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\library\train_util.py", line 2956, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\library\train_util.py", line 2922, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\library\model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\Monster/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'C:\Users\Monster/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Traceback (most recent call last):
  File "C:\Users\Monster\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Monster\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\Monster\Desktop\ai\ai-kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Monster\\Desktop\\ai\\ai-kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/Monster/Desktop/ai/ai-kohya/lora traning serenay/eğitimmodel/realisticVisionV20_v20.safetensors', '--train_data_dir=C:/Users/Monster/Desktop/ai/ai-kohya/lora traning serenay/training_test_2/img', '--resolution=512,512', '--output_dir=C:/Users/Monster/Desktop/ai/ai-kohya/lora traning serenay/trainig_test_1/model', '--logging_dir=C:/Users/Monster/Desktop/ai/ai-kohya/lora traning serenay/trainig_test_1/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=serenays_l1rv', '--lr_scheduler_num_cycles=1', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=120', '--train_batch_size=1', '--max_train_steps=1200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
