### ISSUE TITLE
Input must be callable

### ISSUE THREAD

**Issue by sALTaccount** [kohya-ss/sd-scripts#253]
There is an error on line 20 of `train_network.py` when `import library.config_util as config_util` tries to run.

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/salt/clone/sd-scripts/library/config_util.py", line 113, in <module>
    class ConfigSanitizer:
  File "/home/salt/clone/sd-scripts/library/config_util.py", line 116, in ConfigSanitizer
    def __validate_and_convert_twodim(klass, value: Sequence) -> Tuple:
  File "/home/salt/clone/sd-scripts/venv/lib/python3.9/site-packages/toolz/functoolz.py", line 201, in __init__
    raise TypeError("Input must be callable")
TypeError: Input must be callable
```
used to work just fine before I pulled.

My training command is as follows:
```
venv/bin/python3 train_network.py \
    --pretrained_model_name_or_path=models/wd-1-5-beta2-fp16.safetensors \
    --train_data_dir=chocoan \
    --output_dir=loras \
    --reg_data_dir=empty \
    --prior_loss_weight=1.0 \
    --resolution=896,896 \
    --train_batch_size=2 \
    --learning_rate=1e-4 \
    --text_encoder_lr=5e-5 \
    --network_dim=128 \
    --network_alpha=128 \
    --lr_scheduler=cosine_with_restarts \
    --max_train_steps=8000 \
    --use_8bit_adam \
    --xformers \
    --save_every_n_epochs=1 \
    --save_model_as=safetensors \
    --seed=43 \
    --flip_aug \
    --network_module=networks.lora \
    --v2 \
    --v_parameterization \
    --enable_bucket \
    --min_bucket_reso=384 \
    --max_bucket_reso=1024 \
    --caption_extension=".txt"
    ```

**Comment by sALTaccount** [comment]
Interesting, reverting back to the old commit didn't fix anything. I also didn't touch anything to the best of my knowledge....

**Comment by sALTaccount** [comment]
ah, apparently i somehow switched my venv to python 3.9. changing it back to the 3.10 one worked fine

**Comment by Linaqruf** [comment]
Oh that's why new update doesn't work on Colab lol
