### ISSUE TITLE
Error just before learning

### ISSUE THREAD

**Issue by StupidGame** [kohya-ss/sd-scripts#263]
LoConを使って学習をさせているのですが、以下のエラーが出ます。
I am using LoCon to learn, but I get the following error.

running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 300
  num reg images / 正則化画像の数: 100
  num batches per epoch / 1epochのバッチ数: 300
  num epochs / epoch数: 10
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 3000
Traceback (most recent call last):
  File "sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "sd-scripts/train_network.py", line 411, in train
    metadata |= {
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1069, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 551, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sd-scripts/train_network.py', '--pretrained_model_name_or_path=JosephusCheung/ACertainty', '--train_data_dir=train', '--reg_data_dir=reg', '--network_dim=16', '--network_alpha=8', '--resolution=512', '--enable_bucket', '--output_dir=output', '--prior_loss_weight=1.0', '--train_batch_size=2', '--text_encoder_lr=1.1666666666666666e-05', '--unet_lr=7e-05', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=750', '--max_train_steps=3000', '--optimizer_type=Lion', '--mixed_precision=fp16', '--xformers', '--cache_latents', '--gradient_checkpointing', '--save_precision=fp16', '--save_every_n_epochs=2', '--save_model_as=safetensors', '--network_module=locon.locon_kohya', '--network_args', 'conv_dim=8', 'conv_alpha=4', '--logging_dir=logs', '--clip_skip=2']' returned non-zero exit status 1.

**Comment by p1atdev** [comment]
train_network で使われている `|=` 演算子が Python 3.9 以降の記法のようで、 Colab などの Python 3.8 環境だとエラーが出るようです。
ローカルの3.10.6環境では問題は発生しませんでした。

https://github.com/kohya-ss/sd-scripts/blob/46aee85d2a88e279d9a0a286f579f5f3434a3c56/train_network.py#L410-L428

`metadata.update({ "ss_batch_size_per_device": ... })` のようにすれば 3.8 でも同じ動作を実現できそうです。

**Comment by StupidGame** [comment]
ありがとうございます！
