### ISSUE TITLE
Error when trying to use DAdaptation

### ISSUE THREAD

**Issue by Lauson1ex** [kohya-ss/sd-scripts#266]
For LoRA training, other optimizers such as Adam8bit work, but DAdaptation always returns an error when passing it as argument to `--optimizer_type`, with the following unhelpful error message:
```python
ModuleNotFoundError: No module named 'dadaptation'

ImportError("No dadaptation / dadaptation がインストールされていないようです")
ImportError: No dadaptation / dadaptation がインストールされていないようです
```

Full log:
```python
import network module: networks.lora
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "G:\dev\sd-scripts\library\train_util.py", line 1747, in get_optimizer
    import dadaptation
ModuleNotFoundError: No module named 'dadaptation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\dev\sd-scripts\train_network.py", line 642, in <module>
    train(args)
  File "G:\dev\sd-scripts\train_network.py", line 168, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "G:\dev\sd-scripts\library\train_util.py", line 1749, in get_optimizer
    raise ImportError("No dadaptation / dadaptation がインストールされていないようです")
ImportError: No dadaptation / dadaptation がインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Endri\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Endri\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\dev\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\dev\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "G:\dev\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "G:\dev\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher

```

**Comment by Lauson1ex** [comment]
I learned there is a py dadaptation package shortly after submitting the issue.
Still, this requirement should have been on `requirements.txt` or mentioned as an optional install. This made me pull the repo thinking some internal dependency was missing.
