### ISSUE TITLE
UnboundLocalError: local variable 'pipe' referenced before assignment

### ISSUE THREAD

**Issue by larssn** [kohya-ss/sd-scripts#279]
Keep getting the following exception. This is using Python 3.10.10.
I'm using the GUI made by [bmaltais](https://github.com/bmaltais), if that is relevant, and I made an issue about it over there (https://github.com/bmaltais/kohya_ss/issues/345), but was redirected here.

```
Traceback (most recent call last):
  File "F:\Software\kohya_ss\train_network.py", line 652, in <module>
    train(args)
  File "F:\Software\kohya_ss\train_network.py", line 114, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "F:\Software\kohya_ss\library\train_util.py", line 2024, in load_target_model
    text_encoder = pipe.text_encoder
UnboundLocalError: local variable 'pipe' referenced before assignment

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Software\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by larssn** [comment]
That was the problem. I was using the GUI to point to the folder, but the ckpt wasn't picked up.
It worked when I pointed it at the ckpt directly.

Thanks for the response.
I feel it would be a good idea to clarify how the pointing to a folder works?

**Comment by kopyl** [comment]
@kohya-ss why it's not working with the models downloading from Hugging face? It was working a couple days ago and now it does not and i'm getting this error... :(

**Comment by kopyl** [comment]
@kohya-ss if it's required to have a model locally, what should it be for training LoRA? .ckpt? .safetensors? Diffusers (folder)?

**Comment by kopyl** [comment]
@kohya-ss I dropped the server, so don't have access to it. Maybe next time.

It's strange cause without manually downloading a model my training was working correctly...
