### ISSUE TITLE
Could not start Training, please help me!

### ISSUE THREAD

**Issue by 764220145** [kohya-ss/sd-scripts#280]
Here is the code, after "prepare accelerator", it just went wrong. And I do not know why. Please help me! Thank you!!!

Loading config...
Folder 50_LuoTianYi: 6300 steps
max_train_steps = 3150
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="D:/Stable Diffusion/Training/image" --resolution=512,512 --output_dir="D:/Stable Diffusion/Training/model" --logging_dir="D:/Stable Diffusion/Training/Log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="luotianyi" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="3150" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory D:\Stable Diffusion\Training\image\50_LuoTianYi contains 126 image files
6300 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "D:\Stable Diffusion\Training\image\50_LuoTianYi"
    image_count: 126
    num_repeats: 50
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: LuoTianYi
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 126/126 [00:00<00:00, 5998.46it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "D:\kohya\kohya_ss\train_network.py", line 652, in <module>
    train(args)
  File "D:\kohya\kohya_ss\train_network.py", line 108, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\kohya\kohya_ss\library\train_util.py", line 1973, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 370, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "C:\Users\ZUOZUO\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ZUOZUO\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:/Stable Diffusion/Training/image', '--resolution=512,512', '--output_dir=D:/Stable Diffusion/Training/model', '--logging_dir=D:/Stable Diffusion/Training/Log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=luotianyi', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=3150', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by AI-Casanova** [comment]
> ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.

Change precision from bf16 to fp16

**Comment by 764220145** [comment]
> 

OMG， it helps, thank you so much!!! I love you!

**Comment by 764220145** [comment]
> > ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
> 
> Change precision from bf16 to fp16

OMG， it helps, thank you so much!!! I love you!

**Comment by AI-Casanova** [comment]
Cheers!

**Comment by Manjiz** [comment]
I found the pytorch version is 1.9.0. So, 1. cannot use bf16? 2. manual upgrade it?

**Comment by bzImanol** [comment]
How can I change it?

**Comment by lynrayy** [comment]
bf16 mixed precision requires PyTorch >= 1.10 and a supported device.

Why the fuck this thing installing with outdated version of PyTorch?!??!?!?!?

**Comment by lynrayy** [comment]
How to update it?????
