### ISSUE TITLE
After update i get this errors and dont work anymore!

### ISSUE THREAD

**Issue by merecesarchviz** [kohya-ss/sd-scripts#289]
Hi,

I update the to the last version here, and after doing it when i run the training, it gives me this errors!:

Traceback (most recent call last):
  File "F:\kohya\sd-scripts\train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "F:\kohya\sd-scripts\library\config_util.py", line 19, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
Traceback (most recent call last):
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\kohya\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\kohya\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=G:/Ai_Models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=G:/Ai_Models/training/Creatures/Koyha3/img', '--resolution=512,512', '--output_dir=G:/Ai_Models/training/Creatures/Koyha3/model', '--logging_dir=G:/Ai_Models/training/Creatures/Koyha3/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=FunnyCreaturesV3', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=6', '--max_train_steps=634', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by magpie514** [comment]
You must enter the venv and use the command `pip install --use-pep517 --upgrade -r requirements.txt` .
You are just missing a dependency, that should do it.

**Comment by merecesarchviz** [comment]
Yes, it was that! thks for the tip
