### ISSUE TITLE
Error loading json config file

### ISSUE THREAD

**Issue by Zuellni** [kohya-ss/sd-scripts#340]
Python 3.10 on Windows 11

Log:
```bat
python train_network.py --dataset_config="config.json"
prepare tokenizer
Load dataset config from config.json
Error on parsing JSON config file. Please check the format. / JSON 形式の設定ファイルの読み込みに失
敗しました。文法が正しいか確認してください。: config.json
Traceback (most recent call last):
  File "[...]\sd-scripts\train_network.py", line 711, in <module>
    train(args)
  File "[...]\sd-scripts\train_network.py", line 68, in train
    user_config = config_util.load_user_config(args.dataset_config)
  File "[...]\sd-scripts\library\config_util.py", line 489, in load_user_config
    config = json.load(file)
  File "[...]\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'WindowsPath' object has no attribute 'read'
```

Haven't checked but the same thing presumably happens with toml.  
Changing `config = json.load(file)` in `config_util.py` fixes it:
```py
with open(file) as f:
   config = json.load(f)
```

**Comment by Zuellni** [comment]
This seems to be working correctly now.
