### ISSUE TITLE
Can't use LoRA trained for SD 2.1 in WebUI

### ISSUE THREAD

**Issue by kopyl** [kohya-ss/sd-scripts#346]
I get this error. Is this expected?

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f70221f4f40>]: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 176, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [8, 320, 1, 1] doesn't match the broadcast shape [8, 320, 8, 320]

**Comment by kopyl** [comment]
@kopyl i guess the error here was that i used lora trained on SD 2.1 768px, but in SD i was using it with the base model 512px. I fixed it.
