### ISSUE TITLE
Error trying to extract LoRa

### ISSUE THREAD

**Issue by Signorlimone** [kohya-ss/sd-scripts#368]
I'm trying to extract LoRa but it keeps giving me this error:

./venv/Scripts/python.exe "networks\extract_lora_from_models.py" --save_precision fp16 --save_to "C:/AI/stable-diffusion-webui/models/Stable-diffusion/srsLora.safetensors" --model_org "C:/AI/stable-diffusion-webui/models/Stable-diffusion/protogenX34Photorealism_1.safetensors" --model_tuned "C:/AI/stable-diffusion-webui/models/Stable-diffusion/srs_style.ckpt" --dim 4 --device cuda --conv_dim 11
Traceback (most recent call last):
  File "C:\Users\RINO\kohya_ss\networks\extract_lora_from_models.py", line 10, in <module>
    import library.model_util as model_util
ModuleNotFoundError: No module named 'library'

**Comment by michaeltran33** [comment]
till having same problem. there is directory library and file model_uti. The problem is still there. File "C:\Users\RINO\kohya_ss\networks\extract_lora_from_models.py", line 11, in
import library.model_util as model_util
ModuleNotFoundError: No module named 'library'

**Comment by Viakole** [comment]
Having the same issue and same error but with SDXL merge lora or regular Merge lora. 
import library.model_util as model_util
ModuleNotFoundError: No module named 'library'.
Tried pip install requirements and many other things to no avail. would like an update!

**Comment by Signorlimone** [comment]
> till having same problem. there is directory library and file model_uti. The problem is still there. File "C:\Users\RINO\kohya_ss\networks\extract_lora_from_models.py", line 11, in import library.model_util as model_util ModuleNotFoundError: No module named 'library'

C:\Users\**RINO**\kohya_ss\networks\extract_lora_from_models.py

I hope you copied my error message, otherwise it would be really strange that you have the same folder structure I have with my same windows username 😅

**Comment by michaeltran33** [comment]
I think I found the reason, that there r 2 library directories one inside venv and one outside. What I did to solve it is to uninstall the latest python, reinstall the required version 10.9. 
also reinstalled kohya_ss, then it works fine.

**Comment by fableman73** [comment]
ERROR: Package 'library' requires a different Python: 3.11.4 not in '<3.11,>=3.9'
