### ISSUE TITLE
Error while downloading pytorch_model.bin

### ISSUE THREAD

**Issue by Timellie** [kohya-ss/sd-scripts#398]
_Hello,
The installation was fine, however when I begin to train lora, I get an error.
Setup is fine everything matching and looking like this:_

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 265/265 [00:00<00:00, 9129.44it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 26500
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>

_But then a big 1.71GB file begins downloading and always crashing_

Downloading pytorch_model.bin:   7%|███▍                                           | 126M/1.71G [01:02<10:37, 2.49MB/s]Traceback (most recent call last):
  File "C:\path\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\ path1\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\ path1\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\ path2\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\ path2\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\ path2\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\ path2\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

_I tried to play with some settings, ensured I have pip and torch up to date and set up kohya_ss once more but cannot resolve the issue._

**Comment by neozbr** [comment]
same error I've download the  pytorch_model.bin manually, but where or in what directory I have to put ?... you can download here: https://huggingface.co/openai/clip-vit-large-patch14/tree/main but I have no ideia where to place since the system insist in trying to download from huggingface..

**Comment by MiKoronjoo** [comment]
> same error I've download the pytorch_model.bin manually, but where or in what directory I have to put ?... you can download here: https://huggingface.co/openai/clip-vit-large-patch14/tree/main but I have no ideia where to place since the system insist in trying to download from huggingface..

Thank you for the download link.
You just need to place the  pytorch_model.bin path in this line of code, instead of `openai/clip-vit-large-patch14`: https://github.com/kohya-ss/sd-scripts/blob/7ad7cac0c272211abb688168d4c2d4400bef7c51/library/model_util.py#L898

**Comment by Manjiz** [comment]
This should be same as `train_util.load_tokenizer` which read from args.tokenizer_cache_dir

**Comment by poporogue** [comment]
I have the same problem and it cannot be resolved. I have followed above comments and the result is just the same as Timellie.
can anyone have any idea where should i place the pytorch_model.bin? 

Thanks a lot.

**Comment by FukangSun** [comment]
> I have the same problem and it cannot be resolved. I have followed above comments and the result is just the same as Timellie. can anyone have any idea where should i place the pytorch_model.bin?
> 
> Thanks a lot.

I solve this problem in ubuntu, hope this can help u . first , I download the "https://huggingface.co/openai/clip-vit-large-patch14/tree/main" to local disk, put it to "/home/lora-scripts/openai/clip-vit-large-patch14" . and then you need to modify two files in ~/lora-scripts/sd-scripts/library folder, I mean "model_util.py" and "train_util.py".  first, modify "model_util.py", you need modify this line "text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)", in my case , it changed to "text_model = CLIPTextModel.from_pretrained("/home/lora-scripts/openai/clip-vit-large-patch14").to(device)". second, you also should modify the "train_util.py", modify this line TOKENIZER_PATH = "openai/clip-vit-large-patch14"  like above.
