### ISSUE TITLE
Problem with training Lora (not starting) 

### ISSUE THREAD

**Issue by dill-shower** [kohya-ss/sd-scripts#405]
I trying to train Lora but give strange error. I try reinstall all packages and venv but it's not help. Model stable diffusion V2.1-768
/

Traceback (most recent call last):
  File "/home/user/sd-scripts/train_network.py", line 18, in <module>
    import library.train_util as train_util
  File "/home/user/sd-scripts/library/train_util.py", line 63, in <module>
    import library.huggingface_util as huggingface_util
  File "/home/user/sd-scripts/library/huggingface_util.py", line 25, in <module>
    src: Union[str, Path, bytes, BinaryIO],
NameError: name 'BinaryIO' is not defined
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/stable-diffusion-webui/venv/bin/python3', 'train_network.py', '--pretrained_model_name_or_path=/home/user/stable-diffusion-webui/models/Stable-diffusion/model.safetensors', '--dataset_config=test.toml', '--output_dir=/home/user/outputlora', '--output_name=lora', '--save_model_as=safetensors', '--prior_loss_weight=1.0', '--max_train_steps=400', '--learning_rate=3e-5', '--network_dim=4', '--optimizer_type=AdamW8bit', '--xformers', '--mixed_precision=fp16', '--cache_latents', '--gradient_checkpointing', '--save_every_n_epochs=1', '--network_module=networks.lora']' returned non-zero exit status 1.

**Comment by angelOnly** [comment]
I changed BinaryIO to BytesIO and imported the package from io import BytesIO at the top of the file and it worked
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/18018532/232035142-eda96be2-23e0-4172-9482-364176ed0867.png">

**Comment by ProGamerGov** [comment]
You can also comment out `import library.huggingface_util as huggingface_util` in `train_network.py` and `library/train_util.py` to resolve this issue.

**Comment by jonathanhecl** [comment]
Thanks angelOnly! with this change works!

**Comment by StefSupertramp** [comment]
> I changed BinaryIO to BytesIO and imported the package from io import BytesIO at the top of the file and it worked <img alt="image" width="1242" src="https://user-images.githubusercontent.com/18018532/232035142-eda96be2-23e0-4172-9482-364176ed0867.png">

I don't understand on which file I should make those changes?

**Comment by StefSupertramp** [comment]
> > I changed BinaryIO to BytesIO and imported the package from io import BytesIO at the top of the file and it worked <img alt="image" width="1242" src="https://user-images.githubusercontent.com/18018532/232035142-eda96be2-23e0-4172-9482-364176ed0867.png">
> 
> I don't understand on which file I should make those changes?

Found it for those looking for it, the file in question is huggingface_util.py
