### ISSUE TITLE
Extracted Lora is in error.

### ISSUE THREAD

**Issue by GeneralAwareness** [kohya-ss/sd-scripts#425]
https://github.com/bmaltais/kohya_ss/issues/626#issue-1670199415

As you can see I posted there first but he said to contact you since it isn't his gui causing the error.   Any ideas?

Error is: activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7fd740735b10>, <modules.extra_networks.ExtraNetworkParams object at 0x7fd740736260>]: AssertionError
Traceback (most recent call last):
File "/home/ga/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
extra_network.activate(p, extra_network_args)
File "/home/ga/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
lora.load_loras(names, multipliers)
File "/home/ga/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/../../extensions-builtin/Lora/lora.py", line 214, in load_loras
lora = load_lora(name, lora_on_disk.filename)
File "/home/ga/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/../../extensions-builtin/Lora/lora.py", line 185, in load_lora
assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_unet_down_blocks_0_downsamplers_0_conv.lora_mid.weight - must end in lora_up.weight, lora_down.weight or alpha

Shows in Linux but not in Windows but the resulting image is the same so Windows is silently ignoring the lora.  I tested this and both Linux, and Windows, were identical images with or without the lora being used.

**Comment by pandora523** [comment]
I think Im having the same problem from my extracted lora  Btw im using Mac

**Comment by Havasiz** [comment]
Bump, same error.

**Comment by Havasiz** [comment]
I fixed it by installing LyCORIS https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by GeneralAwareness** [comment]
Yeah, Kohya is bad and needs major updates, so remove his extension and replace it with the lycoris one.
