### ISSUE TITLE
how to use the trained lora safetensors in pipeline?

### ISSUE THREAD

**Issue by sinri** [kohya-ss/sd-scripts#549]
I used your great work to train a model, and the generated safetensors files works in WebUI;
however it could not be used in pure code with pipeline, such as 
```
# in main
    pipeline = StableDiffusionPipeline.from_ckpt('e:\\xxx\\trained\\stable-diffusion-v1-5-lxq-3.safetensors')
    pipeline.to('cuda')
    drawn = pipeline(
        prompt='a girl with a cat',
        height=1024,
        width=1024,
        num_inference_steps=20,
        guidance_scale=5,
        negative_prompt='lowres'
    )
    image = drawn.images[0]
    image.show()
```

would result in error, like

```
global_step key not found in model
Traceback (most recent call last):
  File "E:\xxx\taiyi\drawer\SafetensorsDrawTest.py", line 4, in <module>
    pipeline = StableDiffusionPipeline.from_ckpt(
  File "E:\xxxr\venv\lib\site-packages\diffusers\loaders.py", line 1284, in from_ckpt
    pipe = download_from_original_stable_diffusion_ckpt(
  File "E:\xxx\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1177, in download_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "E:\xxx\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 376, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```

Could you please give some advice? 
Thx.

**Comment by sinri** [comment]
Seems good, continuable now ...

**Comment by Damarcreative** [comment]
If you want to run a single file, you can code like this:

```
repo_id = "/content/model.ckpt"

pipe = StableDiffusionPipeline.from_single_file(
    repo_id,
    torch_dtype=torch.float16,
    use_karras_sigmas=True,
    algorithm_type="sde-dpmsolver++"
    )
pipe.to('cuda')

image = pipe(
    prompt="a girl with a cat", 
    negative_prompt="low quality, blur, monochrome,", 
    width=512,
    height=512,
    guidance_scale=8,
    num_inference_steps=50
    ).images[0]
image.save("output.png")

```
But if you want to add LoRA, then add the following code:

`pipe.load_lora_weights(".", weight_name="/content/model/model.safetensors")`

Code example:

```
repo_id = "/content/model.ckpt"

pipe = StableDiffusionPipeline.from_single_file(
    repo_id,
    torch_dtype=torch.float16,
    use_karras_sigmas=True,
    algorithm_type="sde-dpmsolver++"
    )
pipe.to('cuda')
pipe.load_lora_weights(".", weight_name="/content/model/lora/realistic-glossy-face-skin.safetensors")

image = pipe(
    prompt="a girl with a cat", 
    negative_prompt="low quality, blur, monochrome,", 
    width=512,
    height=512,
    guidance_scale=8,
    num_inference_steps=50
    ).images[0]
image.save("output.png")

```

Try my Code which I improved :
https://colab.research.google.com/drive/1I91Jr_pWgGBISrMzl3AiFj_W8tIKLfBw?usp=sharing

**Comment by suti-kop** [comment]
![Uploading b1184ce8-bcbb-4b18-8920-e5c8114b8055.jpg…]()

**Comment by suti-kop** [comment]
![2ab44806-bfdf-45ea-be49-c04badd1342c](https://github.com/kohya-ss/sd-scripts/assets/154696713/752e7863-91cb-48dc-afdc-be4e6e0a38e9)
nude

**Comment by suti-kop** [comment]
repo_id = "/content/model.ckpt"

pipe = StableDiffusionPipeline.from_single_file(
    repo_id,
    torch_dtype=torch.float16,
    use_karras_sigmas=True,
    algorithm_type="sde-dpmsolver++"
    )
pipe.to('cuda')
pipe.load_lora_weights(".", weight_name="/content/model/lora/model-lora.safetensors")

image = pipe(
    prompt="a girl with a cat", 
    negative_prompt="low quality, blur, monochrome,", 
    width=512,
    height=512,
    guidance_scale=8,
    num_inference_steps=50
    ).images[0]
image.save("output.png")
