### ISSUE TITLE
Permission denied issue with SD scripts

### ISSUE THREAD

**Issue by Nthompson096** [kohya-ss/sd-scripts#576]
Greetings, I am using a script that uses parts of your code from [this github repo](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts) however I'm always hit with a permission denied error; the distro that I am using is Arch and the gpu and I am using is a 3060 12GB.

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/cv2/../../lib64')}
warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain libcudart.so as expected! Searching further paths...
warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1527,unix/windows98'), PosixPath('local/windows98')}
warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk/gtkrc'), PosixPath('/home/nicholas/.gtkrc')}
warn(
Traceback (most recent call last):
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 864, in
train(args)
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 253, in train
optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/library/train_util.py", line 2623, in get_optimizer
import bitsandbytes as bnb
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/init.py", line 6, in
from .autograd._functions import (
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in
import bitsandbytes.functional as F
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in
from .cextension import COMPILED_WITH_CUDA, lib
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in
lib = CUDALibrary_Singleton.get_instance().lib
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
cls._instance.initialize()
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 15, in initialize
binary_name = evaluate_cuda_setup()
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 123, in evaluate_cuda_setup
cudart_path = determine_cuda_runtime_lib_path()
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 117, in determine_cuda_runtime_lib_path
cuda_runtime_libs.update(find_cuda_lib_in(value))
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 53, in find_cuda_lib_in
resolve_paths_list(paths_list_candidate)
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 48, in resolve_paths_list
return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 23, in remove_non_existent_dirs
raise exc
File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 19, in remove_non_existent_dirs
if path.exists():
File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
self.stat()
File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/nicholas'
Failed to train because of error:
Command '['/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python', 'sd_scripts/train_network.py', '--config_file=runtime_store/config.toml', '--dataset_config=runtime_store/dataset.toml']' returned non-zero exit status 1.
```

**Comment by Nthompson096** [comment]
Looks like it can actually trained, had to run as root sadly.

**Comment by Nthompson096** [comment]
Turns out the issue is adam8bit I have to use adam8bitw.

**Comment by Nthompson096** [comment]
Already have cuda install with the pacman manager.
```
sudo pacman -S cuda
```

**Comment by Nthompson096** [comment]
I also have
```
/opt/cuda/lib64/libcudart.so
```
inside my opt.

**Comment by Nthompson096** [comment]
Right after setting ```export LD_LIBRARY_PATH=/opt/cuda/:$LD_LIBRARY_PATH```

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64:/opt/cuda/: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/windows98'), PosixPath('@/tmp/.ICE-unix/1523,unix/windows98')}
  warn(
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk/gtkrc'), PosixPath('/home/nicholas/.gtkrc')}
  warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./sdxl_train_network.py:174 in <module>                   │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/train_network.py:325 in train                             │
│                                                                                                  │
│   322 │   │   │   )                                                                              │
│   323 │   │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, ar   │
│   324 │   │                                                                                      │
│ ❱ 325 │   │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, train   │
│   326 │   │                                                                                      │
│   327 │   │   # dataloaderを準備する                                                             │
│   328 │   │   # DataLoaderのプロセス数：0はメインプロセスになる                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:3187 in get_optimizer               │
│                                                                                                  │
│   3184 │                                                                                         │
│   3185 │   if optimizer_type == "AdamW8bit".lower():                                             │
│   3186 │   │   try:                                                                              │
│ ❱ 3187 │   │   │   import bitsandbytes as bnb                                                    │
│   3188 │   │   except ImportError:                                                               │
│   3189 │   │   │   raise ImportError("No bitsand bytes / bitsandbytesがインストールされていない  │
│   3190 │   │   print(f"use 8-bit AdamW optimizer | {optimizer_kwargs}")                          │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.p │
│ y:6 in <module>                                                                                  │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_ │
│ functions.py:5 in <module>                                                                       │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional │
│ .py:13 in <module>                                                                               │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:41 in <module>                                                                               │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:37 in get_instance                                                                           │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:15 in initialize                                                                             │
│                                                                                                  │
│   12 │   │   raise RuntimeError("Call get_instance() instead")                                   │
│   13 │                                                                                           │
│   14 │   def initialize(self):                                                                   │
│ ❱ 15 │   │   binary_name = evaluate_cuda_setup()                                                 │
│   16 │   │   package_dir = Path(__file__).parent                                                 │
│   17 │   │   binary_path = package_dir / binary_name                                             │
│   18                                                                                             │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /main.py:123 in evaluate_cuda_setup                                                              │
│                                                                                                  │
│   120 │   │   #print('No GPU detected. Loading CPU library...')                                  │
│   121 │   │   #return binary_name                                                                │
│   122 │                                                                                          │
│ ❱ 123 │   cudart_path = determine_cuda_runtime_lib_path()                                        │
│   124 │   if cudart_path is None:                                                                │
│   125 │   │   print(                                                                             │
│   126 │   │   │   "WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (an   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /paths.py:117 in determine_cuda_runtime_lib_path                                                 │
│                                                                                                  │
│   114 │                                                                                          │
│   115 │   cuda_runtime_libs = set()                                                              │
│   116 │   for env_var, value in remaining_candidate_env_vars.items():                            │
│ ❱ 117 │   │   cuda_runtime_libs.update(find_cuda_lib_in(value))                                  │
│   118 │                                                                                          │
│   119 │   if len(cuda_runtime_libs) == 0:                                                        │
│   120 │   │   print('CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Se   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /paths.py:53 in find_cuda_lib_in                                                                 │
│                                                                                                  │
│    50                                                                                            │
│    51 def find_cuda_lib_in(paths_list_candidate: str) -> Set[Path]:                              │
│    52 │   return get_cuda_runtime_lib_paths(                                                     │
│ ❱  53 │   │   resolve_paths_list(paths_list_candidate)                                           │
│    54 │   )                                                                                      │
│    55                                                                                            │
│    56                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /paths.py:48 in resolve_paths_list                                                               │
│                                                                                                  │
│    45 │   Searches a given environmental var for the CUDA runtime library,                       │
│    46 │   i.e. `libcudart.so`.                                                                   │
│    47 │   """                                                                                    │
│ ❱  48 │   return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))         │
│    49                                                                                            │
│    50                                                                                            │
│    51 def find_cuda_lib_in(paths_list_candidate: str) -> Set[Path]:                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /paths.py:23 in remove_non_existent_dirs                                                         │
│                                                                                                  │
│    20 │   │   │   │   existent_directories.add(path)                                             │
│    21 │   │   except OSError as exc:                                                             │
│    22 │   │   │   if exc.errno != errno.ENAMETOOLONG:                                            │
│ ❱  23 │   │   │   │   raise exc                                                                  │
│    24 │                                                                                          │
│    25 │   non_existent_directories: Set[Path] = candidate_paths - existent_directories           │
│    26 │   if non_existent_directories:                                                           │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup │
│ /paths.py:19 in remove_non_existent_dirs                                                         │
│                                                                                                  │
│    16 │   existent_directories: Set[Path] = set()                                                │
│    17 │   for path in candidate_paths:                                                           │
│    18 │   │   try:                                                                               │
│ ❱  19 │   │   │   if path.exists():                                                              │
│    20 │   │   │   │   existent_directories.add(path)                                             │
│    21 │   │   except OSError as exc:                                                             │
│    22 │   │   │   if exc.errno != errno.ENAMETOOLONG:                                            │
│                                                                                                  │
│ /usr/lib/python3.10/pathlib.py:1290 in exists                                                    │
│                                                                                                  │
│   1287 │   │   Whether this path exists.                                                         │
│   1288 │   │   """                                                                               │
│   1289 │   │   try:                                                                              │
│ ❱ 1290 │   │   │   self.stat()                                                                   │
│   1291 │   │   except OSError as e:                                                              │
│   1292 │   │   │   if not _ignore_error(e):                                                      │
│   1293 │   │   │   │   raise                                                                     │
│                                                                                                  │
│ /usr/lib/python3.10/pathlib.py:1097 in stat                                                      │
│                                                                                                  │
│   1094 │   │   Return the result of the stat() system call on this path, like                    │
│   1095 │   │   os.stat() does.                                                                   │
│   1096 │   │   """                                                                               │
│ ❱ 1097 │   │   return self._accessor.stat(self, follow_symlinks=follow_symlinks)                 │
│   1098 │                                                                                         │
│   1099 │   def owner(self):                                                                      │
│   1100 │   │   """                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/nicholas'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/bin/accelerate:8 in <module>                         │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Nthompson096** [comment]
```
Tue Aug  8 18:25:50 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:06:00.0 Off |                  N/A |
| 66%   44C    P8              19W / 170W |      9MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       921      G   /usr/lib/Xorg                                 4MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by Nthompson096** [comment]
```export PATH=$PATH:/opt/cuda/bin/```
```export LD_LIBRARY_PATH=/opt/cuda/lib64/```
prints:
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
CUDA SETUP: CUDA runtime path found: /opt/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda122.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./train_network.py:990 in <module>                        │
│                                                                                                  │
│   987 │   args = train_util.read_config_from_file(args, parser)                                  │
│   988 │                                                                                          │
│   989 │   trainer = NetworkTrainer()                                                             │
│ ❱ 990 │   trainer.train(args)                                                                    │
│   991                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./train_network.py:325 in train                           │
│                                                                                                  │
│   322 │   │   │   )                                                                              │
│   323 │   │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, ar   │
│   324 │   │                                                                                      │
│ ❱ 325 │   │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, train   │
│   326 │   │                                                                                      │
│   327 │   │   # dataloaderを準備する                                                             │
│   328 │   │   # DataLoaderのプロセス数：0はメインプロセスになる                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:3187 in get_optimizer               │
│                                                                                                  │
│   3184 │                                                                                         │
│   3185 │   if optimizer_type == "AdamW8bit".lower():                                             │
│   3186 │   │   try:                                                                              │
│ ❱ 3187 │   │   │   import bitsandbytes as bnb                                                    │
│   3188 │   │   except ImportError:                                                               │
│   3189 │   │   │   raise ImportError("No bitsand bytes / bitsandbytesがインストールされていない  │
│   3190 │   │   print(f"use 8-bit AdamW optimizer | {optimizer_kwargs}")                          │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.p │
│ y:6 in <module>                                                                                  │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_ │
│ functions.py:5 in <module>                                                                       │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional │
│ .py:13 in <module>                                                                               │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:41 in <module>                                                                               │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:37 in get_instance                                                                           │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension │
│ .py:28 in initialize                                                                             │
│                                                                                                  │
│   25 │   │   │   │   print('CUDA SETUP: CUDA detection failed. Either CUDA driver not install    │
│   26 │   │   │   │   print('CUDA SETUP: If you compiled from source, try again with `make CUD    │
│   27 │   │   │   │   raise Exception('CUDA SETUP: Setup Failed!')                                │
│ ❱ 28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   29 │   │   else:                                                                               │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")                           │
│   31 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│                                                                                                  │
│ /usr/lib/python3.10/ctypes/__init__.py:452 in LoadLibrary                                        │
│                                                                                                  │
│   449 │   │   return getattr(self, name)                                                         │
│   450 │                                                                                          │
│   451 │   def LoadLibrary(self, name):                                                           │
│ ❱ 452 │   │   return self._dlltype(name)                                                         │
│   453 │                                                                                          │
│   454 │   __class_getitem__ = classmethod(_types.GenericAlias)                                   │
│   455                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.10/ctypes/__init__.py:374 in __init__                                           │
│                                                                                                  │
│   371 │   │   self._FuncPtr = _FuncPtr                                                           │
│   372 │   │                                                                                      │
│   373 │   │   if handle is None:                                                                 │
│ ❱ 374 │   │   │   self._handle = _dlopen(self._name, mode)                                       │
│   375 │   │   else:                                                                              │
│   376 │   │   │   self._handle = handle                                                          │
│   377                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/bin/accelerate:8 in <module>                         │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Nthompson096** [comment]
It somehow cannot find 
```
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
```
It cannot find libcusparse.so.11; however I'm using libcusparse.so.12 in my OS.

**Comment by Nthompson096** [comment]
downgrade cuda?

**Comment by Nthompson096** [comment]
Turns out downgrading cuda and setting the envs to:
```
export LD_LIBRARY_PATH=/opt/cuda-11.1/lib64/
```
```
export PATH=$PATH:/opt/cuda-11.1/bin/
```

Solved the issue, it was a cuda version problem.

closing.
