### ISSUE TITLE
Kohya error in runpod

### ISSUE THREAD

**Issue by Megamaker1** [kohya-ss/sd-scripts#597]
Hi Guys!
Ive installed Kohya ss linux version on my runpod and after a spending 2 hours fixing a error, found a new error after I press
train model in the dreambooth lora tab. Since i have very limited coding knowledge, i need help please.

root@1422e0b89586:/workspace/kohya_ss-linux# source venv/bin/activate
(venv) root@1422e0b89586:/workspace/kohya_ss-linux# python3 ./kohya_gui.py
Load CSS...
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://e513ef000398c54e0d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss-linux/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss-linux/lora_gui.py", line 385, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: '.ipynb'

**Comment by bmaltais** [comment]
You may want to try this:

https://github.com/bmaltais/kohya_ss/issues/1062
