### ISSUE TITLE
[SDXL] CUDA out of memory

### ISSUE THREAD

**Issue by entrpn** [kohya-ss/sd-scripts#627]
I'm trying to finetune SDXL on an L4 GPU, but I keep getting a CUDA out of memory error. Any guidance would be appreciated. Here are my steps.

Prepare latents:

```bash
python prepare_buckets_latents.py \
cinematic meta_clean.json meta_lat.json \
~/sdxl/sd-scripts/sd_xl_base_0.9.safetensors \
--batch_size=1 \
--bucket_reso_steps=32 \
--max_data_loader_n_workers=4 \
--max_resolution="1024,1024" \
--min_bucket_reso=1024 \
--max_bucket_reso=1280 \
--mixed_precision="bf16"
```

Train

```bash
accelerate launch sdxl_train.py \
--sample_prompts=sample_prompt.txt \
--dataset_config=dataset_config.toml \
--config_file=config_file.toml \
--cache_text_encoder_outputs \
--save_every_n_steps 7000 \
--xformers
```

config_file.toml

```bash
[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "sd_xl_base_0.9.safetensors"

[optimizer_arguments]
optimizer_type = "adafactor"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False" ]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 100
learning_rate = 4e-7 # SDXL original learning rate
max_grad_norm = 0.0
train_text_encoder = false

[dataset_arguments]
debug_dataset = false

[training_arguments]
output_dir = "output"
output_name = "last"
save_precision = "fp16"
save_n_epoch_ratio = 1
save_state = false
train_batch_size = 1
mem_eff_attn = false
max_train_steps = 3305
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
gradient_checkpointing = false
gradient_accumulation_steps = 2
mixed_precision = "bf16"
logging_dir = "logs"
log_prefix = "last"

[sample_prompt_arguments]
sample_every_n_steps = 661
sample_sampler = "ddim"

[saving_arguments]
save_model_as = "safetensors"
```

dataset config

```bash
[[datasets]]
resolution = 1024
caption_dropout_rate = 0.0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
color_aug = false
[[datasets.subsets]]
image_dir = "cinematic"
num_repeats = 1
metadata_file = "meta_lat.json"

[general]
enable_bucket = true                        # Whether to use Aspect Ratio Bucketing
shuffle_caption = false
keep_tokens = 1
```

error:

```bash
Traceback (most recent call last):
  File "/home/foo/sdxl/sd-scripts/sdxl_train.py", line 618, in <module>
    train(args)
  File "/home/foo/sdxl/sd-scripts/sdxl_train.py", line 428, in train
    noise_pred = unet(noisy_latents, timesteps, text_embedding, vector_embedding)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 521, in forward
    return model_forward(*args, **kwargs)
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 509, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/foo/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 1099, in forward
    h = call_module(module, h, emb, context)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 1084, in call_module
    x = layer(x, context)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 723, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 646, in forward
    output = self.forward_body(hidden_states, context, timestep)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 630, in forward_body
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 574, in forward
    hidden_states = module(hidden_states)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 553, in forward
    return hidden_states * self.gelu(gate)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 547, in gelu
    return F.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 21.99 GiB total capacity; 19.87 GiB already allocated; 9.69 MiB free; 20.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                             | 0/3305 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/foo/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by entrpn** [comment]
Thanks for the quick response. With gradient_checkpointing = true, I'm still getting OOM. 

```
/home/foo/.local/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:339: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  and inp.query.storage().data_ptr() == inp.key.storage().data_ptr()
Traceback (most recent call last):
  File "/home/foo/sdxl/sd-scripts/sdxl_train.py", line 618, in <module>
    train(args)
  File "/home/foo/sdxl/sd-scripts/sdxl_train.py", line 444, in train
    accelerator.backward(loss)
  File "/home/foo/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1745, in backward
    loss.backward(**kwargs)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/foo/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/foo/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 321, in custom_forward
    return func(*inputs)
  File "/home/foo/sdxl/sd-scripts/library/sdxl_original_unet.py", line 308, in forward_body
    h = self.in_layers(x)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/foo/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 21.99 GiB total capacity; 19.24 GiB already allocated; 1.69 MiB free; 20.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by entrpn** [comment]
Ok I finally got this running by using switching to fp16 and running `--full_fp16`. So far the loss looks good.

**Comment by sdbds** [comment]
if you using linux ,u can use bitsandbytes for Paged optim,it will reduce so many memory
i will finish that pr in few days.
https://twitter.com/bdsqlsz/status/1677788826402705409

**Comment by entrpn** [comment]
awesome, will try it once its out.

**Comment by entrpn** [comment]
Another thing I want to point out is that you'll need a machine with at least 48GB of RAM to save the weights or the machine will freeze, or at least it did for me. I'm running in GCP and had to update the machine type from a `g2-standard-8` to `g2-standard-12`.

**Comment by marks202309** [comment]
with my RTX4090 24G memory, I can go ahead with the two suggestions in this thread,
gradient_checkpointing = true

--full_fp16
