### ISSUE TITLE
SDXL sampling broken when using multi-gpu training

### ISSUE THREAD

**Issue by yumlevi** [kohya-ss/sd-scripts#647]
Hi, here's the error

```python
generating sample images at step / サンプル画像生成 ステップ: 72
                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                           
  File "sdxl_train_network.py", line 167, in <module>
    trainer.train(args)
  File "/fsx/home-yam/trainer/sd-scripts/train_network.py", line 804, in train
    self.sample_images(accelerator, args, None, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "sdxl_train_network.py", line 151, in sample_images
    sdxl_train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "/fsx/home-yam/trainer/sd-scripts/library/sdxl_train_util.py", line 422, in sample_images
    return train_util.sample_images_common(SdxlStableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/library/train_util.py", line 3967, in sample_images_common
    image = pipeline(
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/library/sdxl_lpw_stable_diffusion.py", line 1007, in __call__
    noise_pred = self.unet(latent_model_input, t, text_embedding, vector_embedding)
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/library/sdxl_original_unet.py", line 1074, in forward
    h = call_module(module, h, emb, context)
  File "/fsx/home-yam/trainer/sd-scripts/library/sdxl_original_unet.py", line 1066, in call_module
    x = layer(x, context)
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/library/sdxl_original_unet.py", line 719, in forward
    hidden_states = self.proj_in(hidden_states)
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/networks/lora.py", line 92, in forward
    lx = self.lora_down(x)
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-yam/trainer/sd-scripts/.env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
```

**Comment by yumlevi** [comment]
Ok, it does work if you remove mixed precision in the config and accelerate config, if I had to guess I'd say it's something to do with the vae not being fp16 vs the rest of the model and accelerate fuckery

**Comment by lifeisboringsoprogramming** [comment]
@yumlevi may I know how much VRAM for each of your GPU? how many GPU do you have? how much VRAM I need to train the SDXL LoRA model? thank you very much

**Comment by yumlevi** [comment]
> @yumlevi may I know how much VRAM for each of your GPU? how many GPU do you have? how much VRAM I need to train the SDXL LoRA model? thank you very much

A100 80GB x 8

**Comment by lifeisboringsoprogramming** [comment]
@yumlevi Great thank you very much
