### ISSUE TITLE
RuntimeError: NaN detected in latents

### ISSUE THREAD

**Issue by D3voz** [kohya-ss/sd-scripts#653]
Getting NaN error while trying to use sdxl finetune . 

Enable xformers for U-Net
[Dataset 0]
caching latents.
checking cache validity...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                   | 0/110 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\github\d\sd-scripts\sdxl_train.py", line 631, in <module>
    train(args)
  File "C:\github\d\sd-scripts\sdxl_train.py", line 185, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "C:\github\d\sd-scripts\library\train_util.py", line 1681, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "C:\github\d\sd-scripts\library\train_util.py", line 845, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "C:\github\d\sd-scripts\library\train_util.py", line 2008, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: C:\github\lora\images\4_genesis\File 1.png
Traceback (most recent call last):
  File "C:\Users\Deva\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Deva\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\github\d\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\github\d\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\github\d\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 918, in launch_command
    simple_launcher(args)
  File "C:\github\d\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\github\\d\\sd-scripts\\venv\\Scripts\\python.exe', 'sdxl_train.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/github/sdxl_base.safetensors', '--output_dir=C:\\github\\lora\\models', '--output_name=genesisft', '--enable_bucket', '--train_data_dir=C:\\github\\lora\\images', '--resolution=1024,1024', '--save_model_as=safetensors', '--learning_rate=5e-6', '--max_train_steps=5000', '--train_batch_size=1', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_data_loader_n_workers=0', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--cache_text_encoder_outputs', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--caption_extension', "='.txt'"]' returned non-zero exit status 1.

**Comment by lifeisboringsoprogramming** [comment]
I think related to
https://github.com/kohya-ss/sd-scripts/issues/636

**Comment by D3voz** [comment]
no half vae fixed it, thanks. waiting for training to finish, taking almost all of 24gb vram .

**Comment by Humanoidme** [comment]
How do you fix no half vae ?

**Comment by lifeisboringsoprogramming** [comment]
https://youtu.be/iNwB98P3V0k

**Comment by wq1314521** [comment]
This error may be a problem with the VAE model, and it should be solved by changing the VAE.
