### ISSUE TITLE
how to use sdxl_train_network.py

### ISSUE THREAD

**Issue by MaxTran96** [kohya-ss/sd-scripts#665]
Hi, how do i use this script? What arguments i need to pass in?

https://github.com/kohya-ss/sd-scripts/blob/sdxl/sdxl_train_network.py

**Comment by MaxTran96** [comment]
Thanks! How do i use this script? https://github.com/kohya-ss/sd-scripts/blob/sdxl/sdxl_gen_img.py
I also tried using https://github.com/kohya-ss/sd-scripts/blob/sdxl/sdxl_minimal_inference.py but i got an error about missing dict type. I'll post the full error here

**Comment by MaxTran96** [comment]
python3 /home/ubuntu/content/sd-scripts/sdxl_minimal_inference.py --ckpt_path /home/ubuntu/content/VenusAI/Sessions/test/models/checkpoints/1000_lr1e-5_cosine.safetensors --interactive --output_dir=/home/ubuntu/content/VenusAI/out/

building U-Net
loading U-Net from checkpoint
Traceback (most recent call last):
  File "/home/ubuntu/content/sd-scripts/sdxl_minimal_inference.py", line 114, in <module>
    text_model1, text_model2, vae, unet, _, _ = sdxl_model_util.load_models_from_sdxl_checkpoint(
  File "/home/ubuntu/content/sd-scripts/library/sdxl_model_util.py", line 166, in load_models_from_sdxl_checkpoint
    info = unet.load_state_dict(unet_sd)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SdxlUNet2DConditionModel:
	Missing key(s) in state_dict: "time_embed.0.weight", "time_embed.0.bias", "time_embed.2.weight", "time_embed.2.bias", "label_emb.0.0.weight", "label_emb.0.0.bias", "label_emb.0.2.weight", "label_emb.0.2.bias", "input_blocks.0.0.weight", "input_blocks.0.0.bias", "input_blocks.1.0.in_layers.0.weight", "input_blocks.1.0.in_layers.0.bias", "input_blocks.1.0.in_layers.2.weight", "input_blocks.1.0.in_layers.2.bias", "input_blocks.1.0.emb_layers.1.weight", "input_blocks.1.0.emb_layers.1.bias", "input_blocks.1.0.out_layers.0.weight", "input_blocks.1.0.out_layers.0.bias", "input_blocks.1.0.out_layers.3.weight", "input_blocks.1.0.out_layers.3.bias", "input_blocks.2.0.in_layers.0.weight", "input_blocks.2.0.in_layers.0.bias", "input_blocks.2.0.in_layers.2.weight", "input_blocks.2.0.in_layers.2.bias", "input_blocks.2.0.emb_layers.1.weight", "input_blocks.2.0.emb_layers.1.bias", "input_blocks.2.0.out_layers.0.weight", "input_blocks.2.0.out_layers.0.bias", "input_blocks.2.0.out_layers.3.weight", "input_blocks.2.0.out_layers.3.bias", "input_blocks.3.0.op.weight", "input_blocks.3.0.op.bias", "input_blocks.4.0.in_layers.0.weight", "input_blocks.4.0.in_layers.0.bias", "input_blocks.4.0.in_layers.2.weight", "input_blocks.4.0.in_layers.2.bias", "input_blocks.4.0.emb_layers.1.weight", "input_blocks.4.0.emb_layers.1.bias", "input_blocks.4.0.out_layers.0.weight", "input_blocks.4.0.out_layers.0.bias", "input_blocks.4.0.out_layers.3.weight", "input_blocks.4.0.out_layers.3.bias", "input_blocks.4.0.skip_connection.weight", "input_blocks.4.0.skip_connection.bias", "input_blocks.4.1.norm.weight", "input_blocks.4.1.norm.bias", "input_blocks.4.1.proj_in.weight", "input_blocks.4.1.proj_in.bias", "input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.norm1.weight", "input_blocks.4.1.transformer_blocks.0.norm1.bias", "input_blocks.4.1.transformer_blocks.0.norm2.weight", "input_blocks.4.1.transformer_blocks.0.norm2.bias", "input_blocks.4.1.transformer_blocks.0.norm3.weight", "input_blocks.4.1.transformer_blocks.0.norm3.bias", "input_blocks.4.1.transformer_blocks.1.attn1.to_q.weight", "input_blocks.4.1.transformer_blocks.1.attn1.to_k.weight", "input_blocks.4.1.transformer_blocks.1.attn1.to_v.weight", "input_blocks.4.1.transformer_blocks.1.attn1.to_out.0.weight", "input_blocks.4.1.transformer_blocks.1.attn1.to_out.0.bias", "input_blocks.4.1.transformer_blocks.1.ff.net.0.proj.weight", "input_blocks.4.1.transformer_blocks.1.ff.net.0.proj.bias", "input_blocks.4.1.transformer_blocks.1.ff.net.2.weight", "input_blocks.4.1.transformer_blocks.1.ff.net.2.bias", "input_blocks.4.1.transformer_blocks.1.attn2.to_q.weight", "input_blocks.4.1.transformer_blocks.1.attn2.to_k.weight", "input_blocks.4.1.transformer_blocks.1.attn2.to_v.weight", "input_blocks.4.1.transformer_blocks.1.attn2.to_out.0.weight", "input_blocks.4.1.transformer_blocks.1.attn2.to_out.0.bias", "input_blocks.4.1.transformer_blocks.1.norm1.weight", "input_blocks.4.1.transformer_blocks.1.norm1.bias", "input_blocks.4.1.transformer_blocks.1.norm2.weight", "input_blocks.4.1.transformer_blocks.1.norm2.bias", "input_blocks.4.1.transformer_blocks.1.norm3.weight", "input_blocks.4.1.transformer_blocks.1.norm3.bias", "input_blocks.4.1.proj_out.weight", "input_blocks.4.1.proj_out.bias", "input_blocks.5.0.in_layers.0.weight", "input_blocks.5.0.in_layers.0.bias", "input_blocks.5.0.in_layers.2.weight", "input_blocks.5.0.in_layers.2.bias", "input_blocks.5.0.emb_layers.1.weight", "input_blocks.5.0.emb_layers.1.bias", "input_blocks.5.0.out_layers.0.weight", "input_blocks.5.0.out_layers.0.bias", "input_blocks.5.0.out_layers.3.weight", "input_blocks.5.0.out_layers.3.bias", "input_blocks.5.1.norm.weight", "input_blocks.5.1.norm.bias", "input_blocks.5.1.proj_in.weight", "input_blocks.5.1.proj_in.bias", "input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias"

**Comment by MaxTran96** [comment]
Thanks and where do i get that lora_weight? for training i only pass in the safetensor file of sdxl, i dont remember passing in the lora weight. Also how would i use this script? https://github.com/kohya-ss/sd-scripts/blob/sdxl/sdxl_gen_img.py

**Comment by MaxTran96** [comment]
and i think i already passed in ckpt_path, that's why i got the error above

**Comment by MaxTran96** [comment]
Oh, so the output of sdxl training is lora weight if i use ./sdxl_train_network.py right? then ckpt_path is the actual sdxl model. Got it
