### ISSUE TITLE
lora_diffusers.py throwing AssertionError

### ISSUE THREAD

**Issue by AI-Casanova** [kohya-ss/sd-scripts#708]
Attempting to use `lora_diffusers.py` from the SDXL branch

`python lora_diffusers.py --model_id stabilityai/stable-diffusion-xl-base-1.0 --sdxl --lora_weights /content/sd_xl_offset_example-lora_1.0.safetensors`

Returns this error:

```
Loading pipeline components...: 100% 7/7 [00:44<00:00,  6.40s/it]
load LoRA weights from /content/sd_xl_offset_example-lora_1.0.safetensors
create LoRA network
create LoRA network from weights
converted 788 Stability AI's U-Net LoRA modules to Diffusers (SDXL)
create LoRA for Text Encoder: 0 modules.
skipped 264 modules because of missing weight.
[]
create LoRA for U-Net: 560 modules.
Traceback (most recent call last):
  File "/content/lora_diffusers.py", line 515, in <module>
    lora_network: LoRANetwork = create_network_from_weights(text_encoders, pipe.unet, lora_sd, multiplier=1.0)
  File "/content/lora_diffusers.py", line 257, in create_network_from_weights
    return LoRANetwork(text_encoder, unet, multiplier=multiplier, modules_dim=modules_dim, modules_alpha=modules_alpha)
  File "/content/lora_diffusers.py", line 381, in __init__
    assert lora_name in names, f"{lora_name} is not found in created LoRA modules."
AssertionError: lora_unet_down_blocks_0_resnets_0_time_emb_proj is not found in created LoRA modules.
```

I'm trying to create a lora loader for SD.Next that takes Diffusers out of the loop, and am getting stymied here.

**Comment by AI-Casanova** [comment]
Doh, downgrading diffusers fixed the issue, but leaves me no closer to my goals as I need the newer version.

**Comment by AI-Casanova** [comment]
For future reference, replacing `"Linear"` with `"LoRACompatibleLinear"` and `"Conv2d"` with `"LoRACompatibleConv"`

Seems to work for updated diffusers
