### ISSUE TITLE
SDXL training issue, recommended to open an issue here.

### ISSUE THREAD

**Issue by Nthompson096** [kohya-ss/sd-scripts#725]
Original issue: https://github.com/bmaltais/kohya_ss/issues/1335

Basically was recommend to open an issue here; as the problem appears to be a trainer code, error will still persist.

**Comment by Nthompson096** [comment]
Was able to generate an image with it just fine on an AMD card; also have a NVIDIA card inside my system.
![image](https://github.com/kohya-ss/sd-scripts/assets/68661602/4b1dea8c-b968-4bf1-9d2c-589246e833e8)

**Comment by Nthompson096** [comment]
Wait, nvm; wasn't able to load the model inside my webui; false alarm.

**Comment by Nthompson096** [comment]
```
changing setting sd_model_checkpoint to sd_xl_base_1.0.safetensors [f1298ceb4a]: SafetensorError
Traceback (most recent call last):
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/modules/shared.py", line 633, in set
    self.data_labels[key].onchange()
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/modules/call_queue.py", line 14, in f
    res = func(*args, **kwargs)
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/webui.py", line 238, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()), call=False)
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/modules/sd_models.py", line 570, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/modules/sd_models.py", line 277, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/modules/sd_models.py", line 253, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/home/nicholas/Desktop/SSD/AI/stable-diffusion-webui/venvamd/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```
I'll see about re downloading it.

**Comment by Nthompson096** [comment]
Was able to successfully generate an image; will see if I can train an image.
![image](https://github.com/kohya-ss/sd-scripts/assets/68661602/7a33db68-b17c-4a11-9287-ec9282a01f6f)
![image](https://github.com/kohya-ss/sd-scripts/assets/68661602/aa1954aa-bf03-41da-aa90-4e6518aa9048)

**Comment by Nthompson096** [comment]
```
caching latents...
  0%|                                                                                                                              | 0/19 [00:01<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./sdxl_train_network.py:174 in <module>                   │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/train_network.py:252 in train                             │
│                                                                                                  │
│   249 │   │   │   vae.requires_grad_(False)                                                      │
│   250 │   │   │   vae.eval()                                                                     │
│   251 │   │   │   with torch.no_grad():                                                          │
│ ❱ 252 │   │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_l   │
│   253 │   │   │   vae.to("cpu")                                                                  │
│   254 │   │   │   if torch.cuda.is_available():                                                  │
│   255 │   │   │   │   torch.cuda.empty_cache()                                                   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:1824 in cache_latents               │
│                                                                                                  │
│   1821 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1822 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1823 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1824 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1825 │                                                                                         │
│   1826 │   def cache_text_encoder_outputs(                                                       │
│   1827 │   │   self, tokenizers, text_encoders, device, weight_dtype, cache_to_disk=False, is_m  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:873 in cache_latents                │
│                                                                                                  │
│    870 │   │   # iterate batches: batch doesn't have image, image will be loaded in cache_batch  │
│    871 │   │   print("caching latents...")                                                       │
│    872 │   │   for batch in tqdm(batches, smoothing=1, total=len(batches)):                      │
│ ❱  873 │   │   │   cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.rando  │
│    874 │                                                                                         │
│    875 │   # weight_dtypeを指定するとText Encoderそのもの、およひ出力がweight_dtypeになる        │
│    876 │   # SDXLでのみ有効だが、datasetのメソッドとする必要があるので、sdxl_train_util.pyでは   │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:2160 in cache_batch_latents         │
│                                                                                                  │
│   2157 │   for info, latent, flipped_latent in zip(image_infos, latents, flipped_latents):       │
│   2158 │   │   # check NaN                                                                       │
│   2159 │   │   if torch.isnan(latents).any() or (flipped_latent is not None and torch.isnan(fli  │
│ ❱ 2160 │   │   │   raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")          │
│   2161 │   │                                                                                     │
│   2162 │   │   if cache_to_disk:                                                                 │
│   2163 │   │   │   save_latents_to_disk(info.latents_npz, latent, info.latents_original_size, i  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: NaN detected in latents: 
/home/nicholas/Desktop/laptop/training/shodan/images/79_prompt/00001-0-shodan_5_by_5465646465464_dbxigig-fullview.png
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/bin/accelerate:8 in <module>                         │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Nthompson096** [comment]
Got the same issue as before when entering the command prior in my console instead of gui in https://github.com/bmaltais/kohya_ss/issues/1335#issuecomment-1666876723

**Comment by Nthompson096** [comment]
Great and bad news!
First the bad news :(
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./sdxl_train_network.py:174 in <module>                   │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/train_network.py:378 in train                             │
│                                                                                                  │
│   375 │   │   # TODO めちゃくちゃ冗長なのでコードを整理する                                      │
│   376 │   │   if train_unet and train_text_encoder:                                              │
│   377 │   │   │   if len(text_encoders) > 1:                                                     │
│ ❱ 378 │   │   │   │   unet, t_enc1, t_enc2, network, optimizer, train_dataloader, lr_scheduler   │
│   379 │   │   │   │   │   unet, text_encoders[0], text_encoders[1], network, optimizer, train_   │
│   380 │   │   │   │   )                                                                          │
│   381 │   │   │   │   text_encoder = text_encoders = [t_enc1, t_enc2]                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator. │
│ py:1143 in prepare                                                                               │
│                                                                                                  │
│   1140 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│ ❱ 1143 │   │   │   result = tuple(                                                               │
│   1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator. │
│ py:1144 in <genexpr>                                                                             │
│                                                                                                  │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│   1143 │   │   │   result = tuple(                                                               │
│ ❱ 1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│   1147                                                                                           │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator. │
│ py:995 in _prepare_one                                                                           │
│                                                                                                  │
│    992 │   │   │   if isinstance(obj, torch.utils.data.DataLoader):                              │
│    993 │   │   │   │   return self.prepare_data_loader(obj, device_placement=device_placement)   │
│    994 │   │   │   elif isinstance(obj, torch.nn.Module):                                        │
│ ❱  995 │   │   │   │   return self.prepare_model(obj, device_placement=device_placement)         │
│    996 │   │   │   elif isinstance(obj, torch.optim.Optimizer):                                  │
│    997 │   │   │   │   optimizer = self.prepare_optimizer(obj, device_placement=device_placemen  │
│    998 │   │   │   │   return optimizer                                                          │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator. │
│ py:1218 in prepare_model                                                                         │
│                                                                                                  │
│   1215 │   │   │   │   │   "You can't train a model that has been loaded in 8-bit precision wit  │
│   1216 │   │   │   │   )                                                                         │
│   1217 │   │   elif device_placement and not has_hf_device_map:                                  │
│ ❱ 1218 │   │   │   model = model.to(self.device)                                                 │
│   1219 │   │                                                                                     │
│   1220 │   │   if self.distributed_type == DistributedType.MULTI_GPU:                            │
│   1221 │   │   │   if any(p.requires_grad for p in model.parameters()):                          │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:1145 in to                                                                                   │
│                                                                                                  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│   1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│ ❱ 1145 │   │   return self._apply(convert)                                                       │
│   1146 │                                                                                         │
│   1147 │   def register_full_backward_pre_hook(                                                  │
│   1148 │   │   self,                                                                             │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:797 in _apply                                                                                │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:797 in _apply                                                                                │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:820 in _apply                                                                                │
│                                                                                                  │
│    817 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    818 │   │   │   # `with torch.no_grad():`                                                     │
│    819 │   │   │   with torch.no_grad():                                                         │
│ ❱  820 │   │   │   │   param_applied = fn(param)                                                 │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    822 │   │   │   if should_use_set_data:                                                       │
│    823 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:1143 in convert                                                                              │
│                                                                                                  │
│   1140 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│   1141 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱ 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│   1145 │   │   return self._apply(convert)                                                       │
│   1146                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.76 GiB total capacity; 10.92 GiB already allocated; 56.25 MiB free; 10.97 GiB
reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for 
Memory Management and PYTORCH_CUDA_ALLOC_CONF
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/bin/accelerate:8 in <module>                         │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```
Ran out of memory on my 3060 12GB

Good news I was able to attempt training; meaning the command args were good enough to run! the card may be the only issue here (don't feel like buying another lol).

**Comment by Nthompson096** [comment]
Curious what the specifics for training on SDXL is; what card would be needed? would you have to use cloud?

**Comment by g2asell2019** [comment]
> NaN detected in latents: 
enable no-half-vae

> what card would be needed (VRAM)

12GB VRAM is enough for bz of 3 but need 8 for dim and rank

**Comment by Nthompson096** [comment]
@g2asell2019 

used the GUI.sh script this time; had this error.

```
use AdamW optimizer | {'decouple': True, 'weight_decay': 0.5, 'betas': (0.9, 0.99), 'use_bias_correction': False}
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/./sdxl_train_network.py:174 in <module>                   │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/train_network.py:325 in train                             │
│                                                                                                  │
│   322 │   │   │   )                                                                              │
│   323 │   │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, ar   │
│   324 │   │                                                                                      │
│ ❱ 325 │   │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, train   │
│   326 │   │                                                                                      │
│   327 │   │   # dataloaderを準備する                                                             │
│   328 │   │   # DataLoaderのプロセス数：0はメインプロセスになる                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/library/train_util.py:3360 in get_optimizer               │
│                                                                                                  │
│   3357 │   elif optimizer_type == "AdamW".lower():                                               │
│   3358 │   │   print(f"use AdamW optimizer | {optimizer_kwargs}")                                │
│   3359 │   │   optimizer_class = torch.optim.AdamW                                               │
│ ❱ 3360 │   │   optimizer = optimizer_class(trainable_params, lr=lr, **optimizer_kwargs)          │
│   3361 │                                                                                         │
│   3362 │   else:                                                                                 │
│   3363 │   │   # 任意のoptimizerを使う                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: AdamW.__init__() got an unexpected keyword argument 'decouple'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/bin/accelerate:8 in <module>                         │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /home/nicholas/Desktop/SSD/AI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Nthompson096** [comment]
enabled no-half-vae inside sdxl settings.

**Comment by Nthompson096** [comment]
Figured it out, had to reduce the max resolution to 512,512 batch size to 3 and dimensions to 8 as @g2asell2019 recommended; here's my config file; also had to change my Optimizer to Prodigy.

config file for those who may come across this:
```
{
  "LoRA_type": "Standard",
  "adaptive_noise_scale": 0,
  "additional_parameters": "--max_grad_norm=0",
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": true,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_skip": "1",
  "color_aug": false,
  "conv_alpha": 4,
  "conv_block_alphas": "",
  "conv_block_dims": "",
  "conv_dim": 8,
  "decompose_both": false,
  "dim_from_weights": false,
  "down_lr_weight": "",
  "enable_bucket": true,
  "epoch": 20,
  "factor": -1,
  "flip_aug": false,
  "full_bf16": false,
  "full_fp16": false,
  "gradient_accumulation_steps": 1.0,
  "gradient_checkpointing": true,
  "keep_tokens": "0",
  "learning_rate": 1.0,
  "logging_dir": "/path/to/logs",
  "lora_network_weights": "",
  "lr_scheduler": "cosine",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": "0",
  "max_resolution": "512,512",
  "max_timestep": 1000,
  "max_token_length": "75",
  "max_train_epochs": "",
  "mem_eff_attn": false,
  "mid_lr_weight": "",
  "min_bucket_reso": 64,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "model_list": "custom",
  "module_dropout": 0,
  "multires_noise_discount": 0.2,
  "multires_noise_iterations": 8,
  "network_alpha": 16,
  "network_dim": 8,
  "network_dropout": 0,
  "no_token_padding": false,
  "noise_offset": 0.0357,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "optimizer": "Prodigy",
  "optimizer_args": "decouple=True weight_decay=0.5 betas=0.9,0.99 use_bias_correction=False",
  "output_dir": "path/to/models",
  "output_name": "whatever",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "path/to/sd_xl_base_1.0.safetensors",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "rank_dropout": 0,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 0,
  "sample_every_n_steps": 24,
  "sample_prompts": "edit this prompt line here",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 2,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 1,
  "sdxl": true,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": "",
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 1.0,
  "train_batch_size": 3,
  "train_data_dir": "path/to/images",
  "train_on_input": false,
  "training_comment": "rentry.co/ProdiAgy",
  "unet_lr": 1.0,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": true,
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "weighted_captions": false,
  "xformers": true
}
```
