### ISSUE TITLE
An error occur when using latest version of 'train_network.py' to save LoRA models

### ISSUE THREAD

**Issue by zakinp** [kohya-ss/sd-scripts#727]
An error occur when using latest version of 'train_network.py' to train and save LoRA models:

```
Traceback (most recent call last):
  File "/root/autodl-tmp/sd-scripts/train_network.py", line 990, in <module>
    trainer.train(args)
  File "/root/autodl-tmp/sd-scripts/train_network.py", line 869, in train
    save_model(ckpt_name, accelerator.unwrap_model(network), global_step, epoch + 1)
  File "/root/autodl-tmp/sd-scripts/train_network.py", line 711, in save_model
    unwrapped_nw.save_weights(ckpt_file, save_dtype, metadata_to_save)
  File "/root/autodl-tmp/sd-scripts/networks/lora.py", line 1095, in save_weights
    save_file(state_dict, file, metadata)
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/safetensors/torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
TypeError: argument 'metadata': 'int' object cannot be converted to 'PyString'
steps:   5%|██████▋                                                                                                                              | 30/600 [00:32<10:23,  1.09s/it, loss=0.102]
Traceback (most recent call last):
  File "/root/miniconda3/envs/kohya/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/kohya/bin/python', '/root/autodl-tmp/sd-scripts/train_network.py', '--pretrained_model_name_or_path=/root/autodl-tmp/nai-animefull-fixed.safetensors', '--output_dir=/root/autodl-tmp/cocolic-v1-nai', '--output_name=cocolic-v1-nai', '--save_every_n_epochs=1', '--train_batch_size=4', '--max_token_length=225', '--learning_rate=1', '--unet_lr=1', '--text_encoder_lr=1', '--optimizer_type=prodigy', '--optimizer_args', 'weight_decay=0.01', 'decouple=True', 'use_bias_correction=True', '--max_train_epochs=20', '--gradient_accumulation_steps=1', '--mixed_precision=bf16', '--save_precision=fp16', '--xformers', '--clip_skip=2', '--logging_dir=logs', '--log_with=tensorboard', '--sample_every_n_epochs=1', '--sample_prompts=/root/autodl-tmp/prompt.txt', '--sample_sampler=dpmsolver++', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=1', '--train_data_dir=/root/autodl-tmp/loradata/image_dir', '--shuffle_caption', '--caption_extension=.txt', '--keep_tokens=1', '--resolution=1024,1024', '--max_bucket_reso=1536', '--bucket_no_upscale', '--enable_bucket', '--multires_noise_iterations=6', '--multires_noise_discount=0.3', '--min_snr_gamma=5', '--max_grad_norm=1', '--cache_latents', '--vae_batch_size=4', '--persistent_data_loader_workers', '--max_data_loader_n_workers=4', '--reg_data_dir=/root/autodl-tmp/loradata/reg_dir', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_dim=128', '--network_alpha=64']' returned non-zero exit status 1.
```

**Comment by zakinp** [comment]
A temporary solution to this problem is to modify line 1095 of the 'sd-scripts/network/lora.py' file, changing
``` Python
save_file(state_dict, file, metadata)
```
to
``` Python
save_file(state_dict, file)
```

**Comment by KdaiP** [comment]
facing the same error

**Comment by KdaiP** [comment]
> Sorry, the LoRA with clip skip causes an error in sdxl branch. I've fixed.

Thank you, the new script works well!
