### ISSUE TITLE
merge SD2.1 Lora models error 

### ISSUE THREAD

**Issue by axel578** [kohya-ss/sd-scripts#745]
I want to merge SD2.1 512 with three loras trained on it
I have this error:
```
(venv) PS \sd-scripts> py "networks\merge_lora.py" --sd_model "Documents/webui/stable-diffusion-webui/models/Stable-diffusion/v2-1_512-ema-pruned.safetensors" --save_precision fp16 --precision float --save_to "webui/stable-diffusion-webui/models/Stable-diffusion/newmodel.safetensors" --models "webui/stable-diffusion-webui/models/Lora/pixel3D_v1-000020.safetensors" "webui/stable-diffusion-webui/models/Lora/pixel3D-000030.safetensors" "webui/stable-diffusion-webui/models/Lora/pixel3D_v2-000040.safetensors" --ratios 0.22 0.22 0.22
loading SD model: webui/stable-diffusion-webui/models/Stable-diffusion/v2-1_512-ema-pruned.safetensors
Traceback (most recent call last):
  File "sd-scripts\networks\merge_lora.py", line 243, in <module>
    merge(args)
  File "sd-scripts\networks\merge_lora.py", line 192, in merge
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.sd_model)
  File "sd-scripts\venv\lib\site-packages\library\model_util.py", line 868, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for down_blocks.0.attentions.0.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
```

**Comment by tamlog06** [comment]
I have met the same error.
