### ISSUE TITLE
Torch-2.1.0 being installed by pip install -r requirements.txt causing error? (Kaggle env)

### ISSUE THREAD

**Issue by DKnight54** [kohya-ss/sd-scripts#862]
This just started happening today for me, but for some reason, Torch 2.1.0 is being installed along side the requirements, even though torch 2.0.0 is already installed (possibly due to new version of Torch released recently?
![image](https://github.com/kohya-ss/sd-scripts/assets/126916963/f26234b3-c2db-486c-a853-024801a25ae2)
 
![image](https://github.com/kohya-ss/sd-scripts/assets/126916963/5d79e6ab-5287-4af9-9701-65c7c8241652)
Unfortunately, this seems to be causing issues when starting the training as it causes the training script to throw the following error:

```
use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init': False}

Traceback (most recent call last):
  File "/kaggle/temp/sd-scripts/sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "/kaggle/temp/sd-scripts/train_network.py", line 388, in train
    unet, t_enc1, t_enc2, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1284, in prepare
    result = tuple(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1482, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(model, **kwargs)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 678, in __init__
    self._log_and_throw(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1037, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
Traceback (most recent call last):
  File "/kaggle/temp/sd-scripts/sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "/kaggle/temp/sd-scripts/train_network.py", line 388, in train
    unet, t_enc1, t_enc2, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1284, in prepare
    result = tuple(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1482, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(model, **kwargs)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 678, in __init__
    self._log_and_throw(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1037, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
[2023-10-07 03:30:21,237] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 781) of binary: /kaggle/temp/venv/bin/python
Traceback (most recent call last):
  File "/kaggle/temp/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/kaggle/temp/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/kaggle/temp/sd-scripts/sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-07_03:30:21
  host      : ae6011be55b8
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 782)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-07_03:30:21
  host      : ae6011be55b8
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 781)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

I was able to workaround this issue by manually installing torch 2.0.0 using the following to override the default versions installed:
```
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 torchtext==0.15.1 torchdata==0.6.0 --extra-index-url https://download.pytorch.org/whl/cu118 -U
pip install xformers==0.0.19 triton==2.0.0 -U
```

I've attached the config and dataset toml files.
[torch_error.zip](https://github.com/kohya-ss/sd-scripts/files/12837263/torch_error.zip)

**Comment by DKnight54** [comment]
Have not tested in other enviroments, but assuming there are similar issues, then would probably need to add a upper version limit to the torch in the requirements.txt

**Comment by DKnight54** [comment]
@kohya-ss Nope, pulling directly from this repo.
![image](https://github.com/kohya-ss/sd-scripts/assets/126916963/5602b88b-753c-482b-92c0-6f2b53a0fea4)

As best as I can guess, Torch is being updated from 2.0.0 in the env to 2.1.0 because it's a dependency of one of the packages (Don't ask me which, I've no idea. Tentatively maybe tensorboard), and that package's requirements only requires it to be higher than torch 1.10.0

**Comment by DKnight54** [comment]
> It is recommended to install PyTorch before installing `requirements.txt` in the installation guide. Please reverse the order of these commands.

Tested, and you are correct. Doing it that way gives the correct torch version. Thanks!
