### ISSUE TITLE
AttributeError: type object 'GenerationMixin' has no attribute '_prepare_input_ids_for_generation'. Did you mean: 'prepare_inputs_for_generation'?

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#869]
When I try to caption images with GIT this is the below error

```
21:53:51-679893 INFO     GIT captioning files in E:\MarMar 2500 usd game assets\GIT...
21:53:51-680893 INFO     ./venv/Scripts/python.exe finetune/make_captions_by_git.py --batch_size="1" --max_data_loader_n_workers="2"
                         --max_length="75" --caption_extension=".txt" "E:\MarMar 2500 usd game assets\GIT"
Traceback (most recent call last):
  File "F:\kohya_ss\finetune\make_captions_by_git.py", line 172, in <module>
    main(args)
  File "F:\kohya_ss\finetune\make_captions_by_git.py", line 56, in main
    org_prepare_input_ids_for_generation = GenerationMixin._prepare_input_ids_for_generation
AttributeError: type object 'GenerationMixin' has no attribute '_prepare_input_ids_for_generation'. Did you mean: 'prepare_inputs_for_generation'?
21:53:55-194493 INFO     ...captioning done
```

**Comment by FurkanGozukara** [comment]
> Thank you for reporting! This was caused by upgrading of transformers. The latest transformers seems to support the batch size > 1, so I've removed the patch for it.

thank you so much
