### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by radry** [kohya-ss/sd-scripts#887]
Please make it compatible with Python 3.11

```
19:29:42-761975 INFO     Version: v22.1.0

19:29:42-763290 INFO     Python 3.11.5 on Windows
19:29:42-764301 ERROR    Incompatible Python version: 3.11.5 required 3.[9, 10]
19:29:42-769301 INFO     Installing modules from requirements_windows_torch2.txt...
19:29:42-771302 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
19:29:46-516313 INFO     Installing package: bitsandbytes==0.35.0
19:29:49-040160 INFO     Installing modules from requirements.txt...
19:29:49-049159 INFO     Installing package: -e .
19:29:54-016745 ERROR    Error running pip: install --upgrade -e .
19:29:54-018746 INFO     Copying bitsandbytes files...
19:29:54-020745 INFO     Configuring accelerate...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 21, in <module>
    from accelerate.commands.estimate import estimate_command_parser
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\commands\estimate.py", line 35, in <module>
    import timm
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
```

**Comment by radry** [comment]
Ok. I did some research and I think Python 3.11 is still a problem because there is no xformers version that supports it.
