### ISSUE TITLE
`sdxl_train.py` Dreambooth - `NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154`

### ISSUE THREAD

**Issue by dseravalli** [kohya-ss/sd-scripts#888]
This is my first time trying to fine tune a stable diffusion model so there's a lot I don't understand yet.

Full stack:
```
Traceback (most recent call last):
  File "/root/sd-scripts/sdxl_train.py", line 753, in <module>
    train(args)
  File "/root/sd-scripts/sdxl_train.py", line 567, in train
    accelerator.backward(loss)
  File "/usr/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1983, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 271, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/root/sd-scripts/library/sdxl_original_unet.py", line 643, in custom_forward
    return func(*inputs)
  File "/root/sd-scripts/library/sdxl_original_unet.py", line 633, in forward_body
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/sd-scripts/library/sdxl_original_unet.py", line 577, in forward
    hidden_states = module(hidden_states)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/sd-scripts/library/sdxl_original_unet.py", line 556, in forward
    return hidden_states * self.gelu(gate)
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch. 
```

Running this on modal.com A10G function with this command:

```sh
accelerate launch --num_cpu_threads_per_process 1 /root/sd-scripts/sdxl_train.py
--pretrained_model_name_or_path=/vol/sd_xl_base_1.0.safetensors
--dataset_config=/vol/7c4230a4-10ec-4e87-820f-5c7116933590/training_config.toml
--output_dir=/vol/7c4230a4-10ec-4e87-820f-5c7116933590
--output_name=model.safetensors
--save_model_as=safetensors
--learning_rate=4e-7
--optimizer_type=AdaFactor
--xformers
--mixed_precision=fp16
--cache_latents
--cache_text_encoder_outputs
--gradient_checkpointing
--no_half_vae
```

Docker image setup:
```python
     Image.debian_slim(python_version="3.10")
    .apt_install(["ffmpeg"])
    .pip_install(
        "accelerate==0.23",
        "boto3",
        "opencv-python-headless",
        "pytorch-lightning",
        "tensorboard",
        "safetensors",
        "toml",
        "voluptuous",
        "open-clip-torch",
        "huggingface-hub",
        "datasets~=2.13",
        "diffusers[torch]",
        "einops",
        "ftfy",
        "smart_open",
        "transformers==4.30.2",
        "torch==2.0.1",
        "torchvision",
        "torchaudio",
        "triton",
        "tomli-w",
    )
    .pip_install("xformers", pre=True)
```

training config is this converted to TOML:
```python
{
        'general': {
            'enable_bucket': True
        },
        'datasets': [
            {
                'resolution': 1024,
                'batch_size': 1,
                'subsets': [
                    {
                        'image_dir': "/vol/d835023a-4ed5-4269-b323-9952930d3786/training_images",
                        'class_tokens': 'shs face',
                        'keep_tokens': 2,
                    },
                ]
            },
        ]
    }
```

**Comment by dseravalli** [comment]
This works when I use a A100 instead of a A10G, but A10G should have enough RAM at 24GB. Is it something to do with CUDA version or a pip library version?

**Comment by DKnight54** [comment]
Not gonna pretend I know the details, but seems like you might need to use a different[ CUDA 11.6](https://stackoverflow.com/questions/70022761/pytorch-version-on-g5-xlarge) if you are working with the A10G

**Comment by rachelspark** [comment]
Hi! Rachel from the Modal team here. Can you try using a this micromamba image instead? If not, there are a couple other tricks we can try.

`Image.micromamba()
    .micromamba_install(
        "cudatoolkit=11.8",
        "cudnn=8.1.0",
        "cuda-nvcc",
        channels=["conda-forge", "nvidia"],
    )
    .apt_install(...)
    .pip_install(...)
   `
