### ISSUE TITLE
RuntimeError: NaN detected in latents - cache latents not working on Kaggle any ideas?

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#892]
I am trying to do SDXL DreamBooth training on Kaggle and I got error during cache latents

```
22:37:35-020247 INFO     accelerate launch --num_cpu_threads_per_process=4      
                         "./sdxl_train.py"                                      
                         --pretrained_model_name_or_path="stabilityai/stable-dif
                         fusion-xl-base-1.0"                                    
                         --train_data_dir="/kaggle/working/train_data/img"      
                         --reg_data_dir="/kaggle/working/train_data/reg"        
                         --resolution="1024,1024"                               
                         --output_dir="/kaggle/working/train_data/model"        
                         --logging_dir="/kaggle/working/train_data/log"         
                         --save_model_as=safetensors --output_name="Kaggle_SDXL"
                         --lr_scheduler_num_cycles="1"                          
                         --max_data_loader_n_workers="0" --learning_rate="1e-05"
                         --lr_scheduler="constant" --train_batch_size="1"       
                         --max_train_steps="4160" --save_every_n_epochs="1"     
                         --mixed_precision="fp16" --save_precision="fp16"       
                         --cache_latents --cache_latents_to_disk                
                         --optimizer_type="Adafactor" --optimizer_args          
                         scale_parameter=False relative_step=False              
                         warmup_init=False weight_decay=0.01                    
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 
                         --gradient_checkpointing --full_fp16 --xformers        
                         --bucket_no_upscale --noise_offset=0.0                 
                         --max_grad_norm=0.0                                    
2023-10-21 22:37:44.702086: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-21 22:37:44.702157: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-21 22:37:44.702201: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-21 22:37:44.711956: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-21 22:37:44.712020: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-21 22:37:44.712086: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
prepare tokenizers
prepare tokenizers
Using DreamBooth method.
Using DreamBooth method.
prepare images.
found directory /kaggle/working/train_data/img/160_ohwx man contains 13 image files
No caption file found for 13 images. Training will continue without captions for these images. If class token exists, it will be used. / 13枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134600.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134620.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134646.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134712.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134753.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134833.jpg... and 8 more
prepare images.
found directory /kaggle/working/train_data/img/160_ohwx man contains 13 image files
No caption file found for 13 images. Training will continue without captions for these images. If class token exists, it will be used. / 13枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134600.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134620.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134646.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134712.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134753.jpg
/kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134833.jpg... and 8 more
found directory /kaggle/working/train_data/reg/1_man contains 4321 image files
No caption file found for 4321 images. Training will continue without captions for these images. If class token exists, it will be used. / 4321枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/kaggle/working/train_data/reg/1_man/man (1).jpg
/kaggle/working/train_data/reg/1_man/man (10).jpg
/kaggle/working/train_data/reg/1_man/man (100).jpg
/kaggle/working/train_data/reg/1_man/man (1000).jpg
/kaggle/working/train_data/reg/1_man/man (1001).jpg
/kaggle/working/train_data/reg/1_man/man (1002).jpg... and 4316 more
2080 train images with repeating.
4321 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (1024, 1024)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "/kaggle/working/train_data/img/160_ohwx man"
    image_count: 13
    num_repeats: 160
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: ohwx man
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "/kaggle/working/train_data/reg/1_man"
    image_count: 4321
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: man
    caption_extension: .caption


[Dataset 0]
loading image sizes.
found directory /kaggle/working/train_data/reg/1_man contains 4321 image files
  0%|                                                  | 0/2093 [00:00<?, ?it/s]No caption file found for 4321 images. Training will continue without captions for these images. If class token exists, it will be used. / 4321枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/kaggle/working/train_data/reg/1_man/man (1).jpg
/kaggle/working/train_data/reg/1_man/man (10).jpg
/kaggle/working/train_data/reg/1_man/man (100).jpg
/kaggle/working/train_data/reg/1_man/man (1000).jpg
/kaggle/working/train_data/reg/1_man/man (1001).jpg
/kaggle/working/train_data/reg/1_man/man (1002).jpg... and 4316 more
2080 train images with repeating.
4321 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (1024, 1024)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "/kaggle/working/train_data/img/160_ohwx man"
    image_count: 13
    num_repeats: 160
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: ohwx man
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "/kaggle/working/train_data/reg/1_man"
    image_count: 4321
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: man
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████| 2093/2093 [00:00<00:00, 8606.96it/s]
prepare dataset
prepare accelerator
100%|█████████████████████████████████████| 2093/2093 [00:00<00:00, 8792.27it/s]
prepare dataset
prepare accelerator
loading model for process 0/2
load Diffusers pretrained models: stabilityai/stable-diffusion-xl-base-1.0, variant=fp16
Loading pipeline components...: 100%|█████████████| 6/6 [00:02<00:00,  2.21it/s]
U-Net converted to original U-Net
loading model for process 1/2
load Diffusers pretrained models: stabilityai/stable-diffusion-xl-base-1.0, variant=fp16
Loading pipeline components...: 100%|█████████████| 6/6 [00:02<00:00,  2.34it/s]
U-Net converted to original U-Net
Disable Diffusers' xformers
Enable xformers for U-NetEnable xformers for U-Net

[Dataset 0]
caching latents.
[Dataset 0]
caching latents.
checking cache validity...
  0%|                                                  | 0/2093 [00:00<?, ?it/s]checking cache validity...
100%|███████████████████████████████████| 2093/2093 [00:00<00:00, 187542.53it/s]
100%|████████████████████████████████████| 2093/2093 [00:00<00:00, 67022.53it/s]
caching latents...
  0%|                                                  | 0/2093 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/kaggle/working/kohya_ss/./sdxl_train.py", line 753, in <module>
    train(args)
  File "/kaggle/working/kohya_ss/./sdxl_train.py", line 265, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "/kaggle/working/kohya_ss/library/train_util.py", line 1879, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "/kaggle/working/kohya_ss/library/train_util.py", line 914, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "/kaggle/working/kohya_ss/library/train_util.py", line 2222, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: /kaggle/working/train_data/img/160_ohwx man/IMG_20230430_134600.jpg
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./sdxl_train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-21_22:38:10
  host      : 9b3c0eb23c66
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1337)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by FurkanGozukara** [comment]
FP16 VAE solved it nice

I am preparing a notebook
