### ISSUE TITLE
FP32 XL base can't be used to train with but no issues for inference.

### ISSUE THREAD

**Issue by DarkAlchy** [kohya-ss/sd-scripts#917]
Traceback (most recent call last):
  File "F:\kohya_ss-win\sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "F:\kohya_ss-win\train_network.py", line 224, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "F:\kohya_ss-win\sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "F:\kohya_ss-win\library\sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "F:\kohya_ss-win\library\sdxl_train_util.py", line 75, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "F:\kohya_ss-win\library\sdxl_model_util.py", line 270, in load_models_from_sdxl_checkpoint
    info2 = _load_state_dict_on_device(text_model2, converted_sd, device=map_location)  # remain fp32
  File "F:\kohya_ss-win\library\sdxl_model_util.py", line 158, in _load_state_dict_on_device
    raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CLIPTextModelWithProjection:
        Unexpected key(s) in state_dict: "text_projection.weight.weight".
        Missing key(s) in state_dict: "text_projection.weight".

**Comment by DarkAlchy** [comment]
Here is the download link for it and its .yaml file.

https://huggingface.co/alessandro893/sdxl_base_1.0_FP32/tree/main
