### ISSUE TITLE
Linux train sdxl1.0 Error：Error while deserializing header: MetadataIncompleteBuffer，

### ISSUE THREAD

**Issue by soybeanxiaobi** [kohya-ss/sd-scripts#921]
## Params
```
model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "./sd-models/CopaxTimeLessXLRemote.safetensors"
v2 = false
train_data_dir = "./tags/silva"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1_024
bucket_reso_steps = 64
output_name = "JuggernautXL_train_1102"
output_dir = "./lora"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.00001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora"
network_dim = 32
network_alpha = 32
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
seed = 1_337
clip_skip = 2
mixed_precision = "fp16"
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
```

## Error Message
```
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (1024, 1024), count: 18
mean ar error (without repeats): 0.0
v_parameterization will be unexpected / SDXL学習ではv_parameterizationは想定外の動作になります
clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: ./sd-models/CopaxTimeLessXLRemote.safetensors
Traceback (most recent call last):
  File "lora-scripts/./sd-scripts/sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "lora-scripts/sd-scripts/train_network.py", line 224, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "lora-scripts/./sd-scripts/sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "lora-scripts/sd-scripts/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "lora-scripts/sd-scripts/library/sdxl_train_util.py", line 75, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "lora-scripts/sd-scripts/library/sdxl_model_util.py", line 171, in load_models_from_sdxl_checkpoint
    state_dict = load_file(ckpt_path)  # prevent device invalid Error
  File "/.pyenv/versions/3.10.8/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
10:39:38-052005 ERROR    CompletedProcess(args=['/.pyenv/versions/3.10.8/bin/python', '-m', 
                         'accelerate.commands.launch', '--num_cpu_threads_per_process', '2', '--quiet',    
                         './sd-scripts/sdxl_train_network.py', '--config_file',                            
                         'lora-scripts/config/autosave/202
                         31103-103932.toml'], returncode=1)                                                
10:39:38-054049 ERROR    Training failed / 训练失败
```

Thanks~

**Comment by soybeanxiaobi** [comment]
> According to the error message, the safetensors file may have a broken metadata. Please make sure the file is valid.

I replaced 4 or 5 xl models and downloaded several models from https://civitai.com/ that didn't work.
just like https://civitai.com/models/133005/juggernaut-xl

**Comment by soybeanxiaobi** [comment]
Tips：Everything works fine with sd1.0 or 1.5

**Comment by soybeanxiaobi** [comment]
Does this have anything to do with it?  `load_models_from_sdxl_checkpoint map_location cpu`

**Comment by soybeanxiaobi** [comment]
```
Linux Python 3.10.11 /opt/conda/bin/python             
INFO     Torch 2.0.1                                            
Torch backend: nVidia CUDA 11.7 cuDNN 8500             
Torch detected GPU: NVIDIA A100 80GB PCIe VRAM 81085
```
