### ISSUE TITLE
 Issue with Sanitizing Function - Error Details Unclear

### ISSUE THREAD

**Issue by alfredplpl** [kohya-ss/sd-scripts#923]
Hello,

I'm currently experiencing an issue with the sanitizing function within the sd-scripts. When attempting to sanitize inputs, I encounter an error that I can't seem to decipher.

Issue Description:
I am trying to sanitize user inputs before processing, but the function throws an error every time I attempt to do so. The error message is not clear to me, and I've made sure to follow the documentation provided for the sanitizing process.

Error Message:

```bash
Invalid user config / ユーザ設定の形式が正しくないようです
Traceback (most recent call last):
  File "/mnt/my_raid/github/sd-scripts/sdxl_train.py", line 755, in <module>
    train(args)
  File "/mnt/my_raid/github/sd-scripts/sdxl_train.py", line 170, in train
    blueprint = blueprint_generator.generate(user_config, args, tokenizer=[tokenizer1, tokenizer2])
  File "/mnt/my_raid/github/sd-scripts/library/config_util.py", line 354, in generate
    sanitized_user_config = self.sanitizer.sanitize_user_config(user_config)
  File "/mnt/my_raid/github/sd-scripts/library/config_util.py", line 318, in sanitize_user_config
    return self.user_config_validator(user_config)
  File "/mnt/my_raid/github/sd-scripts/venv/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/mnt/my_raid/github/sd-scripts/venv/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/mnt/my_raid/github/sd-scripts/venv/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['/mnt/NVM/images/data_sub/00_SrW1feA9iVyHm.jpg']
```

Steps to Reproduce:

1. python finetune/merge_captions_to_metadata.py --full_path '/mnt/NVM/images/data_sub' detailed_images.json
```json
{
  "/mnt/NVM/images/data_sub/00_SrW1feA9iVyHm.jpg": {
    "caption": "The image features a woman with purple hair, wearing a black shirt and a green scarf. She is holding her shirt open, revealing her large breasts. The woman appears to be smiling and is the main focus of the scene.In the background, there are two trees, one on the left side and the other on the right side. The trees are not prominent in the image, but they do add some depth to the scene."
  },
....
}
```

2. accelerate launch --num_cpu_threads_per_process 1 sdxl_train.py --pretrained_model_name_or_path='/mnt/NVM/emix.safetensors' --output_dir='/mnt/NVM/emix' --output_name=emix-0-2 --dataset_config=detailed_images.json --save_model_as=safetensors --learning_rate=2e-6 --max_train_epoch=2 --use_8bit_adam --xformers --gradient_checkpointing --mixed_precision=bf16 --full_bf16 --min_bucket_reso=512 --max_bucket_reso=2048 

Expected Behavior:
I would expect the function to sanitize the inputs without any issues.

Actual Behavior:
The function fails and returns the above error message.

Environment:

OS: Ubuntu 20.04
Language/Runtime Version: python 3.9

I've reviewed the existing issues and pull requests but didn't find anything that seems to match this problem. Any insights or hints on what could be causing this error would be greatly appreciated.

Thank you for your assistance.

Best regards,
Alfredplpl

**Comment by alfredplpl** [comment]
Sorry. I just have found a command error.
**dataset_config=detailed_images.json** is NOT correct.
**dataset_config=detailed_images.toml** is  correct.

Thanks.
