### ISSUE TITLE
I'm getting a "ModuleNotFoundError: No module named 'scipy' " on Pop OS system (aka Debian with better native graphics support)

### ISSUE THREAD

**Issue by Cratopea** [kohya-ss/sd-scripts#928]
Hi,

Server runs but throws the below error about 'scipy' being missing when I try to train anything. I tried to install it manually with "pip install scipy" and scipy installs fine but I still get the same error, despite the module being present in the venv. Would appreciate any advice as to how I might fix this. 

  File "/home/user1/venv3/kohya_ss/library/train_util.py", line 3419, in get_optimizer
    import bitsandbytes as bnb
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 8, in <module>
    from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/adagrad.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer1State
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 12, in <module>
    import bitsandbytes.functional as F
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 12, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/venv3/kohya_ss/./train_network.py", line 1009, in <module>
    trainer.train(args)
  File "/home/user1/venv3/kohya_ss/./train_network.py", line 338, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/user1/venv3/kohya_ss/library/train_util.py", line 3421, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "/home/user1/venv3/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/user1/venv3/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user1/venv3/kohya_ss/venv/bin/python', './train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/home/user1/Spiders', '--resolution=512,512', '--output_dir=/home/user1/venv3/kohya_ss', '--logging_dir=/home/user1/venv3/kohya_ss', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=4235', '--train_batch_size=2', '--max_train_steps=42350', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by Cratopea** [comment]
The venv environment I created was being overridded by the Kohya environment, when I activated that environment it turned out that the scipy module wasn't installed by the kohya script. I installed it with pip in that venv and now Kohya is training correctly. 

Unless I missed a step in the instructions specific to installing scipy under linux on the front page, this step should be added or the auto install script should be updated to include scipy. Scipy doesn't seem to be in the requirements file, I have never tried to make a self-installing program before but it seems like maybe scipy should be listed in that file. 

And thanks so much for the work in making this software available.

**Comment by rockerBOO** [comment]
Could be related to this error.

> ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです

Could try to install that (which might be where the scipy is required? not sure.)

**Comment by Cratopea** [comment]
Thanks for the reply. Bitsandbytes was already installed when I called the requirements file as part of the install process. What fixed the problem was manually installing scipy with pip inside the venv used by the kohya script. I mentioned it above but scipy isn't in the requirments file, so I think that may be what caused the problem.

**Comment by noahjgreer** [comment]
Still getting this issue, I am receiving the exact error quoted from above. I tried installing scipy manually, but it appears that it was already installed in the venv. Here's my output:

```
←[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

←[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
←[1;33m=============================================================←[0m

15:51:08-730878 INFO     Version: v22.1.1

15:51:08-738885 INFO     nVidia toolkit detected
15:51:13-077936 INFO     Torch 2.0.1+cu118
15:51:13-120975 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:51:13-122977 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 SUPER VRAM 8192 Arch (7, 5) Cores 34
15:51:13-124979 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
15:51:13-131985 INFO     Verifying modules installation status from requirements.txt...
15:51:17-815253 INFO     headless: False
15:51:17-823260 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
15:51:38-722123 INFO     Loading config...
15:51:40-191035 INFO     Loading config...
15:51:44-681757 INFO     Save...
15:51:51-049039 INFO     Start training Dreambooth...
15:51:51-071059 INFO     Valid image folder names found in: F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/img15:51:51-074062 INFO     Valid image folder names found in: F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/reg15:51:51-076064 INFO     Folder 25_f1nni fox : steps 175
15:51:51-078065 INFO     Regularisation images are used... Will double the number of steps required...
15:51:51-082069 INFO     max_train_steps (175 / 1 / 1 * 12 * 2) = 4200
15:51:51-085072 INFO     stop_text_encoder_training = 0
15:51:51-086073 INFO     lr_warmup_steps = 0
15:51:51-088074 INFO     Saving training config to
                         F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/model\lora_Finni-v1.1-NoAI_SD15_202311                         12-155151.json...
15:51:51-091079 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_db.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/img"
                         --reg_data_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/reg"
                         --resolution="512,512"
                         --output_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/model"
                         --logging_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/log"
                         --save_model_as=safetensors --output_name="lora_Finni-v1.1-NoAI_SD15"
                         --lr_scheduler_num_cycles="12" --max_token_length=150 --learning_rate="0.0001"
                         --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="4200"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="58008"
                         --cache_latents --optimizer_type="AdamW8bit" --max_token_length=150 --clip_skip=2
                         --bucket_reso_steps=64 --shuffle_caption --xformers --bucket_no_upscale --noise_offset=0.0
15:51:58-328674 INFO     The running process has been terminated.
15:51:58-688002 INFO     There is no running process to kill.
15:51:58-855659 INFO     There is no running process to kill.
15:51:59-016806 INFO     There is no running process to kill.
15:51:59-158935 INFO     There is no running process to kill.
15:51:59-319082 INFO     There is no running process to kill.
15:52:21-738803 INFO     Loading config...
15:52:23-172970 INFO     Loading config...
15:52:29-827693 INFO     Start training LoRA Standard ...
15:52:29-837703 INFO     Checking for duplicate image filenames in training data directory...
15:52:29-839704 INFO     Valid image folder names found in: F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/img15:52:29-841706 INFO     Valid image folder names found in: F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/reg15:52:29-843708 INFO     Folder 25_f1nni fox: 7 images found
15:52:29-844709 INFO     Folder 25_f1nni fox: 175 steps
15:52:29-845710 WARNING  Regularisation images are used... Will double the number of steps required...
15:52:29-849714 INFO     Total steps: 175
15:52:29-850715 INFO     Train batch size: 1
15:52:29-852716 INFO     Gradient accumulation steps: 1
15:52:29-853717 INFO     Epoch: 12
15:52:29-855719 INFO     Regulatization factor: 2
15:52:29-856720 INFO     max_train_steps (175 / 1 / 1 * 12 * 2) = 4200
15:52:29-858722 INFO     stop_text_encoder_training = 0
15:52:29-860724 INFO     lr_warmup_steps = 0
15:52:29-861725 INFO     Saving training config to
                         F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/model\lora_Finni-v1.1-NoAI_SD15_202311                         12-155229.json...
15:52:29-864727 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/img"
                         --reg_data_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/reg"
                         --resolution="512,512"
                         --output_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/model"
                         --logging_dir="F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/log"
                         --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --network_dim=8
                         --output_name="lora_Finni-v1.1-NoAI_SD15" --lr_scheduler_num_cycles="12" --no_half_vae
                         --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1"
                         --max_train_steps="4200" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --seed="58008" --cache_latents --optimizer_type="AdamW8bit"
                         --max_token_length=150 --clip_skip=2 --bucket_reso_steps=64 --shuffle_caption --xformers
                         --bucket_no_upscale --noise_offset=0.0
prepare tokenizer
update token length: 150
Using DreamBooth method.
prepare images.
found directory F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox contains 7 image files
No caption file found for 7 images. Training will continue without captions for these images. If class token exists, it will be used. / 7枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00000-0-image-000.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00001-0-image-001.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00002-0-image-002.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00003-0-image-003.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00004-0-image-004.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox\00005-0-image-005.png... and 2 more
found directory F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox contains 200 image files
No caption file found for 200 images. Training will continue without captions for these images. If class token exists, it will be used. / 200枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d05351a88695810ce59ddca92080cd37.jpg
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d131cb2277d8e370ab5a04183ded0bb6.jpg
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d14dfc8b13ed925db973047c3828de90.jpg
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d15ac65a8720ebc664039d2681266782.png
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d15ba6e15ff454ba64b3d51af21e5de8.jpg
F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox\d16ec70b2151c66fa5c87162937cda93.png... and 195 more
175 train images with repeating.
200 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\img\25_f1nni fox"
    image_count: 7
    num_repeats: 25
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: f1nni fox
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "F:\StableDiffusionProjects\LoRA\Character\Finni-v1.1-NAI\reg\1_fox"
    image_count: 200
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: fox
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 182/182 [00:00<00:00, 5510.14it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 320), count: 1
bucket 1: resolution (448, 448), count: 5
bucket 2: resolution (512, 512), count: 319
bucket 3: resolution (576, 384), count: 25
mean ar error (without repeats): 0.0
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.23s/it]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable xformers for U-Net
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████████████████████████████████████████████████████████| 182/182 [00:00<?, ?it/s]
caching latents...
100%|████████████████████████████████████████████████████████████████████████████████| 182/182 [01:09<00:00,  2.62it/s]
create LoRA network. base dim (rank): 8, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\library\train_util.py", line 3419, in get_optimizer
    import bitsandbytes as bnb
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>    from . import cuda_setup, utils, research
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\train_network.py", line 1009, in <module>
    trainer.train(args)
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\train_network.py", line 338, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\library\train_util.py", line 3421, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "F:\StableDiffusionProjects\kohya_ss-22.1.1\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\StableDiffusionProjects\\kohya_ss-22.1.1\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/img', '--reg_data_dir=F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/reg', '--resolution=512,512', '--output_dir=F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/model', '--logging_dir=F:/StableDiffusionProjects/LoRA/Character/Finni-v1.1-NAI/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_dim=8', '--output_name=lora_Finni-v1.1-NoAI_SD15', '--lr_scheduler_num_cycles=12', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=4200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=58008', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_token_length=150', '--clip_skip=2', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
Keyboard interruption in main thread... closing server.
Terminate batch job (Y/N)? y

(venv) F:\StableDiffusionProjects\kohya_ss-22.1.1>pip install scipy
Requirement already satisfied: scipy in f:\stablediffusionprojects\kohya_ss-22.1.1\venv\lib\site-packages (1.11.3)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in f:\stablediffusionprojects\kohya_ss-22.1.1\venv\lib\site-packages (from scipy) (1.24.1)

[notice] A new release of pip available: 22.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) F:\StableDiffusionProjects\kohya_ss-22.1.1>
```

**Comment by Cratopea** [comment]
What fixed it for me was the fact that the venv I made and ran the script from wasn't the venv that Kohya was running in. 

Instead there's a directory on my system created by Kohya located at \kohya_ss\venv that I had to manually activate rather than using the venv I created for the install per the instructions. Once I activated the venv that was created by the install script and ran "pip install scipy" inside that venv Kohya worked as expected. May or may resolve your issue and that may already be the venv you're using, that's just what I had to do to fix it on my system. Also not saying I didn't mess up somewhere to cause this issue, though I think the fact that scipy isn't in the requirements file suggests that they may actually be a problem here.

I followed these instructions: 
git clone https://github.com/kohya-ss/sd-scripts.git
cd sd-scripts

python -m venv venv
.\venv\Scripts\activate

pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
pip install --upgrade -r requirements.txt
pip install xformers==0.0.20

accelerate config

And got the same error you're getting when I tried to train. It seems like maybe scipy needs to be added to the requirements.txt file, it isn't there in my copy. If nothing else works you could try removing Kohya and manually adding scipy in requirements.txt before running "pip install --upgrade -r requirements.txt" 

If none of that works this git seems to have better documentation and install scripts that might work: https://github.com/bmaltais/kohya_ss

**Comment by noahjgreer** [comment]
Thanks so much for your help and your detailed explanation. I will try this out!
